### ISSUE TITLE
Add thumbnail lookup logic for Met CSV

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/dlme#101]
Looks like you can create thumbnail links by the following logic:

```
http://images.metmuseum.org/CRDImages/an/original/ss{Object Number}gp.JPG
```
Need to have check in case doesn't work for a few objects.

(low priority addition)

**Comment by anarchivist** [comment]
See discussion on metmuseum/openaccess#2 - there looks like there's an API that we could use to get the thumbnail URIs.
