### ISSUE TITLE
Improving Arabic search

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1010]
Some comments we received indicate that Arabic search might not be working as it should. 

Examples:
- Searching `أخبار` in the search box (with `Everything` selected) should return https://dlmenetwork.org/library/catalog/81055%2Fvdc_100023677047.0x000007_dlme as this record has the title "Qaul fī al-akhbār allātī yukhbir bihā kathīrūn قول في `الأخبار` التي يخبر بها كثيرون Ḥasan ibn Sahl حسن بن سهل" which include الأخبار –a two-word compound, consisting of the query term prepended by `ال`, the definite article. 
- Searching `كثير` should return the same record from the previous example as that title the record contains the word `كثيرون`
- Searching `أغراض ` should return https://dlmenetwork.org/library/catalog/81055%2Fvdc_100030447153.0x000002_dlme as the compound `وأغراضها` found in the title contains that word

These examples suggest that the terms in the metadata are not being properly tokenized, however, analyzing these terms in the DLME Solr test instance indicates that they should be, if the analyzers were used as expected.

A joint team from Stanford and QNL identified the following actions that could be taken:
- [x] Check that the DLME app is applying lang tags to Solr correctly. @mejackreed suspects that Solr could be looking for fields with `ar` tags when the fields are actually tagged `ar-Arab` in Solr. This step may be enough to solve the problems.
- [ ] Test Solr results in [QDL](http://51.138.59.18:8983/solr/#/) and DLME.
- [ ] QNL team contact the team that developed farasa-their custom Arabic analyzer to determine how, if at all, farasa improves upon the native Arabic Solr analyzer currently deployed in DLME.
- [ ] If it is determined that farasa is an improvement over the native Arabic Solr analyzer, implement farasa in DLME. Arif can give an example of how the Solr config calls the farasa anlyzer.

[documented search notes](https://docs.google.com/document/d/1nQ9LOmEkjqO70p3pMyjTPmovOjt2FDjuDnZBPKWhqOg/edit)

**Comment by jacobthill** [comment]
Potentially useful post: https://medium.com/@ramzialqrainy/checking-arabic-relevance-with-apache-solr-2eb0d1b21395

**Comment by jacobthill** [comment]
[documented search errors](https://docs.google.com/document/d/1nQ9LOmEkjqO70p3pMyjTPmovOjt2FDjuDnZBPKWhqOg/edit)

**Comment by jacobthill** [comment]
Can we highlight the searched term in the metadata so the user can see?

**Comment by mejackreed** [comment]
I believe this is due to an issue with the prod DLME solr configs not being synced up. See: https://gist.github.com/mejackreed/7ab312940dffe1739df5ce92a545e517

**Comment by mejackreed** [comment]
@jacobthill the three examples you gave above are now resolved in production. The change being:
 - @aaron-collier was able to update our production Solr configs in the DLME prod Solr AMI
 - A reindex was kicked off
 - I manually tested all three scenarios with the expected records now returning

Also worth noting the previous configs did not have search fields appropriately configured so that title/author searches would not return correctly. This has now been resolved as well.

Based off of the comparison of tokenization during the workshop and now with production using the correct configs, I think we are in a good place here unless we can come up with some more specific examples that we could investigate.

**Comment by jacobthill** [comment]
@mejackreed great, I will do some testing as well and compare to QDL to see if there is any advantage to using their custom analyzer.

**Comment by aaron-collier** [comment]
@jacobthill is this closable now?

**Comment by jacobthill** [comment]
@aaron-collier no I think we need to do the testing still.

**Comment by jacobthill** [comment]
DLME search works as I expect it to. After fixing https://github.com/sul-dlss/dlme/issues/1073 a user can search over specific fields or everything. A query without quotation marks returns fuzzy matches while the same query with quotation marks returns exact results only. I am moving this to the QNL QA column to see if @mwerla or @asmaaalkuwari can find any reason to adopt the custom analyzer used in QDL over the current DLME implementation.

**Comment by mwerla** [comment]
@jacobthill  We will get in touch with the team responsible for the analyzer used at QDL to find out what they recommend and why.

**Comment by jacobthill** [comment]
@mejackreed searching over everything for identifier values doesn't work. Do we include the 'id' and 'cho_identifier' fields in our search settings? For example https://dlmenetwork.org/library/catalog/81055%2Fvdc_100000000046.0x000087_dlme has identifier "Add MS 14056". You get 0 results if you search for:
- MS 14056
- "MS 14056"
- "Add MS 14056"

How much work would it be to configure "Identifier" as a drop down option and also to include  'id' and 'cho_identifier' in the 'Everything' search results?

**Comment by mejackreed** [comment]
No we don't include those fields to be searchable. If they should be searchable and/or have a search field, can you create a new ticket for that work? This feels a little bit beyond "Improving Arabic search" and the remaining tasks here.

**Comment by jacobthill** [comment]
@mejackreed I'll open a new ticket

**Comment by jacobthill** [comment]
This is assumed done unless @mwerla finds any issues during his review. My instinct is that we've over tuned a bit a recall may be suffering too much. Moving to QA/QNL for now.

**Comment by thatbudakguy** [comment]
closing since material related to this ticket seems done
