### ISSUE TITLE
Add links back to the user site for iiif objects

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1011]
Objects without iiif link back to the user site but objects with iiif do not. Should we add a link?

**Comment by ggeisler** [comment]
Yes, it makes sense to me to be consistent. Something like this:

<img width="865" alt="Screen Shot 2020-06-05 at 9 30 26 AM" src="https://user-images.githubusercontent.com/101482/83901534-c7ffce80-a70f-11ea-806c-327ea30b214d.png">

### A 
- Add a link to the contributor site directly below the viewer element with the label: `View on contributor website`
- Reduce the bottom margin on the the `#m3` element to `0.5rem`

### B
- Give the new IIIF-contributor link a bottom margin of `2rem` so we have some vertical space between the link and the start of the metadata

**Comment by cbeer** [comment]
@ggeisler are we adding this link for all embed varieties (IIIF, static image, and oembed)?

**Comment by ggeisler** [comment]
Yes, I think we want to be consistent and show it on all show pages. I thought we were already doing it for the non-IIIF scenarios:

<img width="353" alt="Screen Shot 2020-06-05 at 10 09 44 AM" src="https://user-images.githubusercontent.com/101482/83904538-e1574980-a714-11ea-9eac-b8123d46148f.png">

**Comment by cbeer** [comment]
Fixed by #1017
