### ISSUE TITLE
Display default image instead of broken image

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1012]
This is an example of a record with a missing image: https://dlmenetwork.org/library/catalog/oai:swco-ir.tdl.org:10605%2F357467

**Comment by cbeer** [comment]
That  image is point at https://spotlight.dlmenetwork.org/assets/default-52adc3dc03639885e8aa93763e29868269dd3b9dad4689f140c0175b4f945922.png and  seems to be present in the IR that way.

**Comment by jacobthill** [comment]
Ah, yes. I think this is because it would not load otherwise. Let me try and confirm

**Comment by cbeer** [comment]
Ok. I should also note, you probably don't want to hard-code that URL in any data. The checksum  at the end of the image name is calculated based on the image content, so if we ever change that image all your images will break.
