### ISSUE TITLE
Consider changing "unknown" to "date unknown" in date filer

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1014]
<img width="273" alt="Screen Shot 2020-06-05 at 10 54 03 AM" src="https://user-images.githubusercontent.com/37662787/83891316-f46d1800-a71a-11ea-8cb9-a2bd266d3c4b.png">

"In the date filter the “Unknown” value is a bit mysterious. Maybe it could help to rename it to “Date unknown”?"

**Comment by ggeisler** [comment]
"Date unknown" seems reasonable to me. I'm not sure where we would need to override the label for this (or if there is some challenge to doing that) so I'm unassigning myself. This should be a developer task.

**Comment by cbeer** [comment]
I don't think we'll want to do this upstream, so it'll need to go into this app's locales file.

**Comment by ggeisler** [comment]
👍 By "where" I didn't mean where in the ecosystem but where in the app (didn't realize it was just a locale string).
