### ISSUE TITLE
Arabic pluralization issue

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1020]
Transifex is raising [warnings](https://www.transifex.com/sul-dlss/dlme/translate/#ar/config-locales-en-yml--master/286839573?q=reviewed%3Ano) on some plural forms because the singular form in English has a hard coded 1 instead of the `formatted_count` variable. I'm not sure if the English should be changed or the Arabic. I want to confirm with @camillevilla because I'm not sure what effect changing the English will have on the Transifex PR or which approach is desirable. In [some cases](https://www.transifex.com/project-blacklight/spotlight-2/translate/#ar/config-locales-spotlight-en-yml--master/285994776?q=reviewed%3Ano) the English form is not hard coded; in others it is. 

Also, possibly related, there is a display issue in the statistics page in Arabic. There is an extra letter و which means 'and' being added at the end of the intended string. I don't know where it comes from but I'm wondering if the mismatch of `{` may be causing this? Not sure where else to look for it.

<img width="332" alt="Screen Shot 2020-06-16 at 9 47 50 AM" src="https://user-images.githubusercontent.com/37662787/84782929-a677d000-afb6-11ea-8026-f203f4b1a136.png">
<img width="380" alt="Screen Shot 2020-06-16 at 9 54 41 AM" src="https://user-images.githubusercontent.com/37662787/84783577-6e24c180-afb7-11ea-9e4b-14eef4c8931f.png">

**Comment by camillevilla** [comment]
Closed by #1025
