### ISSUE TITLE
Unintended authorization message

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1041]
Navigating to https://dlmenetwork.org/library/about/exhibits and then switching to the Arabic view results in a "You are not authorized to access this page" message.
<img width="1203" alt="Screen Shot 2020-07-24 at 1 23 11 PM" src="https://user-images.githubusercontent.com/37662787/88417999-e3eb2c80-cdb0-11ea-8742-d16cfae683a8.png">

**Comment by anarchivist** [comment]
The Arabic version of this page is not published. This error should go away if the page is set to published.

**Comment by jacobthill** [comment]
Got it, thanks for pointing that out.
