### ISSUE TITLE
Improve language display logic

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1052]
When mapping data the data manager has the option of assigning a language to each field e.g. if the title field is in Arabic language and Arabic script the `ar-Arab` value can be assigned to the title. In some cases it is unclear what the language will be during mapping because no language is provided in the incoming metadata. In some cases the data manager can programmatically determine the language or manually assign the language (when all values are in the same language). In other cases, however, this is not possible and the value `none` is assigned by default. This value is used to determine when that title (or any field) will be displayed in the application. Currently the display logic is a bit unclear (to me) and may need revising. I believe the logic is:

- `ar-Arab` values will be displayed in the Arabic view if available, other wise `en` will be displayed, otherwise any language available will be displayed
- `en` values will be displayed in thee English view, otherwise any language available will be displayed

Proposed changes:
- [x] need a way of specifying a known script and an unknown language. There are often cases where the title has been transliterated but it is Arabic or Persian. There are other cases where we know it is Arabic script but can't tell if its Turkish, Arabic, Persian, etc. Need something like (e.g. lang('unk-Arab') and lang('unk-Latn'))
- [ ] any '*-Latn' value should display in the English view before any value in Arabic script
- [ ] any '*-Arab' value should display in the Arabic view before any value in Latn script

Need to finalize this with QNL.

**Comment by anarchivist** [comment]
For the first item, `und` is a valid code for "Undetermined" in ISO 639-2.

I'd want to have someone (maybe @ggeisler) consult on the UX impact of the second two before we roll out the change.

**Comment by jacobthill** [comment]
That is good to know. I will start using 'und-Latn' etc. instead of 'none'. @ggeisler do you have any concerns about the second and third items? My thought was that a user in Arabic would rather see a Persian title instead of an English. They are more likely to be able to read it. The same would go for a western user. Currently if there is a 'none' value and and 'ar-Arab' value the latter will display in the English view. I don't know if we have configured any display logic for 'und' values. Its probably a good idea though to figure out what we can/should do from our side before surfacing this issue with QNL.

**Comment by ggeisler** [comment]
@jacobthill Is it safe to assume a metadata value with `und-Latn` is always some readable Latin text? 

If I understand correctly, I think what you're suggesting is that we extend our current logic for deciding which language version of metadata values to display based on the user's current locale to include language values with `und-` prefixes. If that's an accurate interpretation and it's technically feasible, it makes sense to me. 

This does assume that users in the Arabic locale are more likely to be able to read any language using Arabic script than a Latin language, and vice-versa, correct?

That seems like a reasonable assumption thinking about it from English locale point of view, though I don't have enough understanding of Arabic languages to know how true that is from the Arabic locale point of view.

**Comment by jacobthill** [comment]
@ggeisler I think we are on the same page. I think every value with `und-Latn` should be better the something in Arabic characters. There will be things like "Laṭāʼif al-kalām fī aḥkām al-aʻwām." but that will be better to most westerners than "لطائف الكلام في احكام الاعوام". At least they can kind of pronounce it. It will also allow us to assign `und-Latn` to many cases that are actually English. In some cases the values are mixed English and transcribed Arabic, etc. and I can't always safely determine which one it is. By assigning `und-Latn` to all of them they will all be displayed in the English view. So overall I think it will be a minor improvement in cases where only transcribed Arabic is available but a major improvement where we actually have English titles. I think its safe to assume the same is true for Arabic but I will consult with QNL to get their take.

**Comment by mejackreed** [comment]
@jkeck I found an example that can be used to get going.

https://dlmenetwork.org/library/catalog/penn_mmw-0001-550

A specific use case here is that `und-Latn` should be preferenced to be displayed when the site language is English and `fa-Arab` should be preferenced when in Arabic.

```yaml
cho_title.und-Latn_ssim:
- Laṭāʼif al-kalām fī aḥkām al-aʻwām.
cho_title.fa-Arab_ssim:
- لطائف الكلام في احكام الاعوام
```

**Comment by jacobthill** [comment]
This [record](https://dev.dlmenetwork.org/library/catalog/2e3a3c8d-1465-4721-9923-12436f367498) shows the new feature with Latin text and Persian.

**Comment by mwerla** [comment]
@jacobthill Let's review that together during the Wednesday call please.
