### ISSUE TITLE
Add social media icons

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1060]
Do we want to link to social media accounts (twitter and instagram) from the application?
- [ ] choose icons
- [ ] twitter: https://twitter.com/dlmenetwork
- [ ] instagram: @dlmenetwork

**Comment by ggeisler** [comment]
I don't think we can do any design on this without more information. Why do we want to add social media icons? What are the motivating use cases?

**Comment by jacobthill** [comment]
CLIR wants to make it easy for users to follow our twitter and instagram accounts.

**Comment by jacobthill** [comment]
If we need to do this its better to do it in a dedicated about page that won't effect the rest of the ui.

**Comment by jacobthill** [comment]
Need to work out social media comms policy before adding icons. Should also consider adding icons in records to tweet about a record, etc.
