### ISSUE TITLE
Improving display of gallery view search results 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1065]
When viewing the [browse time categories](https://dlmenetwork.org/library/browse/622-900-ce) it looks like the thumbnails are scaled down to the same width, which is calculated on the basis of the number of items in the row. We are not scaling thumbnails up. The number of records displayed don't divide evenly by the number of records per row which causes the last row to have larger thumbnails.
<img width="594" alt="Screen Shot 2020-10-08 at 9 47 50 AM" src="https://user-images.githubusercontent.com/37662787/95467376-606ebf80-094b-11eb-87e2-3e4090d89443.png">
- [Exhibits #1942](https://github.com/sul-dlss/exhibits/issues/1942) change the default number of records displayed to multiples of 12 (e.g. 12, 24, 36, 48) [not necessarily all of them] so that the total number of results displayed divide evenly into 6, 4, 3, 2, or 1.
- #1084 consider possibilities for displaying additional metadata to better differentiate between items (in the above example the amulets look like the same object because the data provider used the same thumbnail and title for each. Its not clear what can be done though given the limited metadata available.)
- #1083 Fix three columns view (when three columns are displayed the first space is empty e.g. https://dlmenetwork.org/library/catalog?utf8=%E2%9C%93&exhibit_id=library&search_field=all_fields&q=coin) 
<img width="598" alt="Screen Shot 2020-10-08 at 11 15 55 AM" src="https://user-images.githubusercontent.com/37662787/95478693-dda03180-0957-11eb-9551-64ce2ac68461.png">.

Some examples of other sites:
https://www.europeana.eu/en/search?page=1&view=grid&query=amulet
https://www.loc.gov/collections/?q=india
https://fbc.pionier.net.pl/search#fq={!tag=dcterms_accessRights}dcterms_accessRights%3A%22Dost%C4%99p%20otwarty%22&q=amulet

**Comment by jacobthill** [comment]
Consider adding institution and identifier to metadata to differentiate similar looking objects

**Comment by ggeisler** [comment]
@jacobthill I've updated your original comment in this ticket to replace the three todo boxes with links to separate tickets. I did that because the three items you mention seem very distinct work items and it seems like it'll be easier to work on them and track them separately.

I'll leave this ticket open in case there is something here I didn't capture in the new tickets, but ideally it would be great if you could close this one so it's clear there is no work to be done here that isn't covered in more specific tickets. (And if there is something else you think needs attention in gallery view, you could create a specific ticket for it and then close this one.)

**Comment by mwerla** [comment]
@jacobthill Let's review this together in the Wednesday call. There is an improvement, but the overall impression is still quite messy: 

![image](https://user-images.githubusercontent.com/562200/105093184-5f553e80-5ab3-11eb-83b8-2ba9e55fb094.png)

Comparing for example to LoC handling of different proportions of thumbnails:

![image](https://user-images.githubusercontent.com/562200/105093260-801d9400-5ab3-11eb-92b5-530f77702998.png)

**Comment by jacobthill** [comment]
@mwerla sounds good. FYI we have some additional improvements that will be made when remapping that will effect both of these sets and some others. Instead of just mapping whatever thumbnail image the provider offers in the metadata, I will map to a larger (but not too large) thumbnail when possible.
