### ISSUE TITLE
Searching over 'Title' and 'Creator /Contributor' field does not work in English or Arabic

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1073]
Searching "How are the mighty fallen" in 'Everything' returns https://dlmenetwork.org/library/catalog/oai:cdm15795.contentdm.oclc.org:p15795coll8%2F221. Searching "How are the mighty fallen" in 'Title' returns nothing. Similar examples can be found with the 'Creator /Contributor' field.

**Comment by mejackreed** [comment]
I believe this is due to an issue with the prod DLME solr configs not being synced up. See: https://gist.github.com/mejackreed/7ab312940dffe1739df5ce92a545e517

**Comment by mejackreed** [comment]
This was resolved on 2020-12-10 but commented on here: https://github.com/sul-dlss/dlme/issues/1010#issuecomment-742574645 in the related "search" ticket. 

 - Production configs were updated
 - All content was reindexed
 - Testing of the functionality was done.

Search fields were not properly configured in the production Solr environment, and were not synced from the GitHub repository.

**Comment by mwerla** [comment]
Checked in production, looks ok to me.
