### ISSUE TITLE
Introduce collapsible fields for item view

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1075]
Some description field values are quite long e.g. https://dlmenetwork.org/library/catalog/006818820. QNL would like us to explore collapsing these fields (when they exceed a certain length) as a default.

**Comment by ggeisler** [comment]
@jacobthill Are there fields other than Description that came up in this discussion with QNL? 

Description seems like the only one likely to have excessively long values, but the part of your comment where you say "collapsing these fields" makes me uncertain if you know about others.

One potential challenge to collapsing Description might be that is appears to be (at least in the longer examples I've seen) composed of multiple paragraphs. It seems like a strategy of collapsing after N number of lines, which would be my first recommendation, might be harder if those lines extend over multiple paragraphs. But I'll leave that to a developer to determine, and offer two options:

### Option A - Collapse after N lines
Where N might be `10`, though making that configurable could be handy for adjusting in the future.

With this option we would use the responsiveTruncator to add a "more..." link after the first 10 lines of the Description value, if the Description value is more than 10 lines. Selecting the "more..." link expands the entire Description value and changes the link to a "less..." link. Selecting the "less..." link collapses the field value back to the original state.

#### Initial state when more than N lines
<img width="794" alt="Screen Shot 2020-11-13 at 12 38 12 PM" src="https://user-images.githubusercontent.com/101482/99115401-91c45600-25af-11eb-9e2e-5bd1e7997a14.png">

#### Expanded state
<img width="794" alt="Screen Shot 2020-11-13 at 12 40 17 PM" src="https://user-images.githubusercontent.com/101482/99115429-9ab52780-25af-11eb-9e33-804d5bdcbad5.png">

### Option B - Collapse after N paragraphs
Option A assumes we can count lines across different paragraphs, which might not be an accurate assumption. An alternative approach would be to add the "more..." link after a certain number of Description value paragraphs, such as 3. 

A drawback of this approach is if any of the first three paragraphs have a lot of text, the Description value displayed even when collapsed could be long. But it seems unlikely that very many objects will have particularly long descriptions in more than one of the first three paragraphs, so in most cases the initial collapsed view of the Description field is unlikely to be too long (and we could make N = two paragraphs to reduce the likelihood further).

#### Initial state when more than N paragraphs

<img width="794" alt="Screen Shot 2020-11-13 at 1 02 18 PM" src="https://user-images.githubusercontent.com/101482/99116156-c71d7380-25b0-11eb-931b-1cc8cb572506.png">

**Comment by jacobthill** [comment]
@ggeisler "Description" was the only example that came up with QNL. There are some cases, like this [Michigan record](https://dlmenetwork.org/library/catalog/006813660) that have relatively long "Geographic region" values. I can imagine this happening with fields like "Subject" as well. In this case though I think 2 of these values don't need to be in there; our Marc extraction macros are extracting too much. So maybe ~5 lines is about as much as we can reasonably expect in these other fields. I'll defer to you to determine if that is too long or not.

**Comment by ggeisler** [comment]
@jacobthill Yeah, I think 5 or 6 lines in those other fields are fine. It does increase the need for scrolling a bit, but the values in those fields are short, so it's easy to scan the values quickly and move past them. If we regularly had 15 or 20 values in those fields, then yes, that would be something to address.

**Comment by jacobthill** [comment]
@ggeisler Here is a record with 17 lines in the spatial field https://dlmenetwork.org/library/catalog/81055%2Fvdc_100000000193.0x000065_dlme. Its not very common but it does happed

**Comment by jacobthill** [comment]
@ggeisler Here is a record with a ridiculously long subject field: https://dev.dlmenetwork.org/library/catalog/4204

**Comment by mwerla** [comment]
We support the line-based approach, with N set to something like 6 lines.
The 2nd comment is that the more... / less... links are hard to notice as they are just short texts in a wall of text. Making them look like buttons or adding some other visual element (like an arrow?) could help to make it easier to spot.

**Comment by jacobthill** [comment]
@ggeisler @mejackreed I think this can be moved to ready unless design is needed for the visual elements Marcin suggested.

**Comment by mejackreed** [comment]
Just going to outline the needed work here:

- [ ] Proceed with Option A using 6 lines

**Comment by ggeisler** [comment]
I added _design needed_ just to represent the need for an additional mockup for the styling of the expand/collapse element, to address @mwerla's comment.

Will try to get to it soon, just balancing against all the other in-progress design updates. (Though development work could probably start on this now and we could easily adjust the styling later.)

**Comment by ggeisler** [comment]
@mwerla Below are a few mockups showing a button-like affordance for expanding/collapsing metadata fields where the value exceeds 6 lines.

(You'll probably need to open the images in a new browser window to see them better; I wanted to show the full page so you can see how the button colors fit with the rest of the visual design.)

In these examples, the item has two fields that exceed 6 lines: Description and Geographic region.

### Initial state
Both fields show 6 lines of metadata and then the expand button:

<img width="563" alt="Screen Shot 2021-01-22 at 4 30 55 PM" src="https://user-images.githubusercontent.com/101482/105559970-d6671e80-5ccf-11eb-9f2a-872701721bd4.png">

### After expanding the Description field

<img width="564" alt="Screen Shot 2021-01-22 at 4 31 14 PM" src="https://user-images.githubusercontent.com/101482/105560054-044c6300-5cd0-11eb-9124-a40f4dfd60de.png">

### After expanding both the Geographic region fields

<img width="564" alt="Screen Shot 2021-01-22 at 4 31 32 PM" src="https://user-images.githubusercontent.com/101482/105560088-1af2ba00-5cd0-11eb-8755-2e25e3546016.png">

**Comment by mwerla** [comment]
@ggeisler Thanks, looks good to me. It's much easier to notice than in the plain text version.

**Comment by ggeisler** [comment]
Design details for the approach shown in the [mockups above](https://github.com/sul-dlss/dlme/issues/1075#issuecomment-765749054):

- [ ] If a metadata field extends beyond 6 lines, add an expand/collapse button that reveals the entire field on expansion and reduces it back to 6 visible lines on collapse
- [ ] Button label is `more` or `less` (lower-case)
- [ ] Next to the label add the icon https://fontawesome.com/icons/angle-down?style=solid (expand) or https://fontawesome.com/icons/angle-up?style=solid (collapse)
- [ ] The icons and text label should be part of the same link (i.e., the user should be able to select either the label or the icon to trigger the action)
- [ ] The button should be a small-sized button and use the same color styling as the "Back to search" button (I think `btn-sm btn-outline-secondary` will do it)

Here's the item that I used in my mockups above that has two fields that exceed 6 lines: 

https://dlmenetwork.org/library/catalog/81055%2Fvdc_100000000193.0x000065_dlme

@asmaaalkuwari We will need Arabic translations for:

> more

> less

**Comment by asmaaalkuwari** [comment]
@ggeisler 
More:  أكثر
Less: أقل
