### ISSUE TITLE
Thumbnails displaying in Safari and Firefox but not Chrome

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1076]
DLME used to display a generic image in the case that there was no thumbnail image available. Somewhere along the line this feature broke. For example, https://dlmenetwork.org/library/catalog?f%5Bagg_data_provider_en%5D%5B%5D=American+Numismatic+Society.

**Comment by mejackreed** [comment]
Linking how this is done for Texas Tech here: https://github.com/sul-dlss/dlme-transform/blob/b364de11282c005787aed051467f6aa81ef7210a/traject_configs/texas_tech_config.rb#L70-L75

**Comment by jacobthill** [comment]
@mejackreed I could be wrong but I believe DLME used to add a default generic thumbnail without any changes needed in the config. The Texas Tech example was my attempt to work around this change in behavior. I don't think hard-coding urls is a good idea though. In the case of Texas Tech the url broke when we changed the domain. I assume there is a standard way of doing this but I don't know how it is typically done.

**Comment by ggeisler** [comment]
Just for my clarification, the goal when no thumbnail is available is for things to look like the mockup below, and this ticket is just about figuring out why that is not currently happening?

<img width="993" alt="Screen Shot 2020-11-13 at 12 12 29 PM" src="https://user-images.githubusercontent.com/101482/99111602-ab629f00-25a9-11eb-9812-0999297bf979.png">

**Comment by jacobthill** [comment]
@ggeisler correct

**Comment by cbeer** [comment]
I'm seeing thumbnails for the search result you posted; do you have an example that demonstrates the problem (or is it possible ANS's image server was broken earlier this week?)

**Comment by jacobthill** [comment]
<img width="1049" alt="Screen Shot 2020-11-13 at 3 18 18 PM" src="https://user-images.githubusercontent.com/37662787/99117332-87ac5280-25c3-11eb-859e-c68ae433dfc0.png">
This (above) is a screen shot of the search results I linked above on my computer (in Chrome).
<img width="1229" alt="Screen Shot 2020-11-13 at 3 20 07 PM" src="https://user-images.githubusercontent.com/37662787/99117558-e70a6280-25c3-11eb-8758-6f3fec5a8328.png">
This is what it looks like in Safari and Firefox. 

I was under the impression that the images could not be streamed because American Numismatic Society did not have an https certificate (it seems like it does now though?). @mejackreed do you know what is going on here? Why do the images display in in Firefox and Safari, but not Chrome?

FYI I'm also getting the same problem with this data set; thumbnails show in Safari and Firefox but not Chrome: https://dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=Consejo+Superior+de+Investigaciones+Cient%C3%ADficas+%28CSIC%29

This issue may be related to this ticket https://github.com/sul-dlss/dlme/issues/1074

**Comment by jacobthill** [comment]
I think its just the iiif that can't stream without https. Is that correct?

**Comment by jacobthill** [comment]
I loaded a test record in dev and confirmed that the placeholder image appears as expected:
https://s3-us-west-2.amazonaws.com/dlme-metadata-dev/output-158aa15b-d601-420b-9b1e-1638bbc9efb7.ndjson

I'm going to change the title of this ticket. The problem seems to be why do CSIC and ANS records not display images in Chrome (maybe just on my computer?) but they do on Firefox and Safari. Can others confirm whether or not these two collections display thumbnails in Chrome:
https://dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=Consejo+Superior+de+Investigaciones+Cient%C3%ADficas+%28CSIC%29

https://dlmenetwork.org/library/catalog?f%5Bagg_data_provider_en%5D%5B%5D=American+Numismatic+Society

If its just my computer then I will try to figure out what is wrong with my browser.

**Comment by mejackreed** [comment]
@jacobthill the issue with ANS is because they do not serve HTTPS content, Chrome will not display the thumbnails due to mixed content.

Likely what we will end up needing to do is:
 - Remove the thumbs from the data transform 
 - Make sure our fallbacks work (thumbs for things without thumbs specified)

**Comment by jacobthill** [comment]
Thanks @mejackreed. @cbeer are you maybe using an older version of Chrome? I'm not sure, otherwise, why the thumbs display for you. I think our fall backs are working as far as I can tell so this issue is likely covered in https://github.com/sul-dlss/dlme/issues/1074
