### ISSUE TITLE
Gallery view displays empty slot in first row

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1083]
This appears to be related to our DLME-specific flash message about entering search terms in another language.

Default result page in gallery view:

<img width="928" alt="Screen Shot 2020-11-13 at 4 36 26 PM" src="https://user-images.githubusercontent.com/101482/99130785-892f4800-25ce-11eb-84fb-00229b816252.png">

After selecting "Don't show again" and doing another search:

<img width="928" alt="Screen Shot 2020-11-13 at 4 39 27 PM" src="https://user-images.githubusercontent.com/101482/99130874-d0b5d400-25ce-11eb-8014-d8317a01880a.png">

**Comment by mwerla** [comment]
@jacobthill I am not sure what is expected here from QNL, but the screenshot correctly shows the problem.

**Comment by jacobthill** [comment]
@mwerla I just wanted QNL to see where the problem was coming from and that it will be resolved when the flash message error is fixed. Removing `qnl design` tag.

**Comment by mwerla** [comment]
Looks good to us, but as reported in https://github.com/sul-dlss/exhibits/issues/1942#issuecomment-762626455 there are no thumbnails visible in dev environment.

**Comment by mwerla** [comment]
Looks ok now (with thumbnails).
