### ISSUE TITLE
Consider displaying additional field(s) in Gallery view - Curator action

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1084]
@jacobthill noted in #1065 that many DLME items have the same title, so in Gallery view, where we currently only display the title field to keep the view focused on the image, items are difficult to differentiate. Example: https://dlmenetwork.org/library/browse/622-900-ce

<img width="594" alt="Screen Shot 2020-10-08 at 9 47 50 AM" src="https://user-images.githubusercontent.com/37662787/95467376-606ebf80-094b-11eb-87e2-3e4090d89443.png">

Resolving this is a curator action, deciding which fields, if any, to add to the gallery view using the Configuration > Metadata page.

@jacobthill Note that one of the potential fields you mention possibly adding, Identifier, can be quite long for some records and doesn't work so well in gallery view:

<img width="928" alt="Screen Shot 2020-11-13 at 1 50 51 PM" src="https://user-images.githubusercontent.com/101482/99130476-ab749600-25cd-11eb-933a-f4f7a9f8bec8.png">

**Comment by jacobthill** [comment]
This may be best solved by remapping the title field in collections with highly generic titles to include the generic title plus the id (or a portion of the id).

**Comment by mwerla** [comment]
@jacobthill We still think that it would be good to have the possibility to add extra fields on the single tile, and that can be configurable. The design has to be very "space-aware". We could use for example fields like type or creator or date, which should be self-explanatory, so no field label (like "Identifier") is needed. Moreover, the space for the extra fields values should be fixed to avoid breaking the design (as presented on the screenshot). Whatever is longer than the dedicated space, could be truncated on the thumbnail view.

**Comment by jacobthill** [comment]
@ggeisler see also https://github.com/sul-dlss/dlme/issues/1136 which is somewhat related to this.
