### ISSUE TITLE
Scaling up and down thumbnails

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1086]
1. The current behavior seems to scale down thumbnails in gallery view when a row is full so that all thumbnails have the same maximum width.
2. When thumbnails are smaller than the default no scaling occurs. @mejackreed When iiif is available can we scale images up to the maximum default so we get fewer images that are smaller than the others?
3. When rows are not completely filled the images are wider than the full row default (1). Perhaps no scaling occurs and this is the size, or perhaps the images are still scaled down but the default width is larger than the full row width. This behavior seems to happen in the `Browse by time` categories but I don't see the same behavior when simply selecting a set of records using facets and browsing in gallery view. 

<img width="594" alt="95467376-606ebf80-094b-11eb-87e2-3e4090d89443" src="https://user-images.githubusercontent.com/37662787/99265200-6d56bc80-27ef-11eb-8316-aa33688e9711.png">

**Comment by mwerla** [comment]
@jacobthill I am not sure what is expected here from QNL, but the screenshot correctly shows the problem that we've reported.

**Comment by jacobthill** [comment]
@mwelra nothing needed yet. This is currently a question for the development team. @mejackreed any thoughts on this?

**Comment by mejackreed** [comment]
@jacobthill I've looked into this a bit. I think some of the underlying issues revolve around how a thumbnail is specified. For example in the url: https://dlmenetwork.org/library/browse/622-900-ce


![Screen Shot 2021-01-12 at 12 49 38 PM](https://user-images.githubusercontent.com/1656824/104365141-df3c4100-54d4-11eb-8fad-901fd8fe3bf7.png)

1. Is specified using the `extract_harvard_thumb` method. Although IIIF does also appear available.
https://github.com/sul-dlss/dlme-transform/blob/7b4485f4355704821a8ae5f345506c86d5bb3fc5/lib/macros/harvard.rb#L30-L36

2. Does not appear to be rescalable via IIIF

3. and 4. are not rescalable.

However I have found other examples where image sizes are inconsistent.

https://github.com/sul-dlss/dlme-transform/blob/7b4485f4355704821a8ae5f345506c86d5bb3fc5/traject_configs/cambridge_islamic_config.rb#L119-L125

https://github.com/sul-dlss/dlme-transform/blob/7b4485f4355704821a8ae5f345506c86d5bb3fc5/traject_configs/qnl_config.rb#L93-L98

These cause other display issues on other search results see: https://dev.dlmenetwork.org/library/catalog?utf8=%E2%9C%93&exhibit_id=library&search_field=all_fields&q=

Is it possible to have content with IIIF available to have consistent creation of a thumbnail?

**Comment by jacobthill** [comment]
@mejackreed I'm not sure I completely understand your question. I think my assumption was that if a iiif manifest is provided in the IR in the `agg_preview:wr_is_referenced_by` field that the DLME application would fetch the thumbnail from that manifest. I think the implication of your question is that that is not the case. Instead, the DLME application will use the url provided in the `agg_preview:wr_id` field. Is that correct? If so I can look into that as I re transform the collections. What is the preferred url pattern for iiif thumbnails?

**Comment by mejackreed** [comment]
> Instead, the DLME application will use the url provided in the agg_preview:wr_id field

Yes this is correct.

> What is the preferred url pattern for iiif thumbnails?

Well I hate to answer like this.. but `#ItDepends`.  Some IIIF providers provide some subset of functionality so all features may not be available.

But here is the general algorithm we usually like:

Check IIIF manifest, if there is a thumbnail field, and that field is a IIIF Image API service, request an image like this:

Generic:
`https://imageservice.example.com/:image_service_id/full/!400,400/0/default.jpg`

A Stanford request:
`https://stacks.stanford.edu/image/iiif/tv206kh7995%2F0010_Stamp_full_size_MASTER/full/!400,400/0/default.jpg`

If there is no thumbnail field in the manifest, or if it is not a IIIF Image API service, we grab the service from the first canvas, from the first sequence and craft a similar url.

@ggeisler is the `!400,400` thumb the one you would prefer for DLME?

**Comment by ggeisler** [comment]
> @ggeisler is the !400,400 thumb the one you would prefer for DLME?

Yes, I believe so. That size is sufficient for all application contexts where a thumbnail is involved (results pages, using as a source for a browse category, etc.).
