### ISSUE TITLE
Add search over id fields

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1103]
Some professional users will want to search for records by identifier. This feature will also be helpful for debugging transformations.

- Include 'id' and 'cho_identifier' fields in the search results when searching over "Everything"
- Add a separate drop down search option for 'Identifier' that searches only 'id' and 'cho_identifier'

**Comment by mwerla** [comment]
@jacobthill I think that a separate identifier dropdown will be useful for most professional users, including ourselves. Regarding including id fields in "Everything", yes for sure. But I think the question here should be really why "Everything" is not including everything.
@asmaaalkuwari FYI

**Comment by mejackreed** [comment]
@asmaaalkuwari Can you please provide an Arabic translation for the new `Identifier` search field?

**Comment by asmaaalkuwari** [comment]
@mejackreed the translation for the word "Identifier" would be:
معرّف

**Comment by jacobthill** [comment]
@mejackreed, @cbeer the identifier field is not being indexed and I can search 'Everything' with identifier strings successfully but there is no drop down 'Identifier' search option.

**Comment by mejackreed** [comment]
@jacobthill that is configurable and now can be added by you:

![Screen Shot 2021-01-22 at 11 34 27 AM](https://user-images.githubusercontent.com/1656824/105530951-d3573880-5ca5-11eb-8718-67220206591c.png)

**Comment by mwerla** [comment]
Checked in dev, looks ok to me.
