### ISSUE TITLE
Confirm and/or add additional fields to be searched in "Everything"

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/dlme#1105]
Split out of #1103 

 - Check "Everything" settings to make sure that we are searching all metadata fields with exception of urls, provide list for review. Review application profile with business manager.
 - Review weights for each field.

@jacobthill will provide the fields that will be searchable

@mwerla will provide information about weighting changes he wants. The currently tuned ones are here: https://github.com/sul-dlss/dlme/blob/master/solr/config/solrconfig.xml#L44-L114

**Comment by jacobthill** [comment]
All DLME fields listed, checked are searchable, consult [application profile](https://github.com/sul-dlss/dlme/blob/master/docs/application_profile.md) for details on specific fields:
- [ ] agg_data_provider_collection
- [ ] agg_data_provider_country
- [ ] agg_data_provider_country_ar
- [ ] agg_provider_country
- [ ] agg_provider_country_ar
- [ ] dlme_source_file
- [ ] cho_alternative
- [ ] cho_contributor
- [ ] cho_coverage
- [ ] cho_creator
- [ ] cho_date
- [ ] cho_dc_rights
- [ ] cho_description
- [ ] cho_edm_type
- [ ] cho_extent
- [ ] cho_format
- [ ] cho_has_part
- [ ] cho_has_type
- [ ] cho_identifier
- [ ] cho_is_part_of
- [ ] cho_language
- [ ] cho_medium
- [ ] cho_provenance
- [ ] cho_publisher
- [ ] cho_relation
- [ ] cho_same_as
- [ ] cho_source
- [ ] cho_spatial
- [ ] cho_subject
- [ ] cho_temporal
- [ ] cho_title
- [ ] cho_type
- [ ] id
- [ ] __source
- [ ] agg_aggregated_cho
- [ ] agg_data_provider
- [ ] agg_data_provider_ar
- [ ] agg_dc_rights
- [ ] agg_edm_rights
- [ ] agg_has_view
- [ ] agg_is_shown_at
- [ ] agg_is_shown_by
- [ ] agg_preview
- [ ] agg_provider
- [ ] agg_provider_ar
- [ ] agg_same_as
- [ ] wr_id
- [ ] wr_creator
- [ ] wr_dc_rights
- [ ] wr_description
- [ ] wr_edm_rights
- [ ] wr_format
- [ ] wr_has_service
- [ ] wr_is_referenced_by
- [ ] service_id
- [ ] service_conforms_to
- [ ] service_implements

**Comment by jacobthill** [comment]
@mwerla, @asmaaalkuwari, can you take a look at the above list and let me know if you think any changes should be made?

**Comment by mejackreed** [comment]
Confirming here that when we say "searchable" we mean full text searchable. Some of these fields may be facetable already.

**Comment by jacobthill** [comment]
Good point @mejackreed, I would be fine leaving off some fields like agg_provider, etc. based on the fact that they are available as facets. I will update this list and wait for feedback from @mwerla and @asmaaalkuwari,

**Comment by jacobthill** [comment]
I would be okay leaving off all 'wr_*' fields and the rights fields as well

**Comment by mwerla** [comment]
Looking at the above list, I think it's fine. The fields which are not checked are or already available as filters or contain URLs or rather technical data.
Regarding @jacobthill  comment about leaving off all wr_ fields, I am not sure how wr_creator and wr_description are used. If we are not mapping to it, we can exclude them from search, but looking just at the definition of these fields, they potentially may contain useful information. Regarding rights fields, I would propose to keep it searchable until we will normalize the values and provide rights filter (which could be a nice feature btw.).

**Comment by jacobthill** [comment]
@mejackreed does this require a re-index to take effect in dev? I tried testing it with values in the cho_identifier field but its not working.

**Comment by mwerla** [comment]
@jacobthill What we are supposed to check here? Please be more specific when moving tasks to QA - QNL.

**Comment by jacobthill** [comment]
@marcin its not entirely clear to me what wasn't included in 'Everything' before. The video demo showed the 'cho_extent' field and from our past discussions we knew that the 'cho_identifier' field was not being indexed. These are the fields I checked. If you want a more thorough review, we will need to either look at the PR to see the code changes or ask for a summary from the devs. I wasn't sure how much detail you need.
