### ISSUE TITLE
Improve mobile search design

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1110]
As a DLME user I would like a better mobile search design so that when I search for DLME resources on my cell phone I will have a better search experience. 

The majority of DLME users are accessing the application from a mobile device ~50%

Feedback from QNL UX designer:

- The dropdown filter next to search box is too narrow on mobile, so the chosen option is not fully visible
- The “Find Items by” becomes the title of the main homepage rather than having it on the side with the filters

<img width="248" alt="Screen Shot 2021-01-13 at 8 41 51 AM" src="https://user-images.githubusercontent.com/37662787/104459812-44e30880-557b-11eb-8ad8-df0b8d7b361b.png">

Needs to be considered in relation to https://github.com/sul-dlss/dlme/issues/1108

**Comment by ggeisler** [comment]
I'm closing this because I've created two new, separate tickets to address the separate issues raised in the original description of this ticket. See #1374 and #1375.
