### ISSUE TITLE
Update exhibit feedback link and associated form

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1116]
Based on requests from @mwerla, we have two updates to make to the Feedback link and associated form.

Here's the current form and link:

<img width="1092" alt="Screen Shot 2021-01-14 at 4 21 00 PM" src="https://user-images.githubusercontent.com/101482/104661544-fa9a7e00-5685-11eb-93bc-31c1ebc5354b.png">

---

- **A:** Replace the "Reporting from..." text with:

> To contact us about any matter related to DLME, please use the form below.

I'd suggest we remove the background from the text as well.

- **B:** Change the label of the Feedback link to `Contact us`

After those updates are made, the form and link should look more like this:

<img width="1099" alt="Screen Shot 2021-01-14 at 4 26 44 PM" src="https://user-images.githubusercontent.com/101482/104661705-582eca80-5686-11eb-86a1-84e428ebfe9d.png">

@asmaaalkuwari @mwerla We will need translations for:

> To contact us about any matter related to DLME, please use the form below.

> Contact us

**Comment by mwerla** [comment]
@ggeisler The design looks good to me, thanks!

**Comment by jacobthill** [comment]
I know we asked for translations from Asma for 2 of the 4 strings but I just want to point out that none of them have Arabic translations currently visible in the dev site. If we have translations for the other strings, how do we get them to show?

**Comment by mejackreed** [comment]
Seems like those were missed in the initial review. We will need translations for those strings also.

**Comment by ggeisler** [comment]
Yeah, to be clear, I only asked for translations on this ticket for things that were being changed; I assumed we already had translations for the things that weren't changing.

**Comment by jacobthill** [comment]
@asmaaalkuwari @mwerla We will need translations for all of these:

> To contact us about any matter related to DLME, please use the form below.
> 
> Message
> 
> Your name
> 
> Your email
> 
> Contact us

**Comment by asmaaalkuwari** [comment]
> @asmaaalkuwari @mwerla We will need translations for all of these:
> 
> > To contact us about any matter related to DLME, please use the form below.
> > Message
> > Your name
> > Your email
> > Contact us

**Comment by asmaaalkuwari** [comment]
@jacobthill 
To contact us about any matter related to DLME, please use the form below. 
للاستفسار عن أي مسألة متعلقة بمكتبة الشرق الاوسط الرقمية, الرجاء التواصل معنا من خلال تعبئة النموذج التالي


Message الرسالة

Your name الاسم

Your email البريد الالكتروني

Contact us تواصل معنا

**Comment by jacobthill** [comment]
@mejackreed the "To contact us about any matter related to DLME, please use the form below" Arabic translation should have a period at the end.

**Comment by jacobthill** [comment]
Opened a new ticket to fix alignment in Arabic https://github.com/sul-dlss/dlme/issues/1176. Leaving this in QA/Stanford column until https://github.com/sul-dlss/dlme/issues/1176 is complete so we don't confuse QNL team.
