### ISSUE TITLE
Adjust Date range calendar legend/radio button cols for better responsive display

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1129]
The "Calendar" legend wraps at the `LG` breakpoint:

<img width="226" alt="Screen Shot 2021-01-19 at 9 40 03 AM" src="https://user-images.githubusercontent.com/101482/105066681-45c4e000-5a3c-11eb-86cd-5cbb7ca35a19.png">

I think we can fix this by adjusting the `col` specifications for the `legend` and the following `div` that contains the radio buttons. They are currently `col-sm-4` (legend) and `col-sm-8` (div holding radio buttons).

If we change those to `col-sm-2 col-lg-5` and `col-sm-10 col-lg-7` I believe we'll not have the word "Calendar" breaking at any viewport width:

<img width="640" alt="Screen Shot 2021-01-19 at 9 51 07 AM" src="https://user-images.githubusercontent.com/101482/105067486-f8953e00-5a3c-11eb-940e-46afad70ae5e.png">

Here's the `LG` viewport example above after that change:

<img width="224" alt="Screen Shot 2021-01-19 at 9 52 02 AM" src="https://user-images.githubusercontent.com/101482/105067552-06e35a00-5a3d-11eb-886f-f57254ebb7dc.png">

---

(I'd do a PR myself but I don't have my DLME dev environment up-to-date and am hoping we can fix this before the demo, just in case anyone shows the facet with their browser at the `LG` viewport width.)

**Comment by mwerla** [comment]
English version looks ok, Arabic looks too close to the right border (overlapping). Screenshot from Google Chrome on my mobile phone: 
![WhatsApp Image 2021-01-27 at 14 47 17](https://user-images.githubusercontent.com/562200/105986943-9f698200-60ae-11eb-899c-eca4413b8f3a.jpeg)

**Comment by mejackreed** [comment]
Thanks for checking @mwerla we are tracking this in another ticket https://github.com/sul-dlss/dlme/issues/1137
