### ISSUE TITLE
Update catalog controller config for cho_date_range_hijri_isim to be shown in search configuration

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/dlme#1132]
This will allow for the date range label for cho_date_range_hijri_isim and its translation to be shown to exhibit curator

When in the context of `Spotlight::SearchConfigurationsController`

**Comment by mwerla** [comment]
@jacobthill I have no idea what we are supposed to check here. Please be more specific.

**Comment by jacobthill** [comment]
@mwerla this is a curator facing change. I don't think you all need to review it. I should have moved it to done, will do so now.
