### ISSUE TITLE
Spacing for the Arabic label in the date range facet seems off

### ISSUE THREAD

**Issue by caaster** [sul-dlss/dlme#1137]
![Screen Shot 2021-01-20 at 1 07 25 PM](https://user-images.githubusercontent.com/3210225/105237258-2784e000-5b21-11eb-85bc-2c0be99b248c.png)

**Comment by jacobthill** [comment]
Also problems with the radio buttons on smaller viewports.
<img width="570" alt="Screen Shot 2021-01-21 at 10 03 15 AM" src="https://user-images.githubusercontent.com/37662787/105376472-c9ff9a80-5bd7-11eb-92b0-a92650904f5c.png">
