### ISSUE TITLE
Date range years label spacing issue

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1141]
In some ranges the spacing of the year label is problematic. 
<img width="226" alt="Screen Shot 2021-01-21 at 10 33 02 AM" src="https://user-images.githubusercontent.com/37662787/105373116-51e3a580-5bd4-11eb-8204-2a1b51598b21.png">

**Comment by mwerla** [comment]
The numbers formatting looks better, but the X mark looks strange:
![image](https://user-images.githubusercontent.com/562200/105988120-44388f00-60b0-11eb-90a3-2095bda571a3.png)

**Comment by mejackreed** [comment]
The "X" issue has been reported upstream to Blacklight https://github.com/projectblacklight/blacklight/issues/2423
