### ISSUE TITLE
Rename 'Home' tab to 'Explore' and hyperlink the logo

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1173]
We can rename the 'Home' link to 'Explore'. QNL has approved the current demo in dev. To avoid possible user confusion about how to get back to the main page, we can also hyperlink the logo so that it returns to the 'Explore' page.

**Comment by ggeisler** [comment]
I'm concerned about doing this without taking into account the issues I discussed in https://github.com/sul-dlss/dlme/issues/1029#issuecomment-763248308.

For example, if we don't have a main menu item called "Browse" it will be odd to use the "View all" link from the homepage browse group widget and land on a page with a breadcrumb that has "Browse" in the hierarchy. Basically, if we do this I think we need to remove all traces of the term "browse" in the UI.

**Comment by jacobthill** [comment]
From email from Marcin:

"I get Gary’s points. I propose the following:

 

For now, we have the following menu items:
HOME – leads to the home page (also linked from website logo), which includes:
                                                               i.      “Find items by” section with browsing via filters

                                                             ii.      The short textual introduction above the categories, just to explain to the user where he landed. For example, the first sentence from the current main page: “The Digital Library of the Middle East (DLME) offers free and open access to the rich cultural legacy of the Middle East and North Africa by bringing together collections from a wide range of cultural heritage institutions.” and link like “Read more…” that links to “About page”

                                                           iii.      All the groups of categories that we have defined (yes, with the risk that those below the fold will be less used)

EXPLORE – leads to full categories view like: https://dev.dlmenetwork.org/library/browse
CONTRIBUTORS – or something else if you have any idea what is more descriptive than Statistics. This leads to the current statistics page, with the current sections reordered in the following way (to promote data contributors – DLME partners):
                                                               i.      STATISTICS

                                                             ii.      DATA CONTRIBUTORS

                                                           iii.      ITEM CONTRIBUTORS

                                                           iv.      ITEMS

ABOUT – leads to the current About section
 

Once that goes live, we start monitoring at least the following:

The usage of the main page, including
the depth of scrolling;
the way people interact with groups of categories (Do they use arrows? Do they click on “View all”?);
what is more engaging – “Find items by” or the groups of categories?
The usage of the EXPLORE (browse) page, including:
How do they interact with “All” categories view?
How deep they scroll?
Do they often switch between groups of categories?
Which groups and categories are the most interesting?
 

That should give us nice insights on the next development steps."

**Comment by ggeisler** [comment]
@mwerla @jacobthill That all sounds great to me 👍. I like the idea of renaming the Statistics page to Contributors and the plan for gathering analytics.
