### ISSUE TITLE
Strange highlight effects in Arabic mobile view

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1185]
The blue box around the arrows has some strange effects in the Arabic mobile view:

![IMG_2059](https://user-images.githubusercontent.com/37662787/106615644-a6731300-653a-11eb-81b0-276a7834829d.PNG)
![IMG_2060](https://user-images.githubusercontent.com/37662787/106615658-a96e0380-653a-11eb-808a-5ebd4af6d9bc.PNG)

The English view is: 

![IMG_2061](https://user-images.githubusercontent.com/37662787/106615835-d7ebde80-653a-11eb-8378-b86bf0e22261.PNG)

**Comment by caaster** [comment]
@mejackreed I am still seeing a blue box as in the screen shot below. FWIW, I have an iPhone 11, running the most recent OS, 14.4.
![File_000](https://user-images.githubusercontent.com/3210225/106779099-822b3b00-65fb-11eb-9373-eef124858040.png)

**Comment by jacobthill** [comment]
@caaster the blue box is supposed to be there.
