### ISSUE TITLE
Per Page Drop Down Issue 

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#119]
In Chrome and Firefox (not in Safari), when you select a facet, the **Per Page** options are listed outside the dropdown (http://staging.dlme.clir.org/library/catalog?f%5Blanguage%5D%5B%5D=Arabic)

![language arabic digital library of the middle east dlme search results](https://user-images.githubusercontent.com/45000/29521400-6708f136-8653-11e7-80da-0ced7f59bb88.png)

**Comment by cbeer** [comment]
It looks like there's a javascript error on the page with the google analytics integration and whitelisting.

**Comment by cbeer** [comment]
Ah, I see -- you should be visiting https://staging.dlme.clir.org/library. We have some redirects, but they're obviously not working in all cases.
