### ISSUE TITLE
Update URL paths to reflect newly named main menu tabs

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1193]
The `Browse` tab has been renamed `Explore` and the `Statistics` tab is now named `Contributors`.  The urls still reflect the old names e.g. https://dlmenetwork.org/library/browse

**Comment by jcoyne** [comment]
The labels for the Explore page is set in the Admin interface: https://dlmenetwork.org/library/feature  The routes are from spotlight: https://github.com/projectblacklight/spotlight/blob/main/config/routes.rb#L103 So that's not something that can be changed.
