### ISSUE TITLE
When trying to submit feedback on an item (Arabic version), error message is displayed

### ISSUE THREAD

**Issue by caaster** [sul-dlss/dlme#1194]
I navigated to the Arabic version of the site and clicked on this item:

https://dev.dlmenetwork.org/ar/library/catalog/oai:N%2FA:Manchester~18~18~175~225632

I click on the feedback button, and the following error message displayed:

![Screen Shot 2021-02-02 at 11 22 22 AM](https://user-images.githubusercontent.com/3210225/106651632-4a63bb00-6549-11eb-9b00-c1e27da22466.png)

**Comment by jacobthill** [comment]
FYI the English version gets the same error

**Comment by jacobthill** [comment]
@mejackreed this is still not working. Does it need more time for the changes to take effect?

**Comment by mejackreed** [comment]
Should be good to go now

**Comment by caaster** [comment]
@mejackreed - I cleared my cache, and it is still not working for me.

**Comment by jacobthill** [comment]
Its not working for me either.

**Comment by cbeer** [comment]
It looks like the deploy hasn't gone out yet.
