### ISSUE TITLE
Gallery View Text Wrapping

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#120]
In the gallery layout of search results, anchor text overflows the gray boxed area. Maybe the overflow needs to be `hidden`?

![language arabic digital library of the middle east dlme search results 1](https://user-images.githubusercontent.com/45000/29521978-ba14e73e-8655-11e7-8873-763609cff876.png)

**Comment by cbeer** [comment]
We often have curators choose only a subset of fields for the gallery to make it more visual impactful (if there were thumbnails...)

**Comment by anarchivist** [comment]
requires @jacobthill to review and make a decision about how to handle

**Comment by jacobthill** [comment]
I think the gallery view should just show the title. That seems to be standard practice as far as I can tell and will fix this issue I believe.

**Comment by jcoyne** [comment]
Okay, it's currently configured to just show the title on the gallery page, so nothing left to do here.

**Comment by jcoyne** [comment]
Fields that display can be customized on this page: https://spotlight.dev.dlmenetwork.org/library/metadata_configuration/edit
