### ISSUE TITLE
Arabic record view link to provider site misaligned with image

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1200]
<img width="1196" alt="Screen Shot 2021-02-02 at 7 17 31 PM" src="https://user-images.githubusercontent.com/37662787/106679852-7869ef00-658b-11eb-9708-27c0b6ac6490.png">

**Comment by caaster** [comment]
@jacobthill could you include a link to this record in the exhibit, in this ticket? This will help me with QA, because otherwise I won't know how to locate it to make sure it appears fixed. Thanks.

**Comment by jacobthill** [comment]
https://dev.dlmenetwork.org/library/catalog/http:%2F%2Fwww.loc.gov%2Fitem%2F2017498733%2F

**Comment by caaster** [comment]
@jacobthill I see the same misalignment in English view for this item, fyi
