### ISSUE TITLE
Gallery view missized container

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1202]
<img width="1173" alt="Screen Shot 2021-02-02 at 7 26 07 PM" src="https://user-images.githubusercontent.com/37662787/106680505-c2070980-658c-11eb-8674-41567a43b066.png">

https://dev.dlmenetwork.org/ar/library/browse/group/manuscripts/qur-an-manuscripts

**Comment by jacobthill** [comment]
The same record has this problem: https://github.com/sul-dlss/dlme/issues/1203

**Comment by jacobthill** [comment]
I assume this issue and #1203 are caused by a problem with the iiif for this collection: https://dev.dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=Bodleian+Libraries&page=1&per_page=96. If we can confirm that the problem is on Bodleian end, we can document the problem in #1203 and close it. I think we still want to fix our containers so they all appear the same size.

**Comment by jacobthill** [comment]
More inconsistent container sizes that may be related: https://dev.dlmenetwork.org/ar/library/browse/group/photography/emile-bechard-s-oriental-studies-photographs

**Comment by jacobthill** [comment]
Another example from a different collection: 
<img width="1154" alt="Screen Shot 2021-02-02 at 7 55 31 PM" src="https://user-images.githubusercontent.com/37662787/106682507-b289bf80-6590-11eb-89f6-14d249271e68.png">
https://dev.dlmenetwork.org/ar/library/browse/group/serials/javanan-i-imruz

**Comment by mejackreed** [comment]
Seems to be an issue that many of the Bodleian IIIF services are having difficulty responding.

**Comment by jacobthill** [comment]
@mejackreed yep I noticed that many Bodleian record had that problem, but other collections do as well. There as some more examples linked above.

**Comment by mejackreed** [comment]
Ah got it thanks! I see now
