### ISSUE TITLE
Long tokens pushing gallery view container

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1206]
With excessively long tokens, the gallery view is pushed horizontally to contain the token.
https://dev.dlmenetwork.org/library/catalog?f%5Bagg_data_provider_en%5D%5B%5D=American+University+of+Beirut
<img width="1373" alt="Screen Shot 2021-02-02 at 8 03 01 PM" src="https://user-images.githubusercontent.com/37662787/106683003-abaf7c80-6591-11eb-80d8-b24adc94b983.png">

The presence of a thumbnail url in the description field is a mapping error but it exposes this issue. I'm not sure if we will have any other cases of this. I can't think of any examples of actual words that would be this long but if we put identifiers in this field, some could easily exceed the container width. Need a method of breaking excessively long tokens and continuing on the next line.

**Comment by ggeisler** [comment]
@jacobthill This should be an easy fix, but I don't have any records indexed locally that has this issue. Can you point me to an S3 URL I can use to index the records in your screenshot locally?
