### ISSUE TITLE
Update "Contact us" and "Feedback" flash message

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1208]
There are two different messages when each form is submitted, but there is no need for the language to be different. The "Contact us" form message is currently a bit informal, the "Feedback" message gives the impression that we have the power to act on the feedback given us. In some case we may, in others we won't. We don't want to give this impression.
The English message for both should be "Thank you, your feedback has been submitted." and the Arabic message for both should be (Make sure the period ends up at the end of the sentence on the far left): 

شكراً. لقد تم إرسال ملاحظاتك واقتراحاتك.

**Comment by jacobthill** [comment]
Just to be clear the message can be duplicated if need be. Not ideal from a programming standpoint but maybe we don't have time to refactor the code.

**Comment by jkeck** [comment]
Just to make sure I understand this correctly, both the Contact Us  and Record Feedback forms' flash messages (after successfully submitting) should be:

English: "Thanks. Your feedback has been sent."
Arabic: "شكراً. لقد تم إرسال ملاحظاتك واقتراحاتك."

**Comment by mejackreed** [comment]
@jkeck I read this that they both should be: 

Thank you, your feedback has been submitted.
شكراً. لقد تم إرسال ملاحظاتك واقتراحاتك.

**Comment by jkeck** [comment]
👍   Sorry, the confusion was about what the original text was in Spotlight vs. the updated text.  Got it cleared up now, thanks.
