### ISSUE TITLE
Question: Is there a way darken or provide hover darken for home page browse group thumbs

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/dlme#1210]
Reported by @mwerla asked if we could provide similar hover effects from Browse page to image thumbs on homepage

**Comment by mwerla** [comment]
The need for that change is related to the low readability of titles on the thumbs in case of light thumb background or background that has a lot of small elements (like a printed page or manuscript).

**Comment by ggeisler** [comment]
@mejackreed If we can borrow the same on-hover styling effects from the browse landing page, that would be the most straightforward solution.

The alternative is for me to do a bit of tweaking to the gradient applied to the tiles on the homepage, but it's hard to get a general solution that works well with a range of underlying images, so the on-hover styling seems like the best solution.
