### ISSUE TITLE
Long Title Display

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#123]
There are titles that are quite long (e.g. https://spotlight.dlme.clir.org/library/catalog/stanford_mq457xb3818) which appears to have a content viewer that is not displaying (in Chrome).

![a chart of the indian ocean 1803 raster image a chart of the indian ocean improved from the chart of m d apres de mannevillette with the addition of a part of the pacific ocean as well as of the original tracks of the principal disco](https://user-images.githubusercontent.com/45000/29522534-7ce51c10-8657-11e7-88b5-194a20a8c335.png)

**Comment by cbeer** [comment]
The content viewer is related to the javascript error from #119.

**Comment by jcoyne** [comment]
@waynegraham I'm not sure what the action here is. I agree some titles are long.  Can we close?

**Comment by anarchivist** [comment]
This looks like it's an issue of multiple titles being listed in order: https://spotlight.dlme.clir.org/library/catalog/stanford_mq457xb3818.json
