### ISSUE TITLE
Add efficient cache-control headers for static assets in deployment environments

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/dlme#1230]
A follow on to performance increases, providing cache-control headers for these static assets will be useful for client-side caching.

Two approaches that could be taken here:
 - Add a new nginx task in the Fargate container to handle this
 - Setup a Cloudfront distribution for these assets (and maybe other assets also? RIIIF images?)

**Comment by anarchivist** [comment]
#1237 was a potential fix?

**Comment by anarchivist** [comment]
No work needed at the moment; assets have ETags and are being cached. Could revisit the Cloudfront pieces in the future. RIIIF images could be revisited specifically but they now have ETags too.
