### ISSUE TITLE
What are the metrics that are currently used to trigger autoscaling? What should they be?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/dlme#1231]
A question raised after https://github.com/sul-dlss/terraform-aws/pull/747 as we are still seeing >30sec `TargetResponseTime` (avg) spikes.

And, are there are additional metrics that we need to better understand these response time spikes.

**Comment by anarchivist** [comment]
In order to do this we need better understanding of what to accomplish. We're no longer seeing the same average `TargetResponseTime` spikes.
