### ISSUE TITLE
Odd characters in non-western characters

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#124]
There are a lot of `?` in non-Western scripts (see https://spotlight.dlme.clir.org/library/catalog/penn_manuscript%2Frecords%2Fpenn%2Fschoenberg%2Fljs427). 

This appears to be an issue with the original metadata (e.g. http://openn.library.upenn.edu/Data/0001/ljs427/data/ljs427_TEI.xml).

Will need to follow up with Penn on their metadata, but looking at their output (http://dla.library.upenn.edu/dla/medren/detail.html?id=MEDREN_5864396), it looks like they are just using the first `msItem` in the `msContents` as the title even though the item is bound with multiple discrete volumes (with _verso_ and _recto_ pointers within the manuscript).

**Comment by anarchivist** [comment]
I think this probably requires a mapping change, too. Presumably we want the title information for the volume, rather than multiple instances of the title.
