### ISSUE TITLE
Curator changes in dev not transferring accross curator user accounts

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1240]
When curator changes are made in dev, when logged in, they don’t seem to stick after logging out. e.g. I add a new browse group or category, save the changes, and then log out, it doesn’t seem to work. After exporting changes from dev to stage, I can see the changes when I’m logged into stage but they disappear when I log out.

Dev logged in:
<img width="1193" alt="Screen Shot 2021-03-02 at 2 36 44 PM" src="https://user-images.githubusercontent.com/37662787/109704622-ceb75700-7b64-11eb-8ad0-d0dbe4da229d.png">

Dev logged out:
<img width="1169" alt="Screen Shot 2021-03-02 at 2 37 06 PM" src="https://user-images.githubusercontent.com/37662787/109704642-d414a180-7b64-11eb-8c19-1365307fdc11.png">

This is currently blocking data transformation work. 

May be related to https://github.com/sul-dlss/dlme/issues/1235

**Comment by jacobthill** [comment]
Update: this only seems to be a problem in the English view; the Arabic view is as expected.

**Comment by jacobthill** [comment]
This is still an issue. Curator changes while logged in do not stick when I log out.

**Comment by anarchivist** [comment]
@jacobthill Can you describe the issues in more detail again? Updated screenshots of what you're seeing logged in vs. logged out are useful.

**Comment by jacobthill** [comment]
@anarchivist it seems to be working now. Not sure what fixed it but I'm going to close this.
