### ISSUE TITLE
Multiple CLIR addresses in prod

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1245]
The CLIR address is being duplicated in the about page: https://dlmenetwork.org/library/about/about (on the left). I'm not positive, but I think this happens every time I do an import. It duplicates the address each time. It might be related to https://github.com/sul-dlss/dlme/issues/1240 and/or https://github.com/sul-dlss/dlme/issues/1235.

While this is being investigated can we update the CLIR address to:

Council on Library and Information Resources
211 North Union Street, Suite 100-PMB 1027,
Alexandria, VA 22314
dlme@clir.org

**Comment by ggeisler** [comment]
@jacobthill You can update the address yourself as an exhibit curator. On the Admin side, go to Curation > About and edit the one you want to update in the Contact section of that page. 

You could also delete (or uncheck to hide from public view) the duplicate versions. We probably want to do that now without waiting for someone to look into why the duplicates are occurring.

**Comment by jacobthill** [comment]
Thanks @ggeisler. I didn't notice that I could change the address. The duplicates have been removed and the address updated.

**Comment by cbeer** [comment]
Import/export is working fine and looks like it would deduplicate appropriately, except that -dev and -prod seem to have diverged (maybe multiple CLIR contacts were added in -dev at some point?).

Before the next import, I'd suggest removing the existing CLIR contact in -prod and that should fix it permanently.

**Comment by anarchivist** [comment]
@jacobthill Could you confirm testing what Chris proposed the next time you load data into prod? Thanks!

**Comment by jacobthill** [comment]
I tested this by deleting the CLIR address in prod, importing from dev and then importing again and it is not working still. The address is duplicated instead of being overwritten.

**Comment by corylown** [comment]
I think there is a bug here, but it's subtle. The export/import/overwrite works fine as long as the slug can be derived from the value of the name field -- for example if the name is `CLIR` and the slug is `clir`. However, the actual slug on dev is `clir-b4709b48-6562-4895-8534-e1aa7b931d81`. If I export that contact from dev and import it to prod the slug gets created in prod as just `clir` dropping the rest of the imported slug. So when I import to prod from the same file again the slugs do not match and a duplicate contact gets created. Modifying the slug on dev and prod to be `clir` should solve this problem. There also may be something in spotlight that needs fixing to use the slug from the imported file exactly as imported.
