### ISSUE TITLE
502 gateway error

### ISSUE THREAD

**Issue by kamchan** [sul-dlss/dlme#1248]
Jacob had reported seeing occasional 502 errors when navigating dlme sites.    Additional elb logging and pending cloudwatch alerts are showing some occassional connection issues between the elb and its spotlight fargate targets. It possibly maybe a keepAliveTimout issue.

On the elb side the set timeout is 300 seconds (defautl is 60) If the keepAliveTimeout on the container side (puma/nodejs?) is set  to something drastically different, 5xx and other connection errors may result?  

This person saw similar issues and it turns out to be a nodejs configuration with a newer version of nodejs on their target. https://medium.com/@pleasingsmoke/aws-elb-5xxs-revisit-your-server-keepalivetimeout-a0ea8e22c242

Can we make sure the containers' timeout are matching what is set on the ELB side?

**Comment by aaron-collier** [comment]
@jacobthill - I'm curious if we may be able to narrow down when this is happening.

Did you either load a large data set or trigger a full reindex and then start browsing the site? Or are the 502s happening when you know no other work is happening (i.e. indexing in particular).

**Comment by anarchivist** [comment]
Seems better after the caching tweaks, and we've quieted the irrelevant alarms by fixing #1268.
