### ISSUE TITLE
Add rtl support

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#125]
Add support for locale specific stylesheets. See https://github.com/waynegraham/dlme_search/commit/94b7646ddcacc051b9829d0cac919ddbe54f3a02#diff-9599427925097c3c66f26ac1e0de5cad

**Comment by cbeer** [comment]
I thought we explicitly put RTL support and i18n out of scope for this phase?

**Comment by waynegraham** [comment]
Yes (just wanted a ticket in here for next phase and I don't have access to the labels & etc.)

**Comment by cbeer** [comment]
We should talk about how to track things like this either on standup or at sprint planning. It's been our experience on other projects that preemptively creating tickets that won't be addressed in the near future usually results in a bunch of obsolete tickets that never get worked on.
