### ISSUE TITLE
Wrong records showing in browse categories in prod

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1251]
The browse categories (check the ones in the Art & Architecture group) have the wrong records (the number of records are way off in some cases e.g. https://dlmenetwork.org/library/browse/group/art-architecture/abidin-dino-archive). The numbers are correct in dev.

**Comment by anarchivist** [comment]
I haven't done an in-depth analysis, but it looks like one thing we're seeing is that saved searches are showing one count on the "cards" that display in the browse category pages, and a different one when looking at the browse category itself:

![Screen Shot 2021-04-15 at 8 12 01 AM](https://user-images.githubusercontent.com/73732/114893352-75c51a80-9dc2-11eb-8970-77bc24e3e44a.png)

![Screen Shot 2021-04-15 at 8 12 14 AM](https://user-images.githubusercontent.com/73732/114893382-7b226500-9dc2-11eb-9456-59215a3cb3ad.png)

I'll note that 141,285 is the current total number of records in prod.

**Comment by cbeer** [comment]
I'd guess this is related to https://github.com/sul-dlss/exhibits/issues/1103 and maybe a new problem related to import/export

**Comment by camillevilla** [comment]
@jacobthill Chris and I had a chance to investigate this. An incoming fix will be in upstream blacklight, so there will be some delay in getting this out to prod. We'll check in on progress next week.

**Comment by jacobthill** [comment]
thanks @camillevilla

**Comment by anarchivist** [comment]
Just a quick update (I shared this in Slack) - the fix in upstream Blacklight has been released, but there is still work to be done for the Spotlight fix and release management processes.

**Comment by cbeer** [comment]
Fixed with release v2.1.1 (+ spotlight 3.rc6)
