### ISSUE TITLE
Complete Google Tag Manager configuration tasks

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#1265]
Jacob and/or Marcin should:

* [x] Create a Tag Manager account for DLME Network
* [x] Provide Access to the same people at the same levels as the DLME Network Google Analytics Account
* [x] Create four different environments (one for dev, stage, QA, and prod) for the project see https://support.google.com/tagmanager/answer/6311518?hl=en

The development team will need access to TagManager to verify that our installation is being recorded appropriately. Because of some of the frameworks we are using a copy and paste of the Tag Manager snippets will likely yield incorrect metrics without additional developer intervention. We will also have deployment configurations that will need to be updated to provide different TagManager environment configurations.

**Comment by mjgiarlo** [comment]
@anarchivist @jacobthill I believe this has been completed and provided via email. Confirm/deny?

**Comment by anarchivist** [comment]
Yup, thanks!
