### ISSUE TITLE
Statistics dashboard displaying categories not in type facet

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1278]
The [statistics dashboard](https://dlmenetwork.org/library/statistics) has a 'manuscript/mixed material' category that is not displayed on the home page under the 'Type' >> 'Text' facet. The statistics should display the same content as this facet.

**Comment by anarchivist** [comment]
As reported in Slack, this looks like a data issue - see https://dlmenetwork.org/library/catalog?q=%22manuscript%2Fmixed+material%22&search_field=all_fields 

For example, https://dlmenetwork.org/library/catalog/http:%2F%2Fwww.loc.gov%2Fitem%2F00279388355-ms%2F has `cho_has_type.en: manuscript/mixed mixed material` and `cho_type_facet.en: Text:Manuscript`

**Comment by jacobthill** [comment]
@anarchivist I’m not clear how that is possible. I don’t map anything to the `cho_type_facet` field. That field is built from what I map to `cho_edm_type` and `cho_has_type`. If `manuscript/mixed mixed material` is in the `cho_has_type` field it should also be in the `cho_type_facet` field. Also how can you tell from the second url what value is in each field?

**Comment by anarchivist** [comment]
If you're logged in, you can see the Intermediate Representation and the Solr document on the item show page:

<img width="1132" alt="Screen Shot 2021-06-11 at 11 11 01 AM" src="https://user-images.githubusercontent.com/73732/121731462-d496cf80-caa5-11eb-957f-f8e3c248c860.png">

**Comment by jacobthill** [comment]
When I'm logged into the prod site, I can't see the Intermediate Representation and the Solr document. I do in stage and dev but not prod. Am I missing some permissions?

**Comment by anarchivist** [comment]
@jacobthill I've made you a site admin, which hopefully should give you the permissions you need.
