### ISSUE TITLE
Terraform: set up a UAT stack in same AWS account (as specified in DLME Stanford team meeting)

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#1280]
Jacob needs a UAT environment to load prod data and to test major functional changes. This was agreed to by Vivian, Mark, and Julian in a meeting in May 2021. 

Needs more guidance from Ops about what adding UAT means and where it should appear in the directory hierarchy. The different Terraform environments match to different AWS accounts. The engineering teams don't have the right knowledge or access to implement this currently. However, @mjgiarlo started a PR (sul-dlss/terraform-aws#823) to try to push this forward.

**Comment by mjgiarlo** [comment]
This will be taken on by ops this week.

**Comment by mjgiarlo** [comment]
> This will be taken on by ops this week. Unassigning myself and removing from triage board.

☝🏻 was my understanding as of June 15th after chatting with @anarchivist about a conversation they had with @julianmorley. AFAICT, nothing's happened since. The current understanding is that @aaron-collier will take a look at the existing (broken, rebase-needing) PR and we'll take it from there.
