### ISSUE TITLE
502 bad gateway error preventing loading records

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1287]
I have recently re-mapped all collections with changes to the type fields. I am trying to load the data into the production environment and running into a problem. I tried to load the whole Cambridge set (22k records) and kept getting a 502 bad gateway error. I split the set in two to make it smaller and am still consistently getting the same error. Here is a [link to the s3 url](https://s3-us-west-2.amazonaws.com/dlme-metadata-dev/output-3664f671-2508-4e24-a5d4-bc2abd65797d.ndjson) I am trying to load. Here is a [link to the prod page where the records get loaded](https://dlmenetwork.org/library/resources/new); just paste the url and click 'fetch'. I need to remove all records and re-load them before I start vacation at the end of this week. Its not practical to break all of our collections down further so we are loading smaller sets. We have seen the 502 error before but this is the first time I have seen it happen repeatedly when trying the same task.

FYI the records are all linked in dlme transform. The top url is the one I'm working on: https://dev.dlmenetwork.org/transform

**Comment by anarchivist** [comment]
FWIW, this 502 error doesn't seem to be reported/captured by Honeybadger.

**Comment by jacobthill** [comment]
I got an email but when I click the link it says it is not found. Is this related? It seems like it happened at the same time.
<img width="997" alt="Screen Shot 2021-06-23 at 1 01 41 PM" src="https://user-images.githubusercontent.com/37662787/123138564-2b47c600-d423-11eb-9982-98b28997905c.png">

**Comment by peetucket** [comment]
We've examined CloudWatch logs, and have seen the exception:

Summary:

- the data URL (https://s3-us-west-2.amazonaws.com/dlme-metadata-dev/output-3664f671-2508-4e24-a5d4-bc2abd65797d.ndjson) is fine and we can CURL that URL and see the JSON
- the JSON file is 187 MB
- the exception occurs here: https://github.com/sul-dlss/dlme/blob/master/app/controllers/s3_harvester_controller.rb#L37
- the 502 gateway error is not indicative of a problem with the URL, or load balancer, it is the web app failing and is apparently the error reported by the AWS container as a result
- the AWS container is running in 2 GB of memory total: https://github.com/sul-dlss/terraform-aws/blob/master/organizations/production/dlme/container_definitions/dlme_web_app.json#L6

Likely issue:
- the body of the data URL needs to be loaded into memory all at once as a ruby object, and this is causing the container to run out of memory

Possible solutions:
- split the file into smaller parts
- add more memory to the container via terraform-aws
- add validation before the file is loaded to see how big it might be before allowing it to load?

**Comment by ndushay** [comment]
From Jacob:

He needs to be able to load all the data in a short window of time -- if the value of a field changes across collections, then it's important that all collections are updated more or less at the same time.

He would like to be able to load all of the collections at once and/or the largest collections without splitting them.  Cambridge is currently the largest at 22K records, the next biggest is 17K records.   But we could get bigger collections in the future.

**Comment by ndushay** [comment]
Jacob also notes that he was able to load all the data in DEV last week without a problem, but it isn't working in prod ... maybe because the RAM is in use by actual users and there is competition for the RAM for loading data with the RAM used for the app ?

**Comment by peetucket** [comment]
What we did:
- doubled the memory allocated for the AWS DLME container from 2 GB to 4 GB in dev, stage and prod
- tested that the data loaded successfully in stage
- waiting for the new container to start in production

Next steps:
- when container is ready in prod, test the file again in production
- create any tickets needed for future work to deal with this issue (or investigate further) in next workcycle
- if file still fails to load, Jacob will split in smaller chunks and load

- Waiting for OPs to sort out the new container definition

**Comment by jacobthill** [comment]
After the memory changes took effect in prod, the data loaded without issue. I will load all of the data and record any further issues in this ticket, or close the ticket.

**Comment by jacobthill** [comment]
Additional issues during loading:
- loaded another set of 15k records with a 502 bad gateway error; happened once and then went through the next time I tried
