### ISSUE TITLE
Expose more fields as facets in the DLME web app

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1326]
As a DLME curator I would like to browse DLME records by additional fields, some which may be useful to end users and others that have curatorial value but users will not be interested in. 

Expose the following fields as facets in the [curator view](https://dev.dlmenetwork.org/library/search_configuration/edit):
- cho_coverage
- agg_data_provider_collection <strike>dlme_colection</strike>
- agg_data_provider_collection_id <strike>dlme_colection_id</strike>
- cho_subject
- agg_edm_rights
- agg_dc_rights
- wr_dc_rights
- wr_edm_rights

**Comment by jacobthill** [comment]
Add dlme_collection as facet

**Comment by corylown** [comment]
@jacobthill a few questions:

- These fields don't correspond 1:1 with the fields in Solr. In cases where there are separate fields for English and Arabic you would like both fields configured?
- In some cases there are other languages available. For instance, `cho_coverage` has a field containing Turkish. But I don't see that we're exposing any Turkish facet fields in the app. Should I just configure English and Arabic and ignore any other languages that are present?
- There are at least two different `wr_dc_rights` fields: `agg_is_shown_at.wr_dc_rights_ssim` and `agg_preview.wr_dc_rights_ssim` -- do we want one or the other or both added? _As a bit of an aside, the content of these fields does not look particularly appropriate for faceting, but maybe this is useful somehow to administrators? The field contains strings like: "To inquire about permissions or reproductions, contact the Rare Books and Special Collections Library, The American University in Cairo at +phone_number or contact@email.edu"_
- There are three fields for `wr_edm_rights`: `agg_is_shown_at.wr_edm_rights_ssim`, `agg_is_shown_by.wr_edm_rights_ssim`, `agg_preview.wr_edm_rights_ssim`. Again, I'm not sure whether we want all of these configured as facets or which one(s).

**Comment by jacobthill** [comment]
- When there are separate fields for English and Arabic, go ahead and configure both.
- The site is in Arabic and English. The metadata is in many languages, basically whatever the provider shares with us. We have a somewhat confusing process of mapping all of these languages to either English or Arabic depending on what is available in the record e.g. if the record has an English title, present that in the English view, otherwise display the next priority. So, yes you can ignore any other languages and they should be mapped to either English or Arabic.
- While not ideal, we don't have great tools for reviewing the mappings. The faceting is useful for metadata review. You can add both dc_rights fields.
- Go ahead and configure all edm_rights fields as well

Thanks

**Comment by jacobthill** [comment]
@corylown I have a few questions on this, and additional discoveries while reviewing.

I don't see the Arabic equivalents of these fields, (can we add them?):
- [ ] Collection
- [ ] Creator
- [ ] Contributor
- [ ] Medium
- [ ] Spatial
- [ ] Temporal

There were two `Date range` fields with the same number of records. One doesn't seem to do anything. I re-named it to `Date range (delete?)`. Can you explain why this is here and if it is needed?

There are three type fields in the dlme application profile: cho_edm_type, cho_type, and cho_has_type? The first two are added as facets in English. cho_type has English but no Arabic, and cho_has_type has neither. Can we add these?

**Comment by mwerla** [comment]
@jacobthill I don't know how to verify that issue completeness, I am not familiar with the curator view.

**Comment by jacobthill** [comment]
@mwerla I think it is complete but you can verify by looking at all of the displayed facets in the uat environment. All of the new ones displayed automatically. The names can cause confusion at times but I am confident that this is complete.
