### ISSUE TITLE
Rename data contributor and item contributor to less confusing names

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1345]
The terms ‘data contributor’ and ‘item contributor’ are unclear. Perhaps we can change this to “data provider” and “object steward”, “object holder” or “resource steward”. Also, credit for metadata creation/aggregation/enrichment should be clear as well as credit for those who hold the physical objects.

Facet names can be updated by curator but the same names will need to be implemented in the contributors page.

**Comment by ggeisler** [comment]
It's been a while so I might remember this incorrectly, but based on some notes in a Google doc think Marcin and I discussed this potential solution:

- Rename "Item contributor" to something more generic like “Holding institution”
- Rename "Data contributor" to "Data provider"

And then in the application UI:
- Remove "Data contributor/provider" from facet list
- Continue to display both fields on the item details page (using the new labels)
- Update the section headings on the Statistics page to use the new labels

**Comment by jacobthill** [comment]
I think that's right @ggeisler. I've made you're bullet points into check boxes and implemented the curator configurable changes.

**Comment by cbeer** [comment]
As long as I'm doing this right, it seems ripe for error that the IR field `agg_data_provider` maps to `Holding institution` and `agg_provider` maps to `Data provider`. If we're going with these new labels, can we consider renaming the fields in the IR too?

**Comment by jacobthill** [comment]
@anarchivist what do you think? I feel like I have these names sorted and won't mix them up. The code that maps them never changes. But, as other people start doing data mapping, the odds of making this mistake increase.

**Comment by anarchivist** [comment]
I don't have a strong opinion about what the fields are actually named in the IR, but I will note that the IR field names are intended to map to the EDM properties they're associated with.

**Comment by jacobthill** [comment]
@cbeer, @anarchivist, I think we decided that there is not need to update the field names in the application profile. They are consistent with EDM and I think we can avoid confusion on the data mapping side. I think we have the fields mapped correctly, though Europeana could have chose less confusing names. `edm:Provider` (our `agg_provider`) is "The name or identifier of the organization who delivers data directly to an aggregation service (e.g. Europeana)" while `edm:DataProvider` (our `agg_data_provider`) is "The name or identifier of the organization who contributes data indirectly to an aggregation service (e.g. Europeana)." So, I think we have everything correct and should be okay to call this done and consult the EDM definition every time we do work on the application.
