### ISSUE TITLE
Reorder About pages?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1365]
I recommend re-ordering the about pages so that the "About" about page is first in the list. It's currently not:

<img width="674" alt="Screen Shot 2021-12-07 at 3 21 52 PM" src="https://user-images.githubusercontent.com/101482/145115097-adba9862-17fe-4df9-8df8-6e37405ba22c.png">

As a result, a user selecting the "About" menu item from the main menu ends up on the Exhibits page, which is probably not as likely to be useful to most users as the main "About" page, at least as the first About page they see.

**Comment by mwerla** [comment]
Looks like this is fixed on production. @jacobthill Can you confirm? There was no comment made when you closed the task.

**Comment by jacobthill** [comment]
Yes, the pages were reordered and the section titles were all made sentence case.
