### ISSUE TITLE
Use consistent case for page and section headings

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1366]
We're currently using a mix of title-case and sentence-case for page and section headings. For example, most of the About page titles are in sentence-case, but one is not. And within a page, there are both forms used:

<img width="804" alt="Screen Shot 2021-12-07 at 3 25 49 PM" src="https://user-images.githubusercontent.com/101482/145115758-658c8b83-59e1-4a51-b692-34f9172403a2.png">

---

In addition to About pages, we also use headings for browse group titles, browse category titles, and the headings on the Statistics page. Most of those use title-case, although the few headings we inherit from Blacklight are in sentence-case (e.g., "Refine your results").

In my opinion, the most important thing is to make the About section headings internally consistent because the different usages are very clear when looking at pages and sidebar titles in that section. I would lean towards using sentence-case, although that might be at least partly because SUL style is to use sentence-case, so I'm used to that. This isn't a SUL-branded site, however, so I don't think we need to be guided by that. Either is fine as long as we make things consistent.

Secondarily, if we do settle on sentence-case for the About section, I'd suggest updating the browse group headings to be sentence-case, and the same with the Statistics page headings. 

That would leave only the browse category titles as headings in title-case, but they feel different enough in context that I think it's fine to leave them as title-case.

**Comment by mwerla** [comment]
To capture the decision made yesterday:
- Browse categories titles in "Title Cases"
- Everything else in "Sentence cases"

PS. I think "Data Providers" were written like that with the assumption that it's a term that we want to emphasize somehow, but I don't think that's really needed. So I assume that we use the same approach to "data providers" in any project documentation, info pages etc..
