### ISSUE TITLE
Link selected field values on Item Details page?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1368]
User research revealed that when looking at the item metadata on the Item Details page, more than a few users try clicking on names and subjects in field values; the expectation seems to be that they would be linked.

A potential improvement might be to link the values of selected fields (fields that are likely to have a decent number of records with the same value) so that selecting the field value link would take the user to a search results page for that value.

As an example, we did this in the Vatican project. The metadata from an [example item details page](https://spotlight.vatlib.it/latin-paleography/catalog/Pal_lat_177) includes linked values for several fields:

<img width="542" alt="Screen Shot 2021-12-13 at 5 08 17 PM" src="https://user-images.githubusercontent.com/101482/145909398-e1d55afe-e6ed-4aed-adf7-b983e21a6a15.png">

Selecting the Country value, for example, takes the user to [this results page](https://spotlight.vatlib.it/latin-paleography/catalog?f%5Bms_country_ssim%5D%5B%5D=%3CGermania%3E), where all listed records have that same value for the Country field.

To do (Ignore the discussion below unless you need context on these decisions):
- [x] hyperlink `cho_contributor`
- [x] hyperlink `cho_creator`
- [x] hyperlink `agg_data_provider`
- [x] hyperlink `agg_provider`
- [x] hyperlink `cho_subject`
- [x] hyperlink `cho_spatial`
- [x] hyperlink `cho_temporal`
- [x] hyperlink `cho_language`

**Comment by mwerla** [comment]
@jacobthill Can you propose here which fields will have the values linked? It's useful to do it, but not for all fields it makes sense. I guess we should focus on the ones that have a more "tag-like" nature and skip the ones which usually contain longer textual descriptions.

Two clarifications:
- If for a metadata field we have several different values, I assume each of them will be linked separately (e.g. language: English, Arabic).
- If a single value has several words, like "Biblioteca Apostolica Vaticana" in the example above, the search query will be linked with the entire phrase (as a search phrase with "" ) or it will be word by word? I assume that phrase based approach is better (higher relevance of results).

**Comment by jacobthill** [comment]
I think we can link 'cho_language', 'cho_subject', 'cho_spatial', 'cho_temporal'. If we want we can also link 'data_provider' and 'item_provider'. The links would be to the entire phrase. We will want to make sure the linked search results are exact matches, e.g. selections from the facet rather than query results.

**Comment by mwerla** [comment]
Great, thanks for the list, looks good, but maybe we should also add creator and contributor fields? I agree that providers fields should also be linked.

**Comment by mwerla** [comment]
I am not really sure what do you mean that the fields are not visible. At least for creator, it's visible (in production), for example: https://dlmenetwork.org/library/catalog/ResimKlksyn%2F983

**Comment by jacobthill** [comment]
Nevermind, I mixed up the tickets. I think the problem with linking contributor and creator is that most will link back to sparse search results but I don't really have a strong opinion about this. We can link those fields if you think it would be useful.

**Comment by mwerla** [comment]
I hope that at least across the data from one provider the linking will be somehow useful. It will be for sure less useful to discover items across providers.

**Comment by ggeisler** [comment]
I agree with @mwerla that linking to a provider could be useful. It should link to the same result set as selecting that provider from the facet sidebar would, I believe.

Linking to a creator might not produce substantial result sets very often, but I think that could have some value in itself; it helps inform the user that "these are the only items in DLME associated with the creator you are interested in." It's informative, even if the result set is very small.

@jacobthill I'll leave it up to you to decide if and how to ensure the decisions we made here are actionable for the team.
