### ISSUE TITLE
Fix click targets in search results slideshow modal

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1371]
[Edit: I now see I [filed a ticket in blacklight-gallery](https://github.com/projectblacklight/blacklight-gallery/issues/98) about this earlier this year]

In the search results slideshow modal, the previous and next button click targets appear offset. As shown below (and this seems consistent in Firefox, Chrome, and Safari), we have a large click target, which is good, but instead of starting at the top of the modal, it seems to start at the button itself, and then extends down the height of the modal (but because it is offset, that target extends below the modal):

<img width="1251" alt="Screen Shot 2021-12-13 at 5 32 34 PM" src="https://user-images.githubusercontent.com/101482/145912386-f6a8ae54-82ba-4257-bd95-51a59c9b802b.png">

The click target should be shifted up, so that it extend from the top of the modal (leaving room for the close button) to the bottom edge.

I saw several users get frustrated (or at least confused) by this when using the slideshow view.

Note that this would be work on the `blacklight-gallery` gem, so would benefit any project that uses [that gem](https://github.com/projectblacklight/blacklight-gallery), including Stanford Exhibits, where I also see the problem.

**Comment by thatbudakguy** [comment]
@ggeisler (or @jacobthill) this change is live now in production if you want to review.

**Comment by jacobthill** [comment]
Thanks @thatbudakguy. @ggeisler this looks good to me but I would prefer you to confirm this before calling it done.

**Comment by ggeisler** [comment]
@jacobthill Yep, this looks perfect. Thanks @thatbudakguy!

**Comment by mwerla** [comment]
@jacobthill Target clicks looks ok, but I noticed that the slideshow view allows you to go through the current page of search results only. So in the above example (https://dev.dlmenetwork.org/library/catalog?q=qatar&search_field=all_fields&view=slideshow) clicking on right arrow to see next item instead of item 13 will give you item 1:

![image](https://user-images.githubusercontent.com/562200/155266637-18079830-91df-48ab-9861-aa7661145e2c.png)

**Comment by jacobthill** [comment]
@ggeisler I think the issue @mwerla noted need to be broken out into a separate Spotlight ticket. Can you verify?

**Comment by thatbudakguy** [comment]
@jacobthill i think this problem is actually already tracked on the `blacklight-gallery` plugin: https://github.com/projectblacklight/blacklight-gallery/issues/4 ...albeit, the issue is 8 years old! more comments on that issue about expected behavior would be helpful, I think.

**Comment by ggeisler** [comment]
Yes, that Blacklight Gallery ticket @thatbudakguy found (thanks!) is still valid and fixing it should fix the problem @mwerla noted. 

Just to update things, I added a comment on the [Blacklight Gallery ticket](https://github.com/projectblacklight/blacklight-gallery/issues/4) with the behavior I'd expect.
