### ISSUE TITLE
Hide the "Sign in" link in the site brandbar

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1372]
This could be low priority but it also might be relatively easy and would improve the user experience on the (admittedly rare) occasions when a user selects the "Sign in" link the top-right of the site brandbar.

There are several improvements that could be made when selecting the "Sign in" link:

- User accounts are not applicable to regular DLME users, but we don't make that clear
- We don't display the site masthead on the Sign in / Sign up pages so those pages look sort of broken
- We use inconsistent terminology on these pages ("Sign in" and "Log in")

### Current "sign in" page ("sign up" is basically the same)
<img width="1153" alt="Screen Shot 2021-12-15 at 5 03 34 PM" src="https://user-images.githubusercontent.com/101482/146285493-9e95753a-bac5-4d76-84ba-833d55770182.png">

---

### Suggested updates
- **A:** Add the DLME masthead to the page
- **B:** Add a `<div class="alert alert-warning" role="alert">` box so the user understands this isn't something they should waste time trying. Suggested text is `The Digital Library of the Middle East website does not currently offer user accounts. This page is for website staff only.`
- **C:** Change the "Log in" heading to "Sign in" so it matches the link label

<img width="1098" alt="Screen Shot 2021-12-15 at 5 28 18 PM" src="https://user-images.githubusercontent.com/101482/146286027-b15f9a1d-5bec-40c1-ac4e-58e3df48bacd.png">

---

If we do the above, we should also update the "Sign up" page, since the changes could be pretty much identical (add masthead, add alert box with the same text):

<img width="1098" alt="Screen Shot 2021-12-15 at 5 33 08 PM" src="https://user-images.githubusercontent.com/101482/146286399-16d5e68a-8b80-455c-84c8-f767f1b68fba.png">

**Comment by mwerla** [comment]
@ggeisler I think that if the login/sign up option is not applicable to end users, we should remove that from the public UI. Those few who use that function can simply bookmark the link.

**Comment by ggeisler** [comment]
@mwerla Sure, hiding the Sign in link would be even better. I was concerned that the team would not like the idea of having to bookmark/keep track of the Sign in URL, but if we're okay with that, just hiding the link would be simpler than updating the sign in and sign up pages.

If we go this route, we should make sure to use a technique that hides the Sign link both visually **and** from screen readers, such as adding a `hidden` attribute to the Sign in element (or I think styling it with `display: none` would be functionally equivalent).

Also, if we go this route, I would still love to see the step of "Add the DLME masthead to the page" for the sign in/sign up pages, because those pages feel clunky to me without the masthead and the availability of the accompanying main menu items. But since only DLME team members would ever see those pages, I recognize this is likely a very low priority.
