### ISSUE TITLE
Link image and title in slideshow view

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1373]
When viewing user sessions where a user has chosen to use slideshow view, I saw several instances where the user  repeatedly clicked both the item image and title, seemingly frustrated not to be able to view more about that item. Ideally, the user should be able to go to the item details page directly from the slideshow view.

There might be a technical reason this isn't feasible (I have a vague feeling we considered doing this years ago on another project but didn't, but I can't remember why we didn't), but if it is feasible, it seems like the image and title should be linked to the take the user to the item details page, just as the image and title are linked in the the other search results views.

- **A:** Link the item image to the item details page
- **B:** Link the item title to the item details page. Add a `text-decoration: underline;` to the title so it is clear to the user that the title is a link.

(Note that for clarity I increased the font size of the title and counter in this screenshot so the current application look exactly like this.)

<img width="1135" alt="Screen Shot 2021-12-16 at 2 23 15 PM" src="https://user-images.githubusercontent.com/101482/146452091-2cf42d17-f883-414d-9f64-4ef2381e521f.png">

**Comment by mwerla** [comment]
@ggeisler Thanks for noticing that. I think it really should be implemented, otherwise the slideshow view is quite useless for many users.

**Comment by jacobthill** [comment]
Agreed
