### ISSUE TITLE
Cancel Hotjar subscription when Winter 2022 workcycle is over

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1381]
Hotjar was useful in pre-planning for the upcoming workcyle and could come in handy during the workcycle, but the "Business" level subscription isn't worth paying for when we aren't actively working on or doing user research for DLME.

We should cancel the "Business" level of the subscription at the conclusion of the Winter 2022 workcycle. We'll still have an active basic level subscription that we can upgrade again when needed.

**Comment by jacobthill** [comment]
Confirmed that we are on the basic plan and not being invoiced currently.
