### ISSUE TITLE
Can we eliminate the brand bar menu toggle?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1384]
Split out from #1375 to discuss this point from @mwerla in more detail:

> One more issue which I think still remains (potentially) confusing is the fact that we have a hamburger icon in the top right corner, and just below it, there is the main menu of the page, which (to me) looks like the expanded menu from the top right hamburger. I am afraid that users may not see the hamburger as yet one more menu to expand.

Here are a couple of quick ideas to get your thoughts on, @mwerla. These both assume we follow through with your suggestion in #1372 that we (perhaps) remove the sign in link from the brand bar. If we do that, we have one less utility link to support in the brand bar, which might open up some other options to enable us to not show the hamburger menu at all.

### Option 1: Hide the "Contact us" link at `md` breakpoint and narrower
If we're willing to not provide access to the "Contact us" link on smaller viewports, then we only have the locale menu to display. I believe there could be enough room to display the locale menu alongside the site title:

<img width="390" alt="Screen Shot 2022-01-10 at 5 42 22 PM" src="https://user-images.githubusercontent.com/101482/148862858-81152ff8-55ac-43af-ab1b-0d43e401b72f.png">

I don't like hiding the "Contact us" link, so don't think this is a great idea, but it would only be at the smallest breakpoints. As soon as we get to `md` (576px) there is sufficient room for the utility links without collapsing (even before we eliminate the Sign in link):

<img width="781" alt="Screen Shot 2022-01-10 at 6 04 45 PM" src="https://user-images.githubusercontent.com/101482/148863239-a7d45c5e-0d7c-46b8-9048-bc6772389693.png">

### Option 2: Abbreviate "Digital Library of the Middle East" to "DLME" at `md` breakpoint and narrower
Again, I'm not suggesting this is a great idea, but if we were to abbreviate the site title in the brand bar, we'd have sufficient room to display both the locale menu and the "Contact us" link (I don't show it here, but we probably even have space to add back in the DLME logo image we currently hide at the smallest breakpoint):

<img width="390" alt="Screen Shot 2022-01-10 at 5 52 00 PM" src="https://user-images.githubusercontent.com/101482/148863555-6613ba07-4b21-4181-955c-ca938a8b0128.png">

Obviously, not displaying the full title of the site isn't ideal, but FWIW, "Digital Library of the Middle East" is fully spelled out not far down the homepage.

**Comment by mwerla** [comment]
@ggeisler, I think that out of the two ideas, hiding the "Contact us" option is less harmful. Abbreviating the title may be justified on the main page, as we have the introductory text there, but if someone will land on one of the item pages, let's say from Google search results, the website name won't be so obvious any longer.

Now, regarding the hiding of the contact link, I think the potentially negative effect it could be minimized by adding that link on the about page, in the "Contacts" section on the left. I think it would be useful there for all resolutions, even if it will repeat the link from the brand bar in broader views (samples below). The button action could remain the same - displaying the contact form.

<img width="996" alt="image" src="https://user-images.githubusercontent.com/562200/148999231-61ce537a-6bc6-403e-a430-5e06f660b021.png">


<img width="425" alt="image" src="https://user-images.githubusercontent.com/562200/148999379-86cfd9e6-8c82-48a6-94e5-67998cfc6e33.png">

**Comment by ggeisler** [comment]
Closing this in favor of the more actionable #1388.
