### ISSUE TITLE
Highlight item providers on item details page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1386]
There's some background discussion about this in #1380, but that is probably not required reading to work on this ticket. As noted there, this design does assume that there is **not** a technical constraint that would prevent us from pulling two metadata fields and values from the list of returned item metadata and displaying them outside the `<dl class="document-metadata dl-invert row">` element the currently holds all metadata elements.

Our goal is to better highlight the item and data providers for a given item on its item detail page. The idea is to pull three pieces of metadata already on the item details page and co-locate those in a box that is positioned at the top of the list of metadata fields:

<img width="1039" alt="148857352-56b2697a-a600-4ca4-80a5-8788e63d3e24" src="https://user-images.githubusercontent.com/101482/149239215-6b0cdccc-b260-41af-8704-ce3f46972e84.png">

### Relevant metadata elements

Current item detail page:

<img width="854" alt="Screen Shot 2022-01-12 at 3 25 44 PM" src="https://user-images.githubusercontent.com/101482/149239309-ba7d6f12-e4cd-476f-b566-e734d17bb932.png">

- A: Item contributor (to become `Holding institution` with #1345)
- B: Data contributor (to become `Data provider` with #1345)
- C: Link to the data contributor website

### New contributor highlight box

<img width="569" alt="Screen Shot 2022-01-12 at 3 43 09 PM" src="https://user-images.githubusercontent.com/101482/149239513-87e0c415-cf97-4fbb-96ef-2ed0af7a2e7f.png">

Box styling:
- Box should extend as wide as possible to contain the text without line-wrapping (i.e., ideally, each of the three elements in the box display on a single line, though that won't always be possible). But the box shouldn't be fixed-width, because we don't want it to be wider than necessary (and we don't want to have to manually deal with all the different breakpoint width constraints).
- `background-color: #ffffff;`
- `border: 1px solid $color-gray-medium;`
- `border-left: 3px solid $color-black-light;`
- `box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);`

Box element styling (as a starting point; we can customize after seeing how this looks):
- The item contributor label becomes `This item resides at:`
- The data contributor label becomes `Item data provided by:`
- Those labels use the default body text styling (`20px, 400 weight, $gray-dark`)
- The values for those labels are links (to the facet value for the respective facet) and should be styled as links
- The "View on contributor website" link is styled as a button horizontally centered in the box. It's a `btn-primary` and I'd try using the `btn-sm` size to keep the box from being taller than necessary.
- The label on the button becomes `View on data provider website`.
- Although visually we want this to look like a button, I think semantically it should remain a link, since it is taking the user outside of the current site?

### Highlight box location
We have two types of item detail page, depending on whether the item is a IIIF item (and thus is displayed in the Mirador viewer) or not. In both cases, the idea is to display the highlight box just above the list of metadata elements. The difference is just that in the IIIF item case we have a wider column in which to display the box:

<img width="1159" alt="Screen Shot 2022-01-12 at 4 32 51 PM" src="https://user-images.githubusercontent.com/101482/149239782-467e7019-5e44-4cdd-8e1e-817e0b4c23c1.png">

I'd suggest horizontally centering the box in the column space available. I'm guessing that'll look the best with boxes of varying widths. 

### Responsive considerations
On narrower viewports, when one of the provider names is long, we'll probably have some line-wrapping. For clarity, I think we should try to wrap the provider name in its own container, rather than treating the whole line as a single container and wrapping from the left-edge. In other words, wrapping would look like this:

<img width="366" alt="Screen Shot 2022-01-12 at 4 33 25 PM" src="https://user-images.githubusercontent.com/101482/149239806-e61a8741-97f2-44db-8bc8-c9d082aac099.png">

This isn't great (and could increase the box height in certain cases) but hopefully this is a worst case (narrow phone width, long-ish provider title) and won't come up that often. We can look at the wrapping options more closely after it's implemented and adjust if it seems necessary.

**Comment by mwerla** [comment]
Thanks, @ggeisler, it looks very good to me.
