### ISSUE TITLE
Update the icon used for Slideshow results view

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#1394]
Related to but independent of #1370.

In #1370 @asmaaalkuwari suggested that the current icon used for selecting the slideshow view could be interpreted as "video" and we might improve the icon. I agree it is worth looking at more modern icons and see if we can find a better fit for this feature. 

(If we do this, I think it would be done in the blacklight-gallery gem, but at least for the time being it will be easier to keep track of this issue here.)

**Comment by ggeisler** [comment]
@asmaaalkuwari and anyone else who has thoughts, below are some mockups of alternative slideshow icons (last icon in the row). It's tricky because some icons look potentially good when you see them in the abstract, but don't work as well when they are at the required (small) size and adjacent to the other result view icons.

Let me know if any of these seem to anyone like a good replacement for our current slideshow icon. (I have opinions but I don't want to bias anything...)

<img width="610" alt="Screen Shot 2022-01-24 at 5 18 32 PM" src="https://user-images.githubusercontent.com/101482/150887147-91b24913-d54e-4ad2-9058-4d6ba017bcad.png">

**Comment by mwerla** [comment]
I vote for A :-)

**Comment by thatbudakguy** [comment]
likely depends on #1447 since the fix is deployed but icon isn't visible yet.

**Comment by cbeer** [comment]
It's visible in -dev and -uat now, so... good enough to close this I think.

**Comment by thatbudakguy** [comment]
@ggeisler @mwerla new icon is now visible at https://uat.dlmenetwork.org/library/catalog?exhibit_id=library&search_field=all_fields&q=

**Comment by mwerla** [comment]
@jacobthill I also see the new icon.
