### ISSUE TITLE
[dlme/dev] Webpacker::Manifest::MissingEntryError: Webpacker can't find mirador.js in /opt/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/dlme#1426]
## Backtrace

    line 4 of [PROJECT_ROOT]/app/views/catalog/_mirador_default.html.erb: _app_views_catalog__mirador_default_html_erb__4206085822008891068_390340
    line 2 of [PROJECT_ROOT]/app/views/catalog/_show_with_viewer.html.erb: _app_views_catalog__show_with_viewer_html_erb___2819388564063121526_390320

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53082/faults/83906558)

**Comment by cbeer** [comment]
All seems good now that we're deploying the code we think we should be
