### ISSUE TITLE
Flush the Rails cache for each new deploy

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/dlme#1447]
Ordinary `capistrano` deploys flush caches, which is super handy for seeing changes reflected immediately after a deploy, but our AWS environments cache data in a cache that persists across deploys. 

AWS might not cooperate with us, because both the new + current versions of the container co-exist at some point.

Do we need to:
- monitor the deploy and trigger flushing the cache after the deploy is fully rolled out?
- use unique cache keys for each deploy?
- ??

**Comment by corylown** [comment]
I'm curious whether we can use EventBridge to detect that a new deploy has happened and flush the cache when it is triggered: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-get-started.html

**Comment by corylown** [comment]
Closing because the plan is to move the DLME web application on premise.
