### ISSUE TITLE
Suggest placeholder thumbnails for images without existing thumbnails

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#145]

**Comment by ggeisler** [comment]
Here's a square version of the placeholder thumbnail I made for Spotlight a while back (so it would match the 4:3 version we already have for browse categories):

![default-square-thumbnail](https://user-images.githubusercontent.com/101482/29592647-40da86ca-875a-11e7-8bc3-941700b0a323.png)

### List view example
![list-view](https://user-images.githubusercontent.com/101482/29592657-515f4b16-875a-11e7-96d0-7bb2e9fb1d77.png)

### Gallery view example
![gallery-view](https://user-images.githubusercontent.com/101482/29592661-57d6d96e-875a-11e7-9234-04111b8c8308.png)

**Comment by cbeer** [comment]
👍 I don't think we added that upstream, but probably should, yeah?

**Comment by ggeisler** [comment]
Yep, I think it makes sense to.

**Comment by cbeer** [comment]
Sounds good. I'd like to talk to @jcoyne about approaches for doing this in blacklight. I started working on this in https://github.com/projectblacklight/blacklight/pull/1750, but it got weird pretty fast.

**Comment by jcoyne** [comment]
@cbeer I've done this in two ways:

1. Index the default value if there's no "good" value to index
2. Override thumbnail_tag e.g. https://github.com/samvera/curation_concerns/blob/d9f615cf2b8927bf908582ca444f04ede7516619/app/helpers/worthwhile/thumbnail_helper.rb
