### ISSUE TITLE
Display type data in facets

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#1451]
From #1326 

There are three type fields in the dlme application profile: cho_edm_type, cho_type, and cho_has_type? The first two are added as facets in English. cho_type has English but no Arabic, and cho_has_type has neither. Can we add these?

**Comment by cbeer** [comment]
I'm tossing designed needed on this one too. It might be the same as #1450 .


I may be confused with all the type fields we have circulating around now, but I'm not sure what our strategy for showing type fields is.

We're currently showing:

"Type (EDM)" cho_edm_type (
"Other type" cho_type
"Type" cho_type_facet.en_ssim

**Comment by jacobthill** [comment]
I'm closing this since I can see all of the type fields in the Arabic record view and the facets are present in both languages.
