### ISSUE TITLE
Add some post-docker-build tests to make sure the image is good (enough)

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#1453]
At least to catch some issues we've seen, including:

- [x] assets not being built (fully? at least the javascript side seems to silently error out)
~spin up the app and make sure some key pages load? Or run the integration test suite?~ see below

**Comment by thatbudakguy** [comment]
i think we could address both of these by adding a job to the `test` workflow in circleCI that runs `build-image` and then executes the integration tests against the container (maybe by starting a compose app and binding port 3000 to the CI runner).

hopefully we could run it in parallel with the unit tests and it doesn't add too much time to the build...

**Comment by thatbudakguy** [comment]
see https://github.com/waynegraham/dlme_tests

**Comment by thatbudakguy** [comment]
blocked by #1462

**Comment by corylown** [comment]
Closing because the plan is to move the DLME web application on premise.
