### ISSUE TITLE
Add additional fixture documents to the test suite

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#1462]
This should help us in development by making sure we have a consistent set of objects we're developing against. It might also set us up for better integration tests or search testing.

**Comment by thatbudakguy** [comment]
- [ ] add a rake task that can index fixtures from the local filesystem (or from a remote file?)
- [ ] add the current testing JSON fixture to the repo
- [ ] add documentation to the README about indexing fixtures
