### ISSUE TITLE
[dlme/prod] Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#1468]
## Backtrace

    line 15 of [PROJECT_ROOT]/app/views/spotlight/shared/_report_a_problem.html.erb: block in _app_views_spotlight_shared__report_a_problem_html_erb___1479674166789937411_57120
    line 6 of [PROJECT_ROOT]/app/views/spotlight/shared/_report_a_problem.html.erb: _app_views_spotlight_shared__report_a_problem_html_erb___1479674166789937411_57120
    line 3 of [PROJECT_ROOT]/app/views/shared/_masthead.html.erb: _app_views_shared__masthead_html_erb___2338909921141303938_57040

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53082/faults/80476533)

**Comment by jcoyne** [comment]
@cbeer is this resolved? Honeybadger no longer has a record of this.

**Comment by cbeer** [comment]
🤷‍♂️
