### ISSUE TITLE
Provide context for users on "sort by" functionality

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1470]
As a DLME user, I sometimes am confused by the sort behavior. Ideally the UI would provide enough context for me to interpret the sort results.

In DLME the sort by functionality relies on data quality/completeness. We are planning on adding sort by date to the existing 'relevance', 'title' and 'creator' options via https://github.com/sul-dlss/dlme/issues/1348. This sort behavior will likely be confusing to users. Is there a way to clarify in the UI:

- [ ] That some records may be missing values and these records will always be at the end
- [ ] That dates are the earliest_dates provided by the data provider
- [ ] Ideally we can fix the way titles sort when numbers are part of the title https://github.com/sul-dlss/dlme/issues/1192 but this is related so linking it here

<img width="1235" alt="Screen Shot 2022-02-16 at 2 11 55 PM" src="https://user-images.githubusercontent.com/37662787/154338421-a5541585-98ee-486e-8f41-8daf7b2b07ed.png">

**Comment by jacobthill** [comment]
Thanks @ggeisler. This all makes sense to me and I think the two alert possibility is acceptable as well. @mwerla, @waynegraham does this seem reasonable to you?

**Comment by corylown** [comment]
@jacobthill you may be able to QA this if you configure the date sort options to appear via the curator/admin UI. The date sorting ought to work in a basic sense (and the alert box should appear when date sort is selected), but we have not yet addressed the solr config changes needed to keep the records with missing values at the end of the result set (#1476 captures this work).
