### ISSUE TITLE
Find out what monitoring + alerting is in place for the production stack

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#1473]
Document (on the wiki? in the README?) what monitoring and alerting is in place for the application, and perhaps even who receives and acts on certain type of alerts, including:

## Stanford nagios

One check for labeled `library-lb |  dlmenetwork:nagios-prod check-webapp`, at SLA medium. This checks the webapp's `/status/all` endpoint, which checks:

- the ruby server
- the database connection
- the solr connection

## AWS CloudWatch Alerts

With actions:

|  Alarm | Type | To |
| --- | ----------- | --- | 
| spotlight-production-elb-target-5xx-count | Notification | dlme-alerts |
| spotlight-production-cpu-high |  Auto Scaling | - |
| spotlight-production-elb-connection-error |  Notification  | dlme-alerts | 
| spotlight-production-elb-response-slow |  Notification  | dlme-alerts |
| dlme-production-SolrExceptions |  Notification  | dlme-alerts |
| spotlight-production-elb-502-count |  Notification  | dlme-alerts |
| spotlight-production-elb-health-hosts | Notification  | dlme-alerts |
| spotlight-production-cpu-high-alert | Notification  | dlme-alerts |

dlme-alerts sends email to dlss-dev-alerts (ops) + sul-aws-dlme-monitor (JH + MM).

Without alerting (but on the DLME CloudWatch dashboard):

- dlme-ec2-i-005f1f12891ec7c06-cpu (bastion? solr?)
- dlme-ec2-i-0f0ae68c198e62e1b-cpu (bastion? solr?)
- dlme-elasticache-dlme-cpu-*
- dlme-logs-dlme-webapp-events ("IncomingLogEvents < 10 for 1 datapoints within 1 hour")
- dlme-rds-dlme-*
- dlme-s3-dlme-uploads-prod-4xx-errors
- dlme-s3-dlme-uploads-prod-5xx-errors
- spotlight-production-elb-target-4xx-count

Not present ("only be created if the cloudwatch agent is installed"):

- dlme-ec2-i-*-disk-free
- dlme-ec2-i-*-memory-free 

## Other
- Wayne's [dlme_tests](http://github.com/waynegraham/dlme_tests) runs every Tuesday against production. Unclear who gets reports and acts on them

## Questions 
- [ ] is dlss-dev-alerts the right list for DLME production alerts?
- [ ] is [CloudWatch Agent installed ](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-on-EC2-Instance.html) on the solr EC2 instance
- [ ] do the disk free / memory free alerts actually work? presumably they should be hooked up to dlme-alerts for production solr.

**Comment by corylown** [comment]
Closing because the plan is to move the DLME web application on premise.
