### ISSUE TITLE
Add sortMissingLast=true attribute to int type field definition in Solr

### ISSUE THREAD

**Issue by corylown** [sul-dlss/dlme#1476]
Modify the Solr schema to set the `sortMissingLast=true` attribute on the field types used to store dates for sorting (fields specified in the related tasks). Apply this schema change to dev Solr instance. (Need to determine how to do this.)

Partially addresses #1348

**Comment by cbeer** [comment]
I think the "how" these days is:
1) commit the change to this repo, 
2) ECS Exec into the running image, 
3) use curl or something to upload the schema to solr (add this as a rake task?) using the solr APIs (kinda like https://github.com/sul-dlss/dlme/blob/main/.circleci/config.yml#L100?)
4) use the solr collection API to reload the collection
5) ...
6) 🎉

**Comment by cbeer** [comment]
We've updated dev, stage and uat.

**Comment by cbeer** [comment]
Moving -prod deploy to a new ticket/note
