### ISSUE TITLE
Add single valued date fields to Solr to enable date sort functionality

### ISSUE THREAD

**Issue by corylown** [sul-dlss/dlme#1477]
- [x] Populate a new field in the Solr index that is single-valued, type `TrieIntField`, with dynamic field suffix of `_isi` and contains the minimum value from `cho_date_range_norm_isim`. Suggested field name: `cho_date_norm_min_isi`
- [x] Populate a new field in the Solr index that is single-valued, type `TrieIntField`, with dynamic field suffix of `_isi` and contains the maximum value from `cho_date_range_norm_isim`. Suggested field name: `cho_date_norm_max_isi`

Partially addresses #1348

**Comment by jacobthill** [comment]
@corylown I don't know how to QA this. I don't see the solr filed but maybe we need to reindex first. I'm moving this to done since QNL will not be able to verify its working either. I think we should be able to tell that its implemented once the functionality is in place.

**Comment by corylown** [comment]
@jacobthill yes, I think the issue that will require QA is #1348  once all the related tasks are completed.
