### ISSUE TITLE
Add to list of fields that display Arabic values in Arabic view, etc.

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1488]
Some fields like language, type, etc. display Arabic values only in the Arabic view and English values only in the English view. Other fields display all values in both views; this is necessary given that the metatdata hasn't been fully normalized and translated. Now that `agg_data_provider_collection` is expected to be fully normalized and translated, it should function like type, and language display only English values in the English view and only Arabic values in the Arabic view.

**Comment by jacobthill** [comment]
@cbeer these changes removed the field from the list of facets https://dev.dlmenetwork.org/library/search_configuration/edit

**Comment by corylown** [comment]
@jacobthill should be fixed now.

**Comment by jacobthill** [comment]
@mwerla to test this we are confirming that the `Collection` facet is displaying only English values in the English view and only Arabic values in the Arabic view.
