### ISSUE TITLE
Don't allow double line titles in breadcrumbs

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/dlme#1497]
## What's wrong ?

Title metadata with more than 1 item is displayed in a way that looks wrong, with stacked titles:
![Screen Shot 2022-02-16 at 10 51 24](https://user-images.githubusercontent.com/1328900/155436998-dfcae992-226b-40b6-ad7b-d621127ddac4.png)

![Screen Shot 2022-02-16 at 10 51 40](https://user-images.githubusercontent.com/1328900/155436928-4e8f79f7-9882-4564-8b8e-4b8206b271e1.png)

**Comment by jacobthill** [comment]
@mwerla you can verify with this record: https://dev.dlmenetwork.org/library/catalog/harvard_scw-4086
