### ISSUE TITLE
Solr AND possibly not working

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1501]
Its not clear to me whether 'AND' is working as expected for Solr queries. [This query](https://dev.dlmenetwork.org/library/catalog?exhibit_id=library&search_field=title&q=Koran+AND+Qur%27an) does not return what I would expect since none of the records have 'Koran' and 'Qur'an' in the title. There are probably better ways to test this. The Boolean AND may be conflicting with other fuzzy matching rules. Can we confirm if this is working or not and, if not, create a new ticket (or edit this ticket) based on what @corylown and @marlo-longley learned from the work in https://github.com/sul-dlss/dlme/issues/1352?

**Comment by jacobthill** [comment]
[This query] seems to confirm that it is working as expected and the unexpected behavior above is caused by some other rules. I expect it will go away when https://github.com/sul-dlss/dlme/issues/1401 is implemented.

**Comment by corylown** [comment]
@jacobthill as you suggest, I suspect that stemming behavior and/or the apostrophe in `Qur'an` may be confounding factors. But my own testing indicates the AND operator is functioning.

**Comment by cbeer** [comment]
Spot-checking the results from https://dev.dlmenetwork.org/library/catalog?exhibit_id=library&search_field=title&q=Koran+AND+Qur%27an, all of them seem to have an alternative title of "Koran".
