### ISSUE TITLE
Add a docker invoke script to trigger data delete

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#1569]
See: https://github.com/sul-dlss/dlme/blob/main/docker/invoke_fetch_s3.sh

There is a requirement that data be cleared per collection prior to reindexing after an updated harvest. By exposing these feature through a docker invocation, this will allow the task to be run as a single ECS task triggered through dlme-airflow.

**Comment by jcoyne** [comment]
@aaron-collier can this be closed?
