### ISSUE TITLE
Export bulk tags automatically

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1580]
The most recent Infrastructure work cycle (September 2022) focused on completely automating the ETL pipeline for most data providers. One lingering issue preventing full automation relates to the way bulk tags work in Spotlight and our existing curator workflow. Bulk tags are manually assigned to records by DLME curators in the dev instance of the web app. These tags persist when metadata is refreshed. But the only way to export them is by manually clicking the `Download CSV file` button. The Infrastructure team needs a method of triggering this export via Airflow.
<img width="1140" alt="Screen Shot 2022-09-28 at 3 30 36 PM" src="https://user-images.githubusercontent.com/37662787/192872031-96208bab-41e8-4d12-8c8b-25848a4f85a6.png">

**Comment by jcoyne** [comment]
I believe this is part of Spotlight (https://github.com/projectblacklight/spotlight/blob/b06511be2b93a1dd999aada2405ab8609592804f/app/views/spotlight/bulk_updates/_download.html.erb) so should this move to that repository?

**Comment by jacobthill** [comment]
I don't think we need this anymore.
