### ISSUE TITLE
Make it possible for curator to add tabs in the browse category view

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1587]
<img width="1165" alt="Screen Shot 2022-10-19 at 3 06 12 PM" src="https://user-images.githubusercontent.com/37662787/196781798-ab5c6889-4017-4f8d-a127-f9cdfa5da8a4.png">

There is a use case for adding tabs in some browse categories, particularly for things like building lesson plans. This is implemented in DPLA primary source sets (and Library of Congress). See the example below with 'Source Set', 'Additional Resources', and 'Teaching Guide' tabs. Ideally the curator could add these tabs as needed to organize the content.

<img width="1086" alt="Screen Shot 2022-10-19 at 3 08 18 PM" src="https://user-images.githubusercontent.com/37662787/196782086-ced4e4cb-085e-4d15-b652-80246c94fa5c.png">

**Comment by jcoyne** [comment]
This will probably have to happen in spotlight.

**Comment by ggeisler** [comment]
@jacobthill This sounds like it could be more than just enabling optional tabs for a browse category. For example, is the content of each tabbed page just a subset of that browse category's items -- meaning the view for each tab is the same as it is now (one of the search result views)? Or do you envision content different from a search result view in one or more tabs?

The Gold Rush example, for instance, displays completely different content/layout in both the Additional Resources and Teaching Guide tabs.

If and when you have it, sharing a concrete example from DLME (browse category, how many tabs you'd want, and what the content of each tab would be) would be helpful before we consider this further.

**Comment by jacobthill** [comment]
@ggeisler my thought was that only the existing mandatory tab contains the category's items. The other tabs could be added by a curator and any contents would need to be manually added. I was thinking these would contain mostly text but I guess there could be possibilities for using a bulk tag to include other items. This is not necessary for my use case though. For DLME, we would use this to create a simple lesson plan and a list of articles or other additional resources, all of which would be text manually added by the curator.

**Comment by jacobthill** [comment]
Exactly like DPLA https://dp.la/primary-source-sets/california-gold-rush/teaching-guide#tabs

**Comment by ggeisler** [comment]
@jacobthill Okay, thanks. So this really is a much bigger issue than enabling the curator to add tabs to a browse category.

We'd have to provide a way for the curator to populate the pages of those additional tabs. That has a lot of implications, the most obvious of which are:

- Do we enable the editable page functionality (with the widgets the curator uses to create page content) for those tabs?
- If so, how do we update/extend the admin side of the application to enable not only adding browse page tabs, but to create and edit the pages for each tab?
- And, is the existing page widget selection sufficient for creating the sort of the page content you have in mind, such as the teaching guide example you pointed to (e.g., the main content can more or less be done with the text widget, but the sidebar part is not currently possible at all)?

I'm trying to keep an open mind until we refine the idea here, but do want to make clear that it might seem to be a simpler idea than it actually is. Adding tabs is probably the simplest part but to make the whole thing work I think this would be a major new feature, requiring significant design and development.

**Comment by jacobthill** [comment]
Yeah we figured it was too big for this work cycle and would need some design work. It can wait until the next Spotlight work cycle.

**Comment by caaster** [comment]
Hi @jacobthill let's discuss the priority of this ticket sometime, please.

**Comment by jacobthill** [comment]
Sure @caaster, its a high priority for DLME but lower than the bootstrap upgrade. I haven't looked through the rest of the Spotlight tickets. I probably not the best person to decide on the priority, but it seems like this would be a useful feature for many Spotlight users, basically anyone who wanted to make a teaching guide, guided learning activity, list of external resources, etc. for a browse category

**Comment by thatbudakguy** [comment]
Moved to spotlight: https://github.com/projectblacklight/spotlight/issues/2868
