### ISSUE TITLE
Upgrade Sidekiq and Redis gems

### ISSUE THREAD

**Issue by corylown** [sul-dlss/dlme#1596]
**Related to (should happen in tandem) #1588** 

We should ensure we use Redis version 7 as part of the migration to move DLME on premise from AWS.

Ops has made [Redis version 7 available](https://github.com/sul-dlss/operations-tasks/issues/3210 ) and we should test and then update the version of Redis for this application.

- [x] Test and upgrade to Redis version 7 for this application
- [x] Update Sidekiq/Sidekiq Pro gem to version >= 7
- [x] Update Redis gem to version >=5

**Comment by corylown** [comment]
re-opened by #1641 
blocked by #1639

**Comment by thatbudakguy** [comment]
AWS autodeploy is off; this is ready to go
