### ISSUE TITLE
Unzip files before storing them

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#162]
https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/penn-egyptian-csv-latest.zip
https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/penn-near-eastern-csv-latest.zip

**Comment by cbeer** [comment]
Can we just add them unzipped to the repository and save ourselves the work?

**Comment by jcoyne** [comment]
That would be best. @waynegraham what do you think?

**Comment by waynegraham** [comment]
They are now unzipped:

- https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/met_museum_records.csv
- https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/near_eastern-20170820.csv

**Comment by cbeer** [comment]
Thanks.
