### ISSUE TITLE
Move DLME Google Analytics to GA4

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1671]
Google Analytics is set up for DLME https://analytics.google.com/analytics/web/#/report-home/a136246606w196538874p282019859 but needs to be moved to GA4.

**Comment by thatbudakguy** [comment]
We currently have two DLME properties in GA, but one has no data. Some investigation needed to figure out why, and probably delete the unused one.

**Comment by thatbudakguy** [comment]
blocked on https://github.com/projectblacklight/spotlight/issues/2908 so we can inherit spotlight's behavior.

**Comment by thatbudakguy** [comment]
now blocked on spotlight release.
