### ISSUE TITLE
 When Arabic is selected the html tag should have the lang="ar" attribute

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#1713]
Currently it has `lang="en"`.  I'm not certain what the impact of this is, but it's not correct.

Consider initial page loads as well as navigation via turbo.  This change may need to be made in https://github.com/projectblacklight/blacklight-locale_picker/

**Comment by thatbudakguy** [comment]
See https://webaim.org/techniques/language/#lang for an overview of why `lang` matters to screen readers (including an audio example of what happens when `lang` doesn't match the actual content language). I think `lang` can also impact SEO in the target language.

**Comment by hudajkhan** [comment]
I'm beginning to look at this and #1712 to see if I can make sense of it.
