### ISSUE TITLE
Encoded record IDs causing broken links

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/dlme#1721]
via @aaron-collier:

I'm curious about this on stage and wonder if it's something y'all are aware of:
1 - <https://dlme-stage.stanford.edu/library/catalog/81055%2Fvdc_100023526782.0x000001_dlme> Notice the `%2F` encoding of a slash in the id. This is what is linked on the search results page. If I click it from search results, I stay on search results, but if I copy paste it I get a "Not found" error.
2 - <https://dlme-stage.stanford.edu/library/catalog/81055/vdc_100023526782.0x000001_dlme> - Is the same record where I've manually removed the encoding for a `/` and it displays fine.

Checking the record in the IR we don't encode that value, so it's either getting encode for display or in the SOLR maybe... either way, it's causing an issue viewing data for QNL at least.

Is this something y'all may be working on or an issue in BL, etc?

[Slack Message](https://stanfordlib.slack.com/archives/C5V53K69G/p1677863925129869?thread_ts=1677863925.129869&cid=C5V53K69G)

**Comment by corylown** [comment]
It's not encoded in Solr: `"id":"81055/vdc_100023526782.0x000001_dlme",`

**Comment by jcoyne** [comment]
This could be an Apache config issue. `AllowEncodedSlashes NoDecode`

**Comment by jcoyne** [comment]
A fix? https://github.com/sul-dlss/puppet/pull/9221

**Comment by thatbudakguy** [comment]
Apache config change doesn't appear to have resolved it. @jacobthill will confirm with QNL that it's OK to rewrite the identifiers to remove the slash, so we can treat this as a data problem.

**Comment by thatbudakguy** [comment]
Since the data problem is larger than we thought, shifting back to considering this something we need to solve at the webserver level. It did work in AWS environments, so hopefully we can find a webserver config matching the one we used to use.

**Comment by jcoyne** [comment]
This works fine in AWS: https://dlmenetwork.org/library/catalog/81055%2Fvdc_100023526782.0x000001_dlme

**Comment by jcoyne** [comment]
Trying it the other way https://github.com/sul-dlss/puppet/pull/9239
