### ISSUE TITLE
Potential configurable UI updates

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#173]
Below are UI elements we can easily update using the built-in admin features we get from Spotlight. These are things that jump out at me as ways to improve the visual design of the site, but I'm not knowledgeable enough about the vision for the site to be sure we should make the changes. So I'm just listing them here for consideration:

- [ ] Would it make sense to add an About page, maybe a couple of browse categories, maybe a feature page, even if they’re mostly blank, just to have the additional main menu items and make more clear that the site could be more than a home page with search results?

- [ ] Better labels for facets?

- [ ] Are all the search result views useful? If there will be minimal thumbnail images, it might be better to just enable list view and gallery view, to show there are view options, but not have the mostly useless (when there are few thumbnails) masonry and slideshow views?

- [x] Are all the topbar menu items useful (Bookmarks, Saved Searches, History) for the anticipated site?

**Comment by anarchivist** [comment]
Thanks @ggeisler - Let's talk through these with @waynegraham on standup today.

**Comment by anarchivist** [comment]
From 8/24 standup: @waynegraham and @ggeisler will work together so Wayne can get up to speed on the Spotlight admin.

**Comment by jcoyne** [comment]
I removed the top-bar partials in #196
