### ISSUE TITLE
Prevent wrapping on 'Holding institution:' 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1740]
Can we make it so 'Holding institution:' is on one line? 

<img width="742" alt="Screen Shot 2023-03-08 at 11 34 16 AM" src="https://user-images.githubusercontent.com/37662787/223773492-c15f5918-ed81-4493-b077-2ad2463954e8.png">

**Comment by jacobthill** [comment]
But I think it does it on most (maybe all) records. https://dlme-stage.stanford.edu/library/catalog/01965107v1

**Comment by jcoyne** [comment]
I believe this was supposed to be done  by https://github.com/sul-dlss/dlme/blob/main/app/components/owner_layout_component.rb#L5, but it still seems to render a 3/9 split
