### ISSUE TITLE
Fix edit button spacing on record view 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1751]
https://dlme-stage.stanford.edu/library/catalog/81055%2Fvdc_100000000193.0x0000bd_dlme

<img width="1221" alt="Screen Shot 2023-03-10 at 10 28 24 AM" src="https://user-images.githubusercontent.com/37662787/224356540-5882e63f-a30f-4cb7-aa01-79a6b4fc211e.png">

**Comment by jcoyne** [comment]
@jacobthill Can you explain how it should be fixed.   What is wrong with this?

**Comment by corylown** [comment]
The edit button is inline with the item title in the AWS prod instance. I think it should look like: 
<img width="1199" alt="Screenshot 2023-03-10 at 5 17 34 PM" src="https://user-images.githubusercontent.com/458247/224438850-c6f16bdb-0462-4ca0-a680-7fdd71f4adfb.png">

**Comment by jacobthill** [comment]
@corylown @jcoyne not that edit button, the one in the picture I attached at the bottom of the page

**Comment by corylown** [comment]
There isn't an edit button near the intermediate representation box on AWS version of the site.
<img width="1232" alt="Screenshot 2023-03-10 at 5 38 04 PM" src="https://user-images.githubusercontent.com/458247/224441405-e0db18f5-e1f2-4630-9b11-738885238a81.png">

The Edit button inline with the title in AWS links to the same route as the Edit button that's displaying oddly on the new on prem site. If we want parity with the AWS site then the button should display inline with the title.

**Comment by jacobthill** [comment]
@corylown There is in the picture I attached. You are looking at a different record. Try the one I linked above.

**Comment by jacobthill** [comment]
FYI this is the same record that we had id problems with and that I can't delete the tag from.

**Comment by corylown** [comment]
@jacobthill I think we're miscommunicating. Let's check in on Monday on Zoom or Slack.

**Comment by jacobthill** [comment]
Sorry I read all of the comments more closely. I don't think we need to check in, I understand what you are suggesting and agree.

**Comment by jcoyne** [comment]
https://github.com/projectblacklight/spotlight/pull/2969 is the solution for Blacklight 8. I'm not sure yet why it's broken in 7

**Comment by thatbudakguy** [comment]
confirmed resolved via #1760
