### ISSUE TITLE
Browse categories not updating 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1753]
I’m getting some unexpected behavior using exhibit tags to make browse categories and want to check to see if this is a bug or if its how browse categories are supposed to work. 

- I tagged 55 items with the “qalaat-seman” tag
- then built a browse category from all records with the “qalaat-seman” tag
- then I tagged more records with the “qalaat-seman” tag

I was expecting the browse category to include these new records but it doesn’t. I then manually selected the linked tag from one of the records which led back to a search result of all records with that tag. I tried to "update the existing category" from those results but the category was not updated.

**Comment by jcoyne** [comment]
Moved to spotlight.
