### ISSUE TITLE
Check that all data has been loaded in prod

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1754]
- [x] American Numismatic Society | United States of America | 7,884 | 1 |  
- [ ] American University in Cairo | Egypt | 7,861 | 32 |  
- [ ] American University of Beirut | Lebanon | 21,134 | 12 |  
- [x] Archives ouvertes de l’Institut français du Proche-Orient | Lebanon | 13,869 | 1 |  
- [x] Bibliothèque nationale de France | France | 626 | 2 |  
- [x] Bodleian Libraries | United Kingdom | 1,058 | 5 |  
- [x] Brooklyn Museum | United States of Americam | 8,388 | 2 |  
- [x] Cambridge University Library | United Kingdom | 22,303 | 3 |  
- [x] Consejo Superior de Investigaciones Científicas (CSIC) | Spain | 160 | 1 |  
- [x] Harvard University Library | United States of America | 14,947 | 2 |  
- [x] Lebanese American University | Lebanon | 113 | 2 |  
- [x] Library of Congress | United States of America | 5,232 | 6 |  
- [x] Metropolitan Museum of Art | United States of America | 6,175 | 1 |  
- [x] Palestine Poster Project Archive | United States of America | 12,920 | 1 |  
- [x] Penn Museum | United States of America | 15,981 | 3 |  
- [x] Princeton University Library | United States of America | 3,940 | 2 |  
- [ ] Qatar National Library | Qatar | 22,500 | 1 |  
- [x] Sakip Sabanci Museum | Turkey | 3,515 | 4 |  
- [x] Shahre Farang | United States of America | 414 | 1 |  
- [x] Stanford Libraries | United States of America | 103 | 1 |  
- [x] Texas Tech University Libraries | United States of America | 2,214 | 1 |  
- [ ] The American Institute for Maghrib Studies | Algeria, Morocco, Tunisia | 154 | 1 |  
- [x] The Walters Art Museum | United States of America | 2,872 | 8 |  
- [x] University of Lausanne | Switzerland | 3,938 | 1 |  
- [x] University of Manchester Library | United Kingdom | 2,986 | 1 |  
- [x] University of Michigan | United States of America | 1,040 | 1 |  
- [x] University of Pennsylvania Libraries | United States of America | 1,062 | 9 |  
- [x] Yale Peabody Museum of Natural History | United States of America | 8,820 | 1

**Comment by jcoyne** [comment]
@jacobthill aren't most of these already loaded? https://dlme-prod.stanford.edu/library/statistics  What is the delta?

**Comment by jacobthill** [comment]
@jcoyne Yeah most of them are, but its easy to miss something. I just want to go through and manually check them all.

**Comment by jacobthill** [comment]
I updated the name and assigned this to myself.

**Comment by thatbudakguy** [comment]
we can try manually loading AIMS, AUC, and AUB while we wait for the new data environment to be created.

**Comment by corylown** [comment]
@jacobthill we loaded AIMS, AUC, and AUB over the weekend. The counts look right to me, except there are 144 records in the AIMS file you sent to me but 154 is the count listed in the description on this ticket. Please check that this looks right and if so I think we can close this ticket.

- [AUC](https://dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=American+University+in+Cairo)
- [AUB](https://dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=American+University+of+Beirut)
- [AIMS](https://dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=The+American+Institute+for+Maghrib+Studies)
