### ISSUE TITLE
Set up production review environment

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/dlme#1761]
See discussion on #1758 

- [x] https://github.com/sul-dlss/operations-tasks/issues/3320
- [ ] add newly created VMs to cap environment file for prod
- [x] create a new solr collection for prod-review

this should make it so that `cap prod deploy` does all of the production VMs (including review) and continuous deployment "just works".

**Comment by thatbudakguy** [comment]
Question: should this environment be behind VPN?

**Comment by corylown** [comment]
The app should be publicly accessible.
