### ISSUE TITLE
Met object Solr doc ids are missing an institutional prefix

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#177]
E.g. https://spotlight.dlme.clir.org/library/catalog/322711 - should be something like `met_322711`

**Comment by jcoyne** [comment]
This means we probably need to delete all the met objects from the dlme_jsons table and clear solr.

```ruby
DlmeJson.delete_all
solr = CatalogController.new.repository.connection
solr.delete_by_query('*:*')
solr.commit
```

**Comment by anarchivist** [comment]
Fixed by reingest/reindex.
