### ISSUE TITLE
Stanford frecords: `agg_data_provider` has both "Stanford University Library" and "Stanford Libraries"

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#178]
![screen shot 2017-08-24 at 3 16 17 pm](https://user-images.githubusercontent.com/73732/29691225-31a724de-88df-11e7-87f3-f2655cc305bb.png)

**Comment by cbeer** [comment]
I suspect those 53 are ones Wayne removed?

**Comment by jcoyne** [comment]
These no longer show up after reindexing everything.
