### ISSUE TITLE
Penn TEI: duplicate records

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#179]
I'm seeing multiple versions of the same record(s), e.g.

* https://spotlight.dlme.clir.org/library/catalog/penn_manuscript%2Frecords%2Fpenn%2Fschoenberg%2Fljs403
* https://spotlight.dlme.clir.org/library/catalog/penn_ljs403

![screen shot 2017-08-24 at 3 18 51 pm](https://user-images.githubusercontent.com/73732/29691352-8d6b5dee-88df-11e7-8f64-cbca2fc54569.png)

**Comment by jcoyne** [comment]
I think this is part of #180.  We changed how we make identifiers after importing some things.

**Comment by jcoyne** [comment]
Fixed by deleting everything and reharvesting.
