### ISSUE TITLE
Develop mapping for Harvard FGDC

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#18]

**Comment by cmh2166** [comment]
first pass of a mapping for FGDC is done in the human readable docs. Being added / implemented now via the fgdc-mappings branch.

**Comment by cmh2166** [comment]
this will also probably be enhanced by a look through by:

1. someone who knows fgdc better than myself (kim?);
2. someone who knows Harvard's specific setup relating fgdc records to hosted digital assets to any IIIF or related services (to create the kind of local methods we did for stanford geo-mods).

**Comment by anarchivist** [comment]
Is this at a state where it's ready for a PR or to be handed off to someone else?

**Comment by aaron-collier** [comment]
Picking this up for implementation

**Comment by cmh2166** [comment]
@aaron-collier there is a branch that has the majority of the work already done.
