### ISSUE TITLE
TEI mapping and QA issues

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#181]
- [x] There should not be a root level `wr_id` set
- [x] `cho_spatial` should not map from `/*/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:msDesc/tei:history/tei:origin/tei:p`
- [x] `agg_edm_rights` for all current data from the Schoenberg mss should be `http://creativecommons.org/publicdomain/mark/1.0/`
- [x] `agg_is_shown_by.wr_id` should be `/*/tei:facsimile/tei:surface[1]/tei:graphic[3]/@url`
- [x] `agg_preview.wr_id` should be `/*/tei:facsimile/tei:surface[1]/tei:graphic[2]/@url`

**Comment by jcoyne** [comment]
@anarchivist for the last two items did you mean from within the `@url` attribute?
Here's what I have in our fixture:
```xml
  <facsimile>
    <surface n="Front cover">
      <graphic height="4591px" url="master/0085_0000.tif" width="3393px"/>
      <graphic height="190px" url="thumb/0085_0000_thumb.jpg" width="140px"/>
      <graphic height="1800px" url="web/0085_0000_web.jpg" width="1330px"/>
    </surface>
    <surface n="Inside front cover">
      <graphic height="4591px" url="master/0085_0001.tif" width="3393px"/>
      <graphic height="190px" url="thumb/0085_0001_thumb.jpg" width="140px"/>
      <graphic height="1800px" url="web/0085_0001_web.jpg" width="1330px"/>
    </surface>
    <surface n="Flyleaf 1 recto">
      <graphic height="4591px" url="master/0085_0002.tif" width="3393px"/>
      <graphic height="190px" url="thumb/0085_0002_thumb.jpg" width="140px"/>
      <graphic height="1800px" url="web/0085_0002_web.jpg" width="1330px"/>
    </surface>
    ...
  </facsimile>
```
Is it a problem that these aren't full URLs?

**Comment by anarchivist** [comment]
@jcoyne Yes, we should be pulling from the `@url` attribute on `<graphic/>`.

For the Schoenberg manuscripts, we should be building out a URL like the following:

```
"http://openn.library.upenn.edu/Data/0001/" + base name of source file + "/data/" + @url value

e.g. http://openn.library.upenn.edu/Data/0001/ljs189/data/thumb/0189_0000_thumb.jpg
