### ISSUE TITLE
Develop mapping for Stanford MODS

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#19]

**Comment by cmh2166** [comment]
first pass is on the mappings branch. hoping to do a second pass / clearly identifier minimum mapping today. https://github.com/sul-dlss/dlme/blob/mappings/docs/mappings.md

**Comment by cmh2166** [comment]
expand mapping to handle MODS oddities - i.e., no identifier field in other MODS records.

**Comment by cmh2166** [comment]
Mapping is up, PR is ready with mapping in place (#65 ). Some issues with 65, all stylistic, opening new issue to fix.

**Comment by cmh2166** [comment]
considering this closed by #55
