### ISSUE TITLE
Update mappings documentation in the codebase

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/dlme#216]
- [x] Remove mappings.md doc from `/docs`
- [x] Add link to open Google Spreadsheets mappings to the MAP documentation
- [x] Add some info on fields (definitions, examples) to MAP documentation
- [ ] (stretch) add basic / generic mappings for folks to build off of (MARC, MODS, DPLA, TEI)

**Comment by jcoyne** [comment]
@cmh2166 I think you did some of this already, can any of these be crossed out?

**Comment by cmh2166** [comment]
@jcoyne  yeah, i think everything except adding basic / generic mappings is there. closing now.
