### ISSUE TITLE
Measurement Thickness misspelled in Penn Museum data headers

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#219]
The current field is labeled as `measurement_tickness`. Is this from the source or should it be updated on our end to `measurement_thickness`?

https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/egyptian-20170820.csv

https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/near_eastern-20170820.csv

**Comment by anarchivist** [comment]
This is in the source data.
