### ISSUE TITLE
Evaluate tools for "local" CSV mapping

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#22]
E.g. for the Met Museum CSV. The reason why we're doing this not through the existing Spotlight CSV tools is because we want to evaluate the viability of the application profile rather than writing the columnar data directly to Spotlight's Solr index.

**Comment by cmh2166** [comment]
I think we can still use Traject, we'll just need to write a CsvReader class. @cbeer is building that already here: https://github.com/sul-dlss/dlme/tree/csv and the mapping is queued up at #20 (next in line).

**Comment by cbeer** [comment]
Agreed; Traject seems like it'll work well-enough.
