### ISSUE TITLE
How do we destructure complex fields?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#23]
```
agg_is_shown_at
agg_is_shown_by
agg_preview
```

**Comment by cbeer** [comment]
For `0..1` fields are destructured into e.g. `agg.is_shown_at.wr_id` (using `.` as a field separator) 

For `0..n` fields, the complex field is serialized to json, stored as a string, and deserialized within the application.

We'll have to revisit this if there emerge any querying needs on the `0..n` serialized fields.
