### ISSUE TITLE
Translate "eng" to "English" for display in language facet

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#235]
Currently highest count language facet. The rest are spelled out, but English is just `eng`

**Comment by aaron-collier** [comment]
Is it possible to have multiple values in the translation map? We already have:

`english: en`

But the data source is clearly often `eng`

**Comment by cmh2166** [comment]
this is related to fuzzy matching work additions to translationMaps.

**Comment by anarchivist** [comment]
Do we know where we're getting the values for `eng`?

**Comment by aaron-collier** [comment]
I believe it's coming from marc. I've gone through most of the other files and will run through marc this morning.

**Comment by cmh2166** [comment]
Is this fixed?

**Comment by cmh2166** [comment]
Is it fixed.
