### ISSUE TITLE
Consolidate Type and Other Type facets?

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#237]
Should we consolidate these fields? There is certainly duplicate data and some data that would need to be normalized.

<img width="226" alt="screen shot 2017-08-30 at 10 45 46 am" src="https://user-images.githubusercontent.com/2294288/29887062-0fd4f20a-8d71-11e7-9a2a-9a320a4bfbd5.png">

**Comment by anarchivist** [comment]
We should not consolidate them, but probably look at the mappings. We can also suppress and relabel the "other type" facet.
