### ISSUE TITLE
Fix blank creator

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#240]
Should we have a fixed text (i.e. `Unknown`) when creator is blank?

It's currently the highest creator facet and can't even be clicked on.

**Comment by jcoyne** [comment]
We should probably remove blanks.

```
  "cho_creator": [
    ""
  ],
```
This is occuring on the Met CSV pipeline for objects such as https://spotlight.dlme.clir.org/library/catalog/met_321592.ir

**Comment by cbeer** [comment]
I'm on it.

**Comment by anarchivist** [comment]
Did we fix this?

**Comment by cbeer** [comment]
We did.
