### ISSUE TITLE
Generate some docs on macros logics

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss/dlme#246]
Might be a good place to include information on things like TranslationMaps ; Thumbnails look-ups ; etc.

**Comment by cmh2166** [comment]
On backlog. Just linked to Traject's docs on macros generically, instead of writing up specific information on our macros / what we added, which still would be good.

**Comment by jcoyne** [comment]
provide more information on what our macros do.
CSV, IIIF, FGCD.
Create a manifest of macros and descriptions of what they do.
Guidance for someone who is writing transforms. When something should be a macro? (e.g. if you're doing the same thing over and over, writing a test for complicated logic)
