### ISSUE TITLE
Doc idea / high level view of how to add data from other sources than GitHub

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss/dlme#249]
- Add comments for setting up something other than GitHub pulls

**Comment by jcoyne** [comment]
Create an `OtherServiceImporter` class similar to https://github.com/sul-dlss/dlme/blob/master/lib/github_importer.rb

For each harvest it should create one `HarvestedResource` https://github.com/sul-dlss/dlme/blob/master/lib/github_importer.rb#L34 and calculate the [Multihash](https://multiformats.io/multihash/) of the content.  Next the script should persist the content as a `ResourceContent` object if we don't already have a copy.  This can be accomplished by doing:

```ruby
ResourceContent.persist(multihash) do
   retrieve_content_from_external_source
end
```

**Comment by jcoyne** [comment]
@jacobthill I talked with Mark about this today and we agreed that we'd close this, but you may want to write up some documentation about how you are doing harvesting now. You can put that in the https://github.com/sul-dlss/dlme-harvest repo.
