### ISSUE TITLE
Met data: `cho_edm_type` should be `Image`, not `3D`

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#264]

**Comment by cmh2166** [comment]
brought up (but not repaired?) in #92

**Comment by cmh2166** [comment]
Ah, this didn't get updated: https://github.com/sul-dlss/dlme/blob/master/lib/traject/macros/met_csv.rb#L58

**Comment by aaron-collier** [comment]
I can fix this in the met macro quickly.

**Comment by aaron-collier** [comment]
Fixed in #271
