### ISSUE TITLE
Penn Museum objects - bad value for `agg_is_shown_by.wr_id`

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#287]
Penn Museum objects have `agg_is_shown_by.wr_id` values like `https://www.penn.museum/collections/object_images.php?irn={491861}`. This should be a "web view" of an object like a higher resolution image, a PDF, etc.

**Comment by aaron-collier** [comment]
It looks as though the correct URL is without the braces, so `https://www.penn.museum/collections/object_images.php?irn=491861`, but some (like for this item) are missing images at this link. Do we (or can/should we) try to do some validation on that?

**Comment by anarchivist** [comment]
This is still not a valid value for `agg_is_shown_by`; it's expected to be a link to an asset itself, not a link to a web page with images.

**Comment by aaron-collier** [comment]
Ah yeah... Looking at the pages, the ID doesn't match the asset number, so I don't think we can format this. Probably something to pass up to the provider to include in the data or if there is a API or we can query...

**Comment by waynegraham** [comment]
I believe I've fixed this in the #302 (which I fixed upstream in the dataset for now).
