### ISSUE TITLE
JavaScript TypeError in Content Page

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#307]
When trying to update the text blocks on the landing page (to add in saved searches) I am getting a JavaScript error:

```
Uncaught TypeError: $.ajax(...) success is not a function
```

Not sure (yet) if jQuery just isn't getting loaded properly yet, but this does prevent the different content blocks from getting loaded on a page in the `edit` view. 

This may be an upstream issue with Spotlight...

**Comment by jcoyne** [comment]
After the dependency updates this no longer seems to be a problem (at least not one I can reproduce)
