### ISSUE TITLE
Auto certificate renewal failed

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#315]
>  You have an AWS Certificate Manager (ACM) provided SSL/TLS certificate in your AWS account that expires on Sep 04, 2018 at 12:00:00 UTC. That certificate has the following domains:
spotlight.dlme.clir.org, staging.dlme.clir.org
>
> Therefore, ACM has initiated the process to renew this certificate. During the process we identified that we are currently unable to issue a certificate containing the following domains:
staging.dlme.clir.org, spotlight.dlme.clir.org
>
> The domains are protected with one or more Certification Authority Authentication (CAA) records. Those records prevent the Amazon certificate authority from issuing a certificate. Please read our troubleshooting guide for CAA and make the necessary changes to your CAA DNS records: http://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html.
>
> We will continue to retry renewal of your certificate until we have successfully done so, or until the certificate expires. If the certificate is not renewed and the current certificate expires, your website might become unreachable.

**Comment by waynegraham** [comment]
I've updated the CAA records to include the following for AWS records:

```
clir.org.  CAA 0 issue "letsencrypt.org"
clir.org.  CAA 0 issue "amazon.com"
clir.org.  CAA 0 issue "amazontrust.com"
clir.org.  CAA 0 issue "awstrust.com"
clir.org.  CAA 0 issue "amazonaws.com"
```

Could we retry the renewal?

**Comment by anarchivist** [comment]
It looks like the existing certificate still requires email verification - https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-validate-email.html

We can create a new one that uses DNS validation instead, if you prefer.
