### ISSUE TITLE
Add monitoring to comply with SLA

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#318]
Per the [draft SLA](https://docs.google.com/document/d/1s5U4f41QWFPvDktqiRBoPBzVaidzYLNsY1By38vTzm4/edit), the DLME webapp should have a [*low* SLA](https://consul.stanford.edu/display/DLSC/Digital+Library+Services+Catalog) for now. 

* [x] Determine who should get alerts

**Comment by kamchan** [comment]
need to monitor staging/production aws envs

**Comment by kamchan** [comment]
dlme healthchecks alarms will now send emails to 

1) dlss-aws-dlme-monitor@lists.stanford.edu  (product owners so far: matienzo@stanford.edu and jacob.hill@stanford.edu) 
2) dlss-dev-alerts@lists.stanford.edu (ops team)

Need to get consensus from ops group and project as to support/response of those healthchecks.

**Comment by anarchivist** [comment]
Thanks @kamchan - is this something you think we need a meeting to discuss, or can it be hashed out asynchronously?

Also, would it be possible to add me as an admin of the first list?

**Comment by kamchan** [comment]
I've added both Mark and Jacob as owner.  We can probably hash this out async and meet only if need be.

**Comment by anarchivist** [comment]
* @kamchan will close once devopsdocs are updated
* @anarchivist to add @waynegraham to notifications

**Comment by kamchan** [comment]
devopsdocs has been updated.
