### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#325]
* [x] Determine whether we should use a CLIR or DLSS GA account
* [x] Add tracking/Tag Manager code

**Comment by anarchivist** [comment]
blocked until we figure out which GA property to use

**Comment by jacobthill** [comment]
@waynegraham @anarchivist how should we proceed with this? What is it blocker by? Do we just need to find the time to think about it and discuss it or is there another hold up?

**Comment by anarchivist** [comment]
I think it's just blocked by making a decision about where the Google Analytics accounts lies (e.g. at CLIR or Stanford).

**Comment by waynegraham** [comment]
I've created a new GA account for DLME network. Will work with @jacobthill to get a list of folks who need access.

**Comment by waynegraham** [comment]
Here are the tracking beacon codes for the properties that have been created:

UA-136246606-3 => production (spotlight.dlmenetwork.org)
UA-136246606-2 => staging (spotlight.stage.dlmenetwork.org)

**Comment by anarchivist** [comment]
blocked by #501

**Comment by anarchivist** [comment]
If we go into the exhibit dashboard (in both stage and prod), I see the following:

> In order to view exhibit analytics, the site administrator must configure an analytics provider.

**Comment by jcoyne** [comment]
We need to set these in the ENV variable: `SETTINGS__ANALYTICS__WEB_PROPERTY_ID`

**Comment by aaron-collier** [comment]
@waynegraham we need OATH also setup for this in order to integrate with spotlight. See:

https://github.com/tpitale/legato/wiki/OAuth2-and-Google#registering-for-api-access

**Comment by anarchivist** [comment]
See #522 for admin UI access issues with the the Analytics dashboard.
