### ISSUE TITLE
Set up a static outbound IP so QNL can whitelist us; notify them of new IP

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#327]
Qatar National Library has an OAI-PMH endpoint that is restricted to only whitelisted hosts. We need to be able to provide them with an IP address or range they can whitelist so we can harvest their metadata.

**Comment by anarchivist** [comment]
@kamchan will provide IP of on prem VM

**Comment by kamchan** [comment]
The static IP for the dlme-harvest machine is 171.67.21.138
