### ISSUE TITLE
Separate data pipeline from DLME Spotlight app

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#329]
Per conversations with @cmharlow the maintenance work cycle should include work to separate the data pipeline from the Spotlight app, to make it easier for @jacobthill to write/test Traject mappings and deploy them to a staging environment (#319). The work includes:

* Getting the Traject setup in a separate job-queue-based system
* Deployment options for sending to dev(?), stage, and prod environments
* Ensuring that the loader part of Traject points to designated ingest endpoints for Spotlight (previously discussed in an Architecture crew meeting)
* Allow pipeline to pull configurations from some designated place (Github repo?) that @jacobthill can access/commit to
* Does this allow us to make the DLME Spotlight app more "vanilla," allowing us to make it easier to maintain/update to more recent Spotlight versions?

(Presumably this will create new additional tickets that are in scope for this work cycle.)

**Comment by jcoyne** [comment]
We want to make something like a CI server.  When it gets a request, if it's not already processing something, update the repository and runs the mappings/data in one directory.  Ship the produced IRs to Spotlight.

**Comment by anarchivist** [comment]
Mural board from 11 January call ([link](https://app.mural.co/t/dlssarchitecture0560/m/dlssarchitecture0560/1547232844006/4ebb3ec86018ce2027ab10d41d6ac7512a6f56a4)):

![screen shot 2019-01-11 at 12 02 37 pm](https://user-images.githubusercontent.com/73732/51056878-ddafa980-1598-11e9-9eb6-c135bb6faac6.png)
