### ISSUE TITLE
Upgrade riiif to 2.0

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#333]
DEPRECATION WARNING: Initializing a file resolver without setting the base path is deprecated and will be removed in Riiif 2.0. (called from new at /Users/cmharlow/go/src/github.com/sul-dlss/dlme/config/initializers/riiif.rb:10)

**Comment by jcoyne** [comment]
Unable to complete this because spotlight depends on RIIIF 1.0 (see https://rubygems.org/gems/blacklight-spotlight/versions/2.3.2)
