### ISSUE TITLE
Allow URIs as resource ids

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#336]
All of the BnF data uses urls for resource ids; I believe we need a Macro to hash these

**Comment by anarchivist** [comment]
Acceptance criteria:

* Given that I have a URI for an identifier from a harvested and transformed record, I should be able to view the record in Spotlight

**Comment by jcoyne** [comment]
Tracking https://github.com/projectblacklight/spotlight/issues/2140

**Comment by aaron-collier** [comment]
Having deployed @jcoyne's branch, the BnF data seems work fine but not the Sakip Sabanci data: https://spotlight.stage.dlmenetwork.org/library/catalog/http:%2F%2Fdigital.sabanciuniv.edu%2Fabidindino%2Fmektup%2F3040200001541.pdf

**Comment by jcoyne** [comment]
@aaron-collier that request would be asking the rails server for a PDF representation for that resource.  That's a case that I hadn't anticipated..

**Comment by jacobthill** [comment]
@jcoyne @aaron-collier https://github.com/sul-dlss/dlme-transform/issues/111 with solve this issue.

**Comment by jcoyne** [comment]
@jacobthill That issue isn't listed as part of the current project. Should it be?

**Comment by jacobthill** [comment]
Yes, I just added it.

**Comment by jcoyne** [comment]
Fixed by #473
