### ISSUE TITLE
Need to develop a process for moving from staging to production

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#337]

**Comment by anarchivist** [comment]
Once there's data in the staging environment and providers have approved it, figure out what the process of moving that into production looks like.

* We're assuming we can invoke transformations in staging, and then reuse transformed resources from S3 produced in staging
* [ ] Decide on how to manage potential risk of rerunning transforms in production and loading unapproved data
* [ ] Confirm whether S3 permissions are public
* [ ] Confirm that we don't need to run transforms in prod

**Comment by anarchivist** [comment]
@jcoyne:
> We can run any transforms we want in stage; generates data and puts it in S3; index in stage; if it looks good, we can take the same URL and load it into prod.

@justinlittman:
> Why are transforms running in AWS? We have potentially built something more complex than it needs to be.

@anarchivist:
> Concerns of scale and longer term viability.
