### ISSUE TITLE
Traject config references local files

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#366]
https://github.com/sul-dlss/dlme/blob/master/lib/traject/bnf_salt_config.rb#L1-L5

This will cause the server to break.

**Comment by peetucket** [comment]
Looks like those files are in the repo, may be able to just make the paths relative?  I can give it a whirl and @jacobthill can test to be sure it works?

**Comment by jcoyne** [comment]
These have been fixed.
