### ISSUE TITLE
Load old database snapshot into dev environment

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#374]
Depends on #373

**Comment by kamchan** [comment]
created a copy of the latest (2/8) current dlme rdb snapshot and shared it out to our development 

arn:aws:rds:us-west-2:472468238516:snapshot:dlme-rds-snapshot-copy-2-8-19

and is ready to test restore  on the future dlme  db.

**Comment by anarchivist** [comment]
completed
