### ISSUE TITLE
Move Traject mappings, configurations, and macros to a new repository

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#377]
Per #329, and sul-dlss/dlme-transform#2, we need to move the Traject mappings and configurations to a new repository.

* [x] Determine which repository (confirm it's not `sul-dlss/dlme-transform`)
* [x] Determine where to manage Traject macros in current app
* [x] Migrate mapping-related configurations outside of the DLME app

**Comment by jcoyne** [comment]
New repo for traject macros is: https://github.com/sul-dlss/dlme-traject
