### ISSUE TITLE
From the website I should be able to kick of a partial transformation

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#423]

**Comment by justinlittman** [comment]
Might I recommend that the user be able to specify a data directory, just as is done when invoking transform from the Docker container. Specifying no data directory means transform everything.

**Comment by jacobthill** [comment]
This ticket will be considered complete when I can:

- [ ] specify a data directory to run a transformation similar to invoking the transform from the Docker container
- [ ] receive a file not found error message if the data file is not found
- [ ] receive an error message if the mappings json file does not have mapping from data file to config file
- [ ] receive an validation error message if the IR does not validate
- [ ] in the event of a successful transformation, receive a report specifying the number of files transformed
- [ ] be able to view the new files in the staging environment

**Comment by jacobthill** [comment]
@justinlittman What do you need me to review on this ticket? I think the work you did in #435 covers the first item on the acceptance criteria. The others may have already been covered in previous commits?

**Comment by justinlittman** [comment]
I demoed this to @jacobthill. Now ready for code review.

**Comment by justinlittman** [comment]
Never mind. Already merged.
