### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dlme#437]
https://github.com/sul-dlss/dlme/tree/master/docs should either be updated or removed or a bit of both.

**Comment by anarchivist** [comment]
Keep:
* Application profile and model diagram
* Framing statement for prototype

Replace/Edit:
* docs/Readme content (refers to prototype)
* Data flow diagram
* top-level readme

Move:
* Add data source (to dlme-harvest?) 
* basic configs (to dlme-traject?)
