### ISSUE TITLE
Exhibit dashboard: recent item indexing activity is missing date, elapsed time, etc.

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#467]
![screen shot 2019-03-05 at 10 02 11 am](https://user-images.githubusercontent.com/73732/53826620-d9b35e80-3f2d-11e9-89c2-7417242ff025.png)

I expect to see information about when an indexing job run, how long it took, and how many items were indexed.

**Comment by aaron-collier** [comment]
Ugh, this works in local docker dev... so some level of inconsistency in AWS... poking...

**Comment by aaron-collier** [comment]
Fixed by: https://github.com/sul-dlss/terraform-aws/pull/331
