### ISSUE TITLE
Diagnose reindexing performance and mitigate issue

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#493]
Currently, a reindex of everything in the DLME app requires ~16 hours. Unlike other Spotlight deployments, the metadata is not being pulled from an external data source or API when we reindex, as it should be reindexing the IRs that are persisted to the database. To that end we should:

* [x] 👩‍⚕️ Diagnose why reindexing takes so long
* [x] 🗣  Talk with the access team about particular strategies that we could use to mitigate this, and where they should live (e.g. upstream in Spotlight, or the DLME app?)
* [ ] 🔧 Fix it

**Comment by jcoyne** [comment]
@aaron-collier thinks that the 16 hours we saw last week was due to an infrastructure problem.  Now seeing 3-4hours.

**Comment by aaron-collier** [comment]
** Why reindexing takes so long **

Reindexing is taking 3-4 hours. This is the result of having a single spotlight collection with ~137,000 items (and growing). The works out to between 7-12 items indexed per second. This indexing performance is typical and generally acceptable. Our use case (one collection with lots of items) is beyond the typical use of spotlight (several collections with few items).

**Comment by aaron-collier** [comment]
**Meet with the access team regarding indexing performance**

During our meeting with the access team last week on 3/14, we identified the note above, as well as adding the suggestion of benchmarking the system (Refs #496). 

Of note, not only are we using a single, very large collection, but we may also be using spotlight "resources" in a sub optimal way.

https://github.com/projectblacklight/spotlight/wiki/Resource-Scenarios 

We may want to revisit customizing our resource structure in a future work cycle.

**Comment by anarchivist** [comment]
> Reindexing is taking 3-4 hours. This is the result of having a single spotlight collection with ~137,000 items (and growing). The works out to between 7-12 items indexed per second. This indexing performance is typical and generally acceptable. 

From a Spotlight perspective, I agree that this is generally acceptable.

> Of note, not only are we using a single, very large collection, but we may also be using spotlight "resources" in a sub optimal way.
>
> https://github.com/projectblacklight/spotlight/wiki/Resource-Scenarios
>
> We may want to revisit customizing our resource structure in a future work cycle.

We may also want to revisit whether Spotlight makes sense at all for the DLME portal use case. If we're not using the curation features up front, it may make more sense to refactor the app to be a simpler Blacklight app, along with an admin UI to start mapping and reindexing jobs. (The admin component could live inside or outside the Blacklight app.) If we need curation features later, we could have a separate Spotlight app. I'm not leaning one way or another at this point but I suspect that this would be perhaps another joint conversation between the Access and Infrastructure teams.

**Comment by anarchivist** [comment]
We're OK with 3-4 hours and are closing this for now.
