### ISSUE TITLE
Remove BnF SALT Galata data from stage

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#495]

**Comment by aaron-collier** [comment]
Done.

**Comment by jacobthill** [comment]
@aaron-collier can you hold off on this? I think we need this data to debug https://github.com/sul-dlss/dlme/issues/516#issuecomment-481311617

**Comment by jacobthill** [comment]
Ignore that comment @aaron-collier what I meant was don't delete the Sakip Sabanci data yet. I'll add this comment to the correct ticket.
