### ISSUE TITLE
Deploy only a specific version of the image

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#499]
https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/

**Comment by justinlittman** [comment]
For both dlme and dlme-transform.

**Comment by justinlittman** [comment]
@aaron-collier This is done for dlme-transform. Verifying that we want to use a tagged version for staging and prod, right?

**Comment by aaron-collier** [comment]
@justinlittman I've set it for both staging and prod, yes, as staging is really part of prod for this particular app.

https://github.com/sul-dlss/terraform-aws/pull/381
