### ISSUE TITLE
two different data paths result in same S3 id

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#514]
`stanford` and `ancient-numismatic-society` have the same S3 url. When I try to add stanford items, ancient-numismatic-society items are added instead.

![Screen Shot 2019-04-03 at 12 56 58 PM](https://user-images.githubusercontent.com/37662787/55509105-39c22100-5610-11e9-8dde-ed97076db284.png)

**Comment by jcoyne** [comment]
It looks like this could happen if two items are kicked off in the same second: https://github.com/sul-dlss/dlme-transform/blob/eaf2c3946d00a3f3e79bcd224924ada798356d29/invoke.sh#L22

**Comment by jcoyne** [comment]
@justinlittman  Could we use `uuidgen` rather than date?

**Comment by justinlittman** [comment]
Yes, but it would be really surprising if two were kicked off in the same second. Are we sure that is the source of the problem?

**Comment by jacobthill** [comment]
I don't think they were both kicked off in the same second, the timestamp is 15 seconds different. I think `ancient-numismatic-society` was started first and `stanford` fifteen seconds later but `ancient-numismatic-society` hadn't finished yet. Though `met` was run between these two and had a unique url.

**Comment by justinlittman** [comment]
+1 on uuidgen. That one is new to me.

**Comment by jcoyne** [comment]
@jacobthill the timestamp you see on the page is for finish time.  The TIMESTAMP in dlme-transform is when the container was ready to start work.  It's totally possible for 2 containers that were told to start 15s apart to be ready at the same time.

**Comment by jacobthill** [comment]
@jcoyne the source of the timestamp and TIMESTAMP make sense. I was just agreeing with @justinlittman that they probably were not started within a second of each other. I don't know if the problem resulted from them finishing at the same time.

**Comment by justinlittman** [comment]
Closed by https://github.com/sul-dlss/dlme-transform/pull/135
