### ISSUE TITLE
Add items in prod needs `Queued for processing.` message

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#515]
Adding items in stage `https://spotlight.stage.dlmenetwork.org/library/resources/new` results in a `Queued for processing.` message. Adding items in prod `https://spotlight.dlmenetwork.org/library/resources/new` gives no message. Should result in the same `Queued for processing.` message.

**Comment by jcoyne** [comment]
@aaron-collier is it possible that the prod environment doesn't have up-to-date webapp code?

**Comment by aaron-collier** [comment]
@jcoyne likely, as any changes since before the last week or so haven't been applied in prod, I'll get this updated today.

**Comment by aaron-collier** [comment]
Last deploy on prod was 3-7. Will submit a PR now.
