### ISSUE TITLE
Re transforming and re adding items does not result in changes

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#516]
When changing the mappings, rerunning the transformations in stage and re-adding items the data displayed in the facets is not updated. The bnf data, for example, in stage is from an old transformation even though the latest transformation `https://s3-us-west-2.amazonaws.com/dlme-metadata-stage/output-20190403193712.ndjson` was added. This S3 bucket was added to prod and the results are as expected in prod but not in stage, presumably because the data was already in stage.

**Comment by jcoyne** [comment]
Can you provide specific examples of "as expected"?

**Comment by jacobthill** [comment]
@jcoyne look at the type facets for the bnf data in prod https://spotlight.dlmenetwork.org/library and look at the type data for bnf in stage https://spotlight.stage.dlmenetwork.org/library. Stage has several unnormalized values.

**Comment by jcoyne** [comment]
Can you explain what you are doing to just show the bnf data?  Do you mean you are clicking the "Bibliothèque nationale de France" value under "Source Institution"?

**Comment by jacobthill** [comment]
yes and then looking at the values that remain in the type facet

**Comment by jcoyne** [comment]
@jacobthill I don't see records such as "https://spotlight.stage.dlmenetwork.org/library/catalog?f%5Bsource_institution%5D%5B%5D=Biblioth%C3%A8que+nationale+de+France&f%5Btype%5D%5B%5D=Dergi+-+Review" in the file: https://s3-us-west-2.amazonaws.com/dlme-metadata-stage/output-20190403193712.ndjson

If those records aren't in the `.ndjson` file, they aren't going to be updated.

**Comment by jacobthill** [comment]
@jcoyne Those records aren't there because they have been deleted from dlme-metadata. They should be removed from stage https://github.com/sul-dlss/dlme/issues/495

**Comment by jcoyne** [comment]
@jacobthill I'm not sure this ticket makes sense then.  Are there any records that should have been updated that weren't?

**Comment by jacobthill** [comment]
@jcorne I'm not positive. Its hard to tell whats going on. I have ran the AUC and the Sakip Sabanci back through and still getting unnormalized types but I just realized there was an error in the types translation map which may have caused these. You just merged two pull requests that will let me confirm one way or the other.

**Comment by jacobthill** [comment]
@jcoyne the Sakip-Sabanci data did update this time through so this is most likely not an issue. I will close it for now and reopen if I need to.

**Comment by jcoyne** [comment]
@jacobthill can you give an example of two records you believe to be duplicates?  What environment are you looking at?
