### ISSUE TITLE
Confirm whether merges to master automatically trigger updates in stage and prod

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#520]

**Comment by aaron-collier** [comment]
Note, for dlme-webapp and dlme-workers, a tagged version (`1.0.0`) is deployed so merges to master do not trigger an update anywhere. A tagged release must be created and then a PR made in terraform to update the tagged release number.

Currently, for dlme-transform, as this is a triggered task (not a running container), a new image is pulled when it is ran. We push the `:latest` image on merges to master, so (with a short delay) any merges to master are available for transform in both stage and prod.
