### ISSUE TITLE
Debug transforming large datasets

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#521]
Transforming large datasets does not seem to work (try `penn` for an example). Nothing happens from a UI perspective. We will have more datasets that are larger than penn and @jacobthill needs to be able to transform these in stage without developer help. Here is an attempt at requirements:
- [ ] should be able to transform datasets of 250,000 records
- [ ] if the above is not feasible, add a way to break the dataset into smaller chucks via the UI
- [ ] if a transform fails, times out, etc. the results should be reported back in transform results as "failed" with a reason

**Comment by jcoyne** [comment]
@jacobthill if the container is terminated by hitting the memory cap, we have no way of reporting it back.  I suspect that's what's happened here.

**Comment by jacobthill** [comment]
@jcoyne Ok maybe we can do without the error reporting. Is there a way to automatically break up larger datasets so it won't try to load the whole thing in memory?

**Comment by aaron-collier** [comment]
Confirming that in this case, it was as @jcoyne mentions that the container hit a memory cap and crashed. There is no logging available related to this or way to error report it. I've upped the memory, which results in a data error I posted in the channel.

**Comment by anarchivist** [comment]
As of standup around April 11, this should be closable.
