### ISSUE TITLE
Verify that data needed to drive dashboard is present in IR, or add it

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#528]
One feature that will be added by the Access team is a public-facing data dashboard. We need to add all data that is not available in the current data model. We also need to confirm that all  Items marked IR are accessible via a SOLR query.

Requirements:
- [x] IR: total number of contributing institutions in stage (use agg_data_provider not agg_provider)
- [x] IR: total number of contributing institutions in prod (use agg_data_provider not agg_provider)
- [x] IR: total number of records from each institution (stage and prod)
- [x] IR: total number of collections from each institution (stage and prod)
- [ ] country of each contributing institution (stage, prod, and non-partner) (Does it make sense to add this to the IR by putting it in the [metadata_mapping](https://github.com/sul-dlss/dlme-traject/blob/master/metadata_mapping.json) file and adding a `to_field` to each config?)
- [x] IR: cho_edm_type of each record (stage and prod)
- [x] IR: cho_has_type of each record (stage and prod)
- [x] IR: language of each record (stage and prod)

@justinlittman, @jcoyne does this make sense? Let me know if anything needs clarification. @anarchivist, @waynegraham, and @tomcramer may have a few things to add/change still.

**Comment by jcoyne** [comment]
The IR items sounds like queries that could be written against Solr, right?

**Comment by jcoyne** [comment]
@jacobthill have you engaged a UX designer about this feature?  It seems like having one of them create a comp could help us understand what it is intended to look like.

**Comment by jacobthill** [comment]
@jcoyne, yes the IR items could be written as queries against solr. I'm working on the view tickets for the access team now. I will share those with Gary and Astrid once they are complete.

**Comment by jacobthill** [comment]
Also, this could be implemented as two separate objects if it makes sense technically to do so. The IR items will drive the public facing dashboard and the others will drive the governing partner dashboard.

**Comment by jcoyne** [comment]
@jacobthill I don't think we have a mechanism to tell who is a governing partner from those who are public users.

**Comment by jacobthill** [comment]
@jcoyne do you mean that information is not stored anywhere or that there is no means of differentiating access levels?

**Comment by jcoyne** [comment]
@jacobthill We don't have an user groups or levels in DLME that I'm aware of.

**Comment by jacobthill** [comment]
@waynegraham that would simplify things for the infrastructure team. If we approach it that way, I can use a spreadsheet to track the institutions not partnering (which I already have) and generate visualizations elsewhere. I think that would make the rest of this a ticket for the access team, assuming they can get all the data they need by querying solr.

**Comment by jcoyne** [comment]
I confirmed that all the IR marked entries are in solr via https://github.com/sul-dlss/dlme/blob/master/app/resource_builders/dlme_json_resource_builder.rb. I don't know if there's more we need to do here.

**Comment by aaron-collier** [comment]
Thanks @jcoyne
