### ISSUE TITLE
Public-facing view for exhibit analytics/statistics

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#531]
Need a public facing data dashboard to show statistics about the current state of DLME. Is seems that the data needed can be pulled from the intermediate representation (IR) via solr query or from Google Analytics (GA).

Requirements:
- [ ] Design work
- [ ] IR: total number of contributing institutions (use unique values from agg_data_providor and agg_providor)
- [ ] IR: total number of records from each institution
- [ ] IR: total number of collections from each institution (need to figure out how to get this; its not in the IR)
- [ ] country of each contributing institution 
- [ ] IR: type of each record 
- [ ] IR: language of each record 
- [ ] GA: total number of users
- [ ] GA: country of users

**Comment by ggeisler** [comment]
@jacobthill A few questions about the requirements:

> IR: total number of collections from each institution (stage and prod)

How is a collection defined? In our currently running instances, there is no facet with the label "Collection" so I'm not sure what this is. Is it a grouping of records from a given institution that we keep track of in the IR and just aren't exposing on the site as a facet?

> country of each contributing institution (stage, prod, and non-partner) (depends on

What does this depend on (I think your sentence was cut off)?

**Comment by ggeisler** [comment]
Below is a mockup for an initial version of the public-facing statistics page. I'll make another ticket as a [placeholder for some potential enhancements](#638), but it seems like the essential things we'd want to show are represented in this mockup.

This is not intended to be the final visual design of the page; after I get further with the site visual design (#134) I should be able to make the design of this page look a bit better.

The counts shown in the mockup come from various sources; @jacobthill can either post a follow-up comment in this ticket about where to get the counts, or work with the developer who takes this ticket on via other means to figure out how to get them.

I believe we'd like this page to exist on -prod, -staging, and -dev, although the Users highlight box and Users section is only applicable to -prod.

### A - Link to Statistics page
The page involves things (tables, mainly) we can't do wit Sir Trevor widgets so I'm proposing we:

- [ ] Manually add a main menu item called "Statistics" 
- [ ] Create a static page to contain the Statistics page content ("Statistics" header should be an `<h1 class="page-title">`, I think)

### B - Highlight the three main metrics we want to convey
- I used Bootstrap's `.jumbotron` for the items, contributors, and users highlight boxes, but customized them to remove a bunch of stuff (also, set to only display when viewport is `md` or wider):

```html
<div class="row d-none d-md-flex justify-content-around">
    <div class="jumbotron col-4-md">
      <h2 class="display-6">999,999 items</h2>
      <hr class="my-4">
      <p class="text-center">4 item types</p>
    </div>
     ...
```

### C - Items, Contributors, Users sections
The remainder of the page is three sections with a similar structure:
- Header is an `<h2>`
- Values in the tables for the Items and Contributors sections are linked to the associated facet value. So if the user selects "Turkish" from the language table that should take her to a results page with the Language > Turkish facet value selected.
- Values in the Users table are not linked 

### D - Items by type table
- The indention shown in this table represents the sub-types that we expect to be part of the Type facet, after it is made a hierarchical facet as described in #552 

### E - Contributors table, Country column
- I'm not sure if the country of each contributing institution is currently part of the data. @jacobthill might need to work with whoever takes on this ticket to figure out how to get this value.

### F - Contributors table, Collections column
- Similarly, some work might need to be done to ensure we have represented and indexed the number of collections associated with each contributing institution.

### G - Users table
- This is derived from Google Analytics data

<img width="833" alt="Screen Shot 2019-11-04 at 3 45 45 PM" src="https://user-images.githubusercontent.com/101482/68168823-5e280800-ff27-11e9-88f0-20bac4649ab8.png">

**Comment by cbeer** [comment]
This requires some upstream work (https://github.com/projectblacklight/spotlight/issues/2237) to allow applications to reliably add different menu items.

**Comment by jkeck** [comment]
Some documentation on adding a page like this in spotlight: https://github.com/projectblacklight/spotlight/wiki/Adding-new-navigation-menu-items

**Comment by jkeck** [comment]
Just as a heads up, I've been cobbling something together for the basic item content/jumbotrons (building on top of #669).  It's rough, but would love to pair up on this on Monday.

<img width="871" alt="Screen Shot 2019-11-08 at 7 01 19 PM" src="https://user-images.githubusercontent.com/96776/68521891-56839e80-025a-11ea-86d1-4ce99d86c0ad.png">

**Comment by jkeck** [comment]
I'm closing this as all other tasks have been spun off into separate issues.
