### ISSUE TITLE
Enhance record only viewing

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#535]
Improve display of single records including:
- [ ] consistent display of thumbnails (currently thumbnails appear in different places depending on their size) ([example one](https://spotlight.stage.dlmenetwork.org/library/catalog/themaghribpodcast.podbean.com%2Frencontre-litteraire-avec-lecrivain-riadh-hadir-autour-de-son-dernier-roman-pupille-8f5e3f972b269a188e0d6118634a1a1d), [example two](https://spotlight.stage.dlmenetwork.org/library/catalog/cambridge_genizah-11643), [find example three of image pushed to top right]())
- [ ] the agg has view field (really, the idea that you can click and go to the partner site to see the full record) is not apparent to some partners. This needs to be more clear, maybe by moving it to the top and/or adding visual indicators that there is a link.

**Comment by ggeisler** [comment]
I'm unclear on whether we will be displaying all DLME items in a Mirador viewer or not? 

If so, I think this problem goes away, because the viewer will take full width of the show page and the metadata will be displayed below it.

If not, I can work on a PR to update the relevant HTML and CSS to make things look better, after I understand what viewer we will be showing items in, and I have real data indexed into my local DLME app.

**Comment by cbeer** [comment]
I'll defer to @jacobthill, of course, but my understanding is only some items have images associated with them and a subset of  those are available by IIIF and could be displayed in a Mirador viewer.

**Comment by ggeisler** [comment]
Okay, thanks @cbeer. I'll just wait until I have local data to work with and either make a PR or specify design recommendations here for someone else to work on.

**Comment by ggeisler** [comment]
@jacobthill See #715, #716, and #728 for a more complete proposal for handling the show page. But for the `agg_is_shown_at` value more apparent to users, the idea is to show a link beneath the item thumbnail:

<img width="393" alt="Screen Shot 2019-11-21 at 10 16 27 AM" src="https://user-images.githubusercontent.com/101482/69363905-90877400-0c4e-11ea-83b4-ca222fa7af8a.png">

If you think that satisfies your concern about that, you can close this ticket and watch for the work on consistent placement of the thumbnail to be done in #728.

**Comment by jacobthill** [comment]
@ggeisler I think that will be ok but we would okay. We plan to get some partner feedback in the future but I think we can move ahead with this plan for now.
