### ISSUE TITLE
Enhance browse records viewing

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#537]
Thumbnails currently overlap (in list view) when the record has little metadata to display. See [example one](https://spotlight.stage.dlmenetwork.org/library/catalog?f%5Bsource_institution%5D%5B%5D=The+American+Institute+for+Maghrib+Studies&page=2), [example two](https://spotlight.stage.dlmenetwork.org/library/catalog?f%5Bsource_institution%5D%5B%5D=American+University+in+Cairo&page=506).

<img width="1175" alt="Screen Shot 2019-10-02 at 3 50 14 PM" src="https://user-images.githubusercontent.com/37662787/66087517-9bfece80-e52c-11e9-9fa8-a6ed4d5ce60c.png">

**Comment by ggeisler** [comment]
A simple (though not 100% ideal) solution to this is to make the following change to the `.document-thumbnail img` [selector here](https://github.com/sul-dlss/dlme/blob/1d6ca38dcfed159117866fd74c1dffb139d18ad4/app/assets/stylesheets/blacklight.scss#L30)

```css
img {
  max-height: 100px; // was: max-height: 200px;
  max-width: 100px; // was: width: 100px;
}
```
I believe that will ensure the thumbnail is never larger than 100x100, while maintaining the aspect ratio. Our result item rows have a min-height of 100px so, for example, the problem in the screenshot above would end up more like this:

<img width="970" alt="Screen Shot 2019-10-29 at 4 13 30 PM" src="https://user-images.githubusercontent.com/101482/67816407-1278e880-fa67-11e9-850e-18731fedc0bc.png">


The downside is, if the result item has enough metadata to make its row height over 100px (which is often the case) and the result item's thumbnail image is relatively narrow and tall (not as likely, but could happen with certain types of DLME resources), the thumbnail image could end up being 20x100 or something, when there is sufficient item row height to show it at 40x200.

But I think that might be a worthwhile tradeoff. So my inclination is to implement the SCSS update above, and then see how it works out with a range of DLME items and revisiting the solution if necessary.
