### ISSUE TITLE
Metadata Priorities

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#54]
In the initial stages of this project we want to show off the ability to display show off the "gee–whiz" aspect of data. To that end the following list of object types was developed (in a rough prioritized list):

- Manuscripts
- Maps / Spatial Data
- IIIF
- 3D
- Images / Visual Art Resources
- Museum Objects
- Movie Posters
- Architectural Records
- Videos
- Books
- Newspapers
- Others

As this is a short work cycle, we need to prioritize specific collections which have a variety of content types and minimize the amount of engineering needed to process the data.

- **Manuscripts**
  - http://library.princeton.edu/projects/islamic/ (IIIF?)
  - https://github.com/waynegraham/dlme-metadata/tree/master/manuscript/records/penn/schoenberg (TEI)
  - Stanford (IIIF?)
- **Maps** (these were scraped from a search of Stanford's GeoBlacklight instance; we will need at some point to have a better solution for identifying and collecting spatial data)
  - https://github.com/waynegraham/dlme-metadata/tree/master/maps/records 
- **IIIF**
  - Stanford
  - Princeton
  - BnF
  - BSB
  - Vatican
  - QNL
  - British Museum?
  - Internet Archive? 
- **3D**
  - https://sketchfab.com/danderson4 (I can get him to send metadata, but this is a scholar's research collection)
  - http://numismatics.org/search/results?q=department_facet:%22Islamic%22 (should be able to get Ethan Gruber to get us a dump of metadata)
  - Others? Maybe http://www.europeana.eu/portal/en/search?f%5BTYPE%5D%5B%5D=3D&q=mosque&view=grid ?
- **Images / Visual Art Resources**
  - [Met Museum OpenAccess Records](https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/met_museum_records.csv) (CSV)
  - [Penn Museum Egyptian](https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/penn-egyptian-csv-latest.zip) (CSV)
  - [Penn Museum Near East](https://github.com/waynegraham/dlme-metadata/blob/master/museum/records/penn-near-eastern-csv-latest.zip) (CSV)
- **Movie Posters** (I need to get the full dump of these)
  - https://github.com/waynegraham/dlme-metadata/tree/master/movie-posters/records/princeton
  - Stanford?
  - There were other groups that worked on this project, we could possibly (easily) add these as well to create a coherent collection
-  **Architectural Records**
  - See https://github.com/waynegraham/dlme-metadata/issues/1 
- **Videos**
  - A/V has been a little difficult to find, but http://www.europeana.eu/portal/en/search?f%5BTYPE%5D%5B%5D=VIDEO&q=mosque&view=grid may be good enough to show off the functionality
- **Books**
  - I'm thinking these will be in parts of the IIIF collections from Stanford, BnF, Vatican, BSB, British Museum, or QNL (and Internet Archive).
- Other (the lowest possible priority)
  - http://syriaca.org (http://syriaca.org/documentation/wiki.html?wiki-page=/The-Syriaca.org-web-application&wiki-uri=https://github.com/srophe/srophe-eXist-app/wiki)
  - http://www.etana.org/ (Drupal)

Specific items identified from Stanford's collection include:

Voyage d’Egype et de Nubie: https://searchworks.stanford.edu/view/9275720
Otttoman diploma in calligraphy: https://searchworks.stanford.edu/view/nk663xb7601
Portrait of the emperor Jahangir: https://searchworks.stanford.edu/view/cm881bj1960
Walters ms W.586: Work on the duties of Muslims toward the Prophet Mohammed: https://searchworks.stanford.edu/view/tk780vf9050
Single leaf from the Arabic version of Dioscorides’ De materia medica: https://searchworks.stanford.edu/view/dx161mc8937
Map/Travel image of Egypt: https://searchworks.stanford.edu/view/9275720
More maps of MENA: https://searchworks.stanford.edu/view/mm896qm6737, https://searchworks.stanford.edu/view/rz546pm0247
Modern sons of the Pharaohs; a study of the manners and customs of the Copts of Egypt: https://searchworks.stanford.edu/view/994416
Veiled mysteries of Egypt and the religion of Islam: https://searchworks.stanford.edu/view/2974646
A browse by call number view of some items (both digitized and still tangible): https://searchworks.stanford.edu/browse?start=2974646&view=gallery

**Comment by anarchivist** [comment]
One of the things that we should be sure to distinguish is the type of IIIF resources that are available. For instance, we should clarify whether there is just an IIIF image server, or if there are also manifests.

**Comment by cmh2166** [comment]
So how do we prioritize for things where records aren't captured yet? And how to handle format prioritization that leads to us having work / records dupes in this list?

**Comment by anarchivist** [comment]
My understanding is that if  we don't have sample records yet then we can't prioritize it. 

What do you mean by "work / records dupes"?

**Comment by aaron-collier** [comment]
Can we get a progress update on which of these have been addressed, and which can't be addressed until we have data? Are there any above for which we have data and haven't created and/or implemented the mapping yet?
