### ISSUE TITLE
Debug record deletion

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#540]
There are a number of record deletion errors. When possible, the steps to reproduce the error are listed. These errors should not be solved. Instead this ticket can be used to test https://github.com/sul-dlss/dlme/issues/527 once it is complete.

### Records in the metadata repo have been deleted

In cases where there are fewer records in the metadata repo than there were in a past transformation (e.g. one of the collections from AUC was deleted from the metadata repo and the transformation was re run) if the latest url is used to delete records it will not delete the records that have been removed from the metadata repo. 

Steps to reproduce error:
Warning: the only way to do this is to delete records from dlme-metadata master branch. You need to save these records locally and push them back up after testing.
-from dlme-metadata
-delete directory 'p15795coll14'
-push changes to master
-navigate to https://spotlight.stage.dlmenetwork.org/transform
-select 'transform data' tab
-enter 'auc' 
-select 'begin transform'
-select 'transform results'
-copy the aws url once it appears 
-https://spotlight.stage.dlmenetwork.org/
-select 'exhibit dashboard' from the dropdown menu in the top right corner
-select 'items' on the left
-select 'delete items' in the middle of the page
-paste the aws url
-check the number of records left after process finishes (should be 1062-the number of records in the 'p15795coll14' directory that you deleted from dlme-metadata)

Also, some collections, for unknown reasons, cause errors when trying to delete records. For example, the Palestine Poster Project Archive I added these records: https://s3-us-west-2.amazonaws.com/dlme-metadata-stage/output-d3fad795-0404-4518-99ef-0d798e98c218.ndjson 
then updated the config file to include a rights statement and added them again:
https://s3-us-west-2.amazonaws.com/dlme-metadata-stage/output-6ac53307-ba38-47ac-a2dd-ee4c69031616.ndjson but they didn't update (e.g. the rights statement wasn't included which was likely because I mapped it to cho_rights instead of cho_dc_rights), so I used both urls to delete the items. All of the records were deleted except 3. We need to figure out why this happened and how to prevent it from happening again. A similar error occurred with AUB records. Not sure how to reproduce this. It might be caused from adding records and then deleting them before they finish adding but this is a guess.

Collections @jacobthill cannot delete: 
- [ ] American Numismatic Society (stage)
- [ ] AUB (stage)
- [ ] AUC (stage)
- [ ] Penn Museum (prod)
- [ ] University of Penn (prod)
- [ ] Palestine Poster Project Archive (stage)

**Comment by aaron-collier** [comment]
Calling this complete for now. I was able to delete all of the stanford records I deleted in Dev. We will add this to the friday release.

**Comment by jacobthill** [comment]
I wasn't able to delete the Harvard or Bodleian records from stage using the S3 url. Should I be able to do that at this point?
