### ISSUE TITLE
Translate spotlight & blacklight UI labels into Arabic

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#541]
Requirements:
- [ ] get English UI labels to translators (Blacklight & Spotlight)
- [ ] get Arabic translation from translators
- [ ] store translated labels in [yaml file](https://github.com/projectblacklight/spotlight/blob/master/config/locales/spotlight.it.yml)

**Comment by jacobthill** [comment]
@aaron-collier don't merge this. @ggeisler pointed out that it should go in spotlight instead of dlme.

**Comment by aaron-collier** [comment]
Being addressed upstream.

**Comment by camillevilla** [comment]
projectblacklight/blacklight#2190
projectblacklight/blacklight#2197
projectblacklight/spotlight#2218
projectblacklight/spotlight#2214
projectblacklight/blacklight-gallery#59
