### ISSUE TITLE
DLME Internationalization overview

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#545]
## Description

This is a significant feature with many moving parts. This ticket summarizes all of the steps at a high level. The individual steps have been broken out into smaller tickets and linked here. I have also created a milestone with the name 'DLME Internationalization' in each repo and assigned the smaller tickets to that milestone.

## Requirements:

1. translate Spotlight UI labels into Arabic (data manager) https://github.com/sul-dlss/dlme/issues/541
![ui-labels](https://user-images.githubusercontent.com/37662787/61634634-bb8d9700-ac5f-11e9-94a0-581a39658f17.png) 
2. translate text (prose and headings) into Arabic (data manager) https://github.com/sul-dlss/dlme/issues/542
![prose](https://user-images.githubusercontent.com/37662787/61634227-e1ff0280-ac5e-11e9-8033-4b8bf03fb271.png)
3. translate metadata field values for cho_edm_type, cho_has_type, date, holding institution, source institution, and language (if possible) (data manager & Infrastructure team) https://github.com/sul-dlss/dlme-traject/issues/110, https://github.com/sul-dlss/dlme-transform/issues/172, https://github.com/sul-dlss/dlme-transform/issues/173, https://github.com/sul-dlss/dlme-transform/issues/171, https://github.com/sul-dlss/dlme-transform/issues/174, https://github.com/sul-dlss/dlme-transform/issues/155
![metadata-values](https://user-images.githubusercontent.com/37662787/61634389-3904d780-ac5f-11e9-9a1c-57352d8cef64.png)
4. redesign the DLME intermediate representation (IR) (Infrastructure team) https://github.com/sul-dlss/dlme-transform/issues/173
5. update each config file so that they map to the updated IR (data manager & Infrastructure team) https://github.com/sul-dlss/dlme-traject/issues/112
6. design work (Access team) https://github.com/sul-dlss/dlme/issues/544

## Examples of multi-lingual metadata records:
- QNL has separate records for Arabic and English. The ID is the same except the ar or en endings. The English can be mapped to the Arabic by matching id.
- AUB has mixed records. Some fields are always in Arabic; others are in English (numbers mainly)
- AUC has mostly English with a few Arabic fields.
- SSM has modern Turkish
- Princeton has transliterated Arabic and English for some fields (e.g. description)
- Harvard has multiple languages including French, English, and transliterated Arabic
- BnF has French

**Comment by ggeisler** [comment]
Closing since all of the issues seem to be covered by more actionable tickets, such as #544, #601, and #589.
