### ISSUE TITLE
Add IIIF support for exhibit objects

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#550]
Stanford manuscripts ([example](https://spotlight.stage.dlmenetwork.org/library/catalog/stanford_nk663xb7601)) are viewable through Mirador. Other collections have iiif metadata but the images displayed are static images ([example](https://spotlight.stage.dlmenetwork.org/library/catalog/cambridge_genizah-12255)). Can we make these collections viewable through Mirador? 

Collections that support iiif:
- [ ] QNL (waiting for data update from QNL)
- [ ] Cambridge
- [ ] Princeton

Requirements:
- [x] enable Mirador viewer for above collections

**Comment by cbeer** [comment]
The example links no longer work (and stage only has 3 records?) Is it possible to update these so we have some fixture objects to work with?

**Comment by jacobthill** [comment]
This is still blocked by https://github.com/sul-dlss/dlme/issues/630 but you can see an example of what Mirador would look like with Arabic and English metadata [here](https://spotlight.stage.dlmenetwork.org/library/catalog/stanford_tk780vf9050)

**Comment by caaster** [comment]
We want a DLME-styled/specific Mirador viewer. Starting point will be sul-embed M3 configuration (minus theme & plugins). (NOTE: no plugins means no share option)

**Comment by aaron-collier** [comment]
I'm not clear why this would be blocked by #630 - we should be able to produce fixture data in order to work towards the mirador viewer. If I'm misunderstanding how the facets relate to this, please clarify.

**Comment by cbeer** [comment]
Yes, example fixtures would help. Without being able to see the examples linked in the ticket, it's hard to know what the requirement is (and if we currently have the data to support it..)

**Comment by cbeer** [comment]
Yes, example fixtures would help. Without being able to see the examples linked in the ticket, it's hard to know what the requirement is (and if we currently have the data to support it..)

**Comment by cbeer** [comment]
Confirmed at standup on 11/5 this isn't currently blocked.
