### ISSUE TITLE
View for cho_has_type (hierarchical facet)

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#552]
Depends on https://github.com/sul-dlss/dlme-transform/issues/155. DLME has three type values: `cho_edm_type`, `cho_has_type`, and `cho_type`. The second field is a subcategory of the first field (e.g. one value of `cho_edm_type` is Text which has possible `cho_has_type` values of 'manuscript', 'book', etc.). The view should reflect this hierarchy. `cho_type` is whatever value the raw data provides when we receive it from the data provider. This could be useful as well and should also be useable. These values are not standardized; they could be thought of as tags.

**Comment by ggeisler** [comment]
Below is a first-pass at how we might handle `cho_edm_type` and `cho_has_type`, although I haven't seen any real data yet and don't have a sense of how items are distributed across types and sub-types. This is just the most obvious and straightforward approach, based on using a hierarchical facet.

### Display in facets
Use a hierarchical facet, as done in Searchworks (e.g., Call number facet). I'm using the label "Type" for now; as we move ahead perhaps we'll find a less generic term.

<img width="322" alt="Screen Shot 2019-10-14 at 4 09 07 PM" src="https://user-images.githubusercontent.com/101482/66789063-d9ede200-ee9e-11e9-8e19-2ce50d6d4410.png">

### Display on show page
This facet is likely important enough to display on a show page. Again, the most obvious idea seems to display the hierarchy on a single line with a separator:

<img width="825" alt="Screen Shot 2019-10-14 at 4 15 02 PM" src="https://user-images.githubusercontent.com/101482/66789173-5e406500-ee9f-11e9-8bb9-2a23ca6f6187.png">

**Comment by ggeisler** [comment]
Note that I've split out the question of how we handle the `cho_type` field into a [separate ticket](#594), since it seems distinct from the `cho_edm_type` and `cho_has_type` fields.

**Comment by jkeck** [comment]
It doesn't feel like this is actionable currently.  I don't believe we have the data to support a hierarchical facet in the index, and will need to split this off into a ticket in dlme-transform.
