### ISSUE TITLE
Metadata discovery short-list

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#56]
I've assembled this short list by comparing what we have, DPLA, Europeana collections, and exhibits.stanford.edu:

## querying
- [x] basic keyword searching that includes textual fields (e.g. title, contributors, etc)
- [x] fielded search for titles
- [x] fielded search for creators / contributors
- [x] improve recall by indexing textual fields into a stemmed field (needs language identification)

## faceting
- [x] faceted search by language, type, spatial, temporal, date, provider
- [ ] rights
- [ ] creator / contributor
- [ ] ~physical arrangement information (series, box, folder, etc?)~

## sorting
- [ ] sort by title
- [ ] ~sort by date~ 
- [ ] sort by creator

**Comment by anarchivist** [comment]
>  physical arrangement information (series, box, folder, etc?)

I might strike this; I'm not sure relevant for us. cc @waynegraham

**Comment by cbeer** [comment]
👍 Strike away. It was just something I noticed in exhibits.
