### ISSUE TITLE
SC #2 - Improve Record Deletion

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#564]
There are multiple concerns related to record deletion:

- [x] Inconsistent results
- [ ] Poor user experience

**Comment by aaron-collier** [comment]
Note, this is presumed complete, however final testing in stage is being held until changes to data transformations is complete so that existing stage data can safely be removed and reproduced.

**Comment by jacobthill** [comment]
I tried to delete everything in stage yesterday, in preparation for adding updated data. There are 3 AUB records that I cannot delete. This is concerning. They were added on 7/22 but running the 7/22 transform url does not remove them. Just to make sure, I used every other AUB url but none of them worked.

**Comment by aaron-collier** [comment]
I'm pretty sure we've seen this before and it's likely something in the data and probably something that is making it difficult (or impossible) to link the data in the way that we are applying deletion. Let's pair on this early next week.
