### ISSUE TITLE
SC #3 - Data Internationalization

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#567]

**Comment by mjgiarlo** [comment]
@aaron-collier I suspect we are done, or close to done, with this epic in this work cycle.

**Comment by aaron-collier** [comment]
@mjgiarlo I need to verify with @jacobthill as there are still (I believe) a couple of things he may be waiting for... I could be mistaken, but I do think we're done on the development side. Something to verify by friday.
