### ISSUE TITLE
Index dates, date ranges, approximate dates, etc to drive e.g. a date range slider

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#57]

**Comment by cmh2166** [comment]
Does this require date normalization (not currently a priority, but something I now know how we would do if needed)

**Comment by anarchivist** [comment]
It might. It would also probably require us in some cases to be able to (automatically) distinguish between Hijri era dates and CE/BCE dates.

**Comment by jacobthill** [comment]
This will require date normalization. One macro to normalize anything that exists in incoming data date fields is likely unfeasible. Even if we could get it to work, it has the potential of breaking with the addition of each new dataset. Consider writing normalizations at the collection level or at some intermediate level between collection and all records in dlme.

**Comment by jacobthill** [comment]
Closed via https://github.com/sul-dlss/dlme-transform/issues/152 and https://github.com/sul-dlss/dlme-transform/issues/153
