### ISSUE TITLE
How to expose to the user the `cho_type` field?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#594]
Related to #552. @jacobthill wrote in that ticket description:

> `cho_type` is whatever value the raw data provides when we receive it from the data provider. This could be useful as well and should also be useable. These values are not standardized; they could be thought of as tags.

I haven't seen examples of this field so don't have a sense of how many distinct values there might be, but if there are many different values and we can't normalize them through some sort of mapping, then I wonder if we should just make them exhibit item tags?

If they are tags, we can expose them to the user; on item show pages for sure and potentially a Tags facet (though that might have limited value if there is a huge number of distinct values). Even if different data providers use very different `cho_type` values, presumably for a given data provider the `cho_type` values will have some internal consistency, so the tags could potentially help a user find similar items based on tags, even if those items are just from that data provider.

Is there a downside to using exhibit item tags for this field? Or am I missing a better way to display this field?

**Comment by jacobthill** [comment]
@ggeisler there are three type values in our application profile: cho_type (raw value from user), cho_edm_type (the normalized values currently in the app, based on the Europeana Data Model), and cho_has_type (sub types of cho_edm_type). I'm not sure if cho_type will be useful to display, or how/where to display it. One thought is to filter/navigate using only the two normalized type fields but display cho_type for additional context.
