### ISSUE TITLE
Give access team admin access to DLME sites

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#602]
I assume the whole team will need access.

**Comment by aaron-collier** [comment]
This is complete to the extent it currently can be. It looks like @mejackreed needs to sign up in dev/stage/prod and @jkeck needs to sign up in prod. Otherwise, the remainder that have signed up are now admins.

**Comment by mejackreed** [comment]
Just signed up on all three. Sorry for the delay.

**Comment by aaron-collier** [comment]
Done
