### ISSUE TITLE
Curation > Translations page not available

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#606]
When I add a new language in my local DLME exhibit, I should see a Curation > Translations menu option:

<img width="1201" alt="Screen Shot 2019-10-29 at 9 33 58 AM" src="https://user-images.githubusercontent.com/101482/67882409-6cc58800-faff-11e9-9dce-6f8c5a3fab92.png">

I don't though:

<img width="1219" alt="Screen Shot 2019-10-30 at 10 22 12 AM" src="https://user-images.githubusercontent.com/101482/67882441-7bac3a80-faff-11e9-93da-4e54e8a47d6f.png">

I was going to see if this is also the case on the production or staging DLME sites, but I don't have access to the admin for those (waiting for #602).

Perhaps related (assuming this is related to DLME not having the latest release of Spotlight or something), the Arabic locale is not an option in the Language select, even though it has been merged into Spotlight.

**Comment by camillevilla** [comment]
Might be that we didn't update the configured locales upstream: 
https://github.com/projectblacklight/spotlight/blob/ba0750c330fffab6674e82759fb48c09c4ea6745/lib/spotlight/engine.rb#L204-L215

**Comment by camillevilla** [comment]
Arabic is now available in the Curation > Translations menu as of #625. However, Arabic Blacklight keys will be available in the UI until we cut a new Blacklight release AND update Spotlight.
