### ISSUE TITLE
Consider local dev experience improvements

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dlme#612]
Look into ways to make local development easier + possible without running docker (or redis / postgres / etc)

- [x] https://github.com/sul-dlss/dlme/pull/610

**Comment by jkeck** [comment]
I'm going to take a look at if postgres is required.  It looks like it's not but I want to say that @ggeisler needed to install it in order to get the app up and running.  I'll validate that.

**Comment by jkeck** [comment]
FWIW, at the current state of the `master` branch, you not longer need to have redis/sidekiq running (although can be nice for indexing/debugging) and postgres is not required (it seems to run fine on sqlite).

**Comment by ggeisler** [comment]
@jkeck In case it helps, I believe my issue was:

1. Ran bundle install
2. Got an error when it was trying to install `pg 1.1.4`
3. Installed postgres with Homebrew
4. Re-ran bundle install, this time successfully

So it seems like step 3 was necessary, but it would be good for someone else to verify that, for sure.

**Comment by cbeer** [comment]
I /think/ you should be able to run `bundle install --without production` and not need postgres.
