### ISSUE TITLE
Collect a representative set of fixture data

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dlme#619]
It would be helpful for local development if there was a set of fixture data that could be easily indexed as part of the setup process.

**Comment by jkeck** [comment]
@jacobthill would you be able to provide us with a few objects from a sampling of the source organizations?  A goal will be to get some variety of the various data shapes we are to expect coming from the different source organizations.  Also, if you're aware of any outliers that we'll want to be aware of (thinking outliers in metadata, multilingual support, IIIF support vs thumbnails vs no representative image, etc) those would be good to add as well.

I'm not sure what the best way to identify these objects for us/transfer them to us. The identifiers in a dev/stage instance will probably work unless you all have a better way of sharing this sort of thing.

**Comment by jacobthill** [comment]
@ jkeck Sure do you want just the json that appears in the IR?

**Comment by jkeck** [comment]
@jacobthill the JSON as it appears in the IR would work out.  If it would be possible to create a JSON document that has a good representative set of documents (from a representative set of institutions) that would be great.  Many of the JSON docs in the IR are pretty large, so just want to make sure we don't end up indexing thousands of docs unnecessarily.

**Comment by jacobthill** [comment]
@jkeck I dropped the first set in the dlme channel yesterday. We can keep this open until I finish revising the configs and then I will give another set with all of the language keys.

**Comment by caaster** [comment]
https://docs.google.com/spreadsheets/d/1UJH2kAdsnx-F_7nhn3STOouKLPLjpq0wk0V4FSbtBH4/edit#gid=0
