### ISSUE TITLE
Resource management and administration scaffolding for intermediate representations

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#62]
- [x] Update existing, directly-added IRs
- [x] Delete IR resources
- [x] <strike>Deduplication and</strike> validation tooling

**Comment by jcoyne** [comment]
@cbeer what does "Deduplication and validation tooling" entail?

**Comment by cbeer** [comment]
We can push those out-of-scope for this ticket.

For deduplication, we talked about additional ways to identify duplicate records (especially for things loaded from by different metadata formats). 

For validation, we idly mused about validating our IRs against a http://json-schema.org/ schema, so supporting that and somehow flagging non-compliant records?
