### ISSUE TITLE
Emails aren't being sent from Fargate-deployed instances

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#626]
[dlme/stage] ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

## Backtrace

    line 13 of [PROJECT_ROOT]/lib/middleware/fix_sns_json_middleware.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53082/faults/46564896)

**Comment by jkeck** [comment]
I _believe_ this has this been addressed?

**Comment by cbeer** [comment]
Has it? I'm still getting errors sending emails in -dev at least.

**Comment by jkeck** [comment]
I thought somebody had reported working on it. I guess I erroneously assumed progress had been made.

**Comment by mejackreed** [comment]
Emails seem to no longer be raising errors. I've successfully confirmed the following emails on dev:
 -  Add contact email + confirmation
 - Feedback to exhibit contacts emails
