### ISSUE TITLE
Exhibit export doesn't seem to work in the AWS deployed instances?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#629]
Maybe it's hitting a timeout or something?

**Comment by aaron-collier** [comment]
@cbeer is this something I should look into on the infra side? Happy to pick it up if so.

**Comment by aaron-collier** [comment]
This works find for me in dev with < 200 items. I'll load >20k and see what happens.

**Comment by aaron-collier** [comment]
I've successfully exported with around 24k items. I'm guessing this may timeout with larger collections, at which time we may want to look at larger containers. For now, closing.
