### ISSUE TITLE
Use an Arabic font when the locale is Arabic

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#655]
Part of #544.

Because Arabic characters are shorter than Latin characters, we should try to use a more Arabic-optimized font when the locale is Arabic. I'm far from an expert on this but from some investigation it seems like the Google font "Amiri" might be a good choice.

- https://fonts.google.com/specimen/Amiri

This font will show Arabic text slightly larger than what we currently see on the DLME site, and look better/more consistent when there is mixed Arabic and Latin text (as is the case for metadata values for some records).

There might be a lot more to this when we get into the details, but as a start:

- [ ] Embed the Amiri font into `<head>` so all users will have the font
- [ ] Specify a `font-family: 'Amiri', serif;` selector in the CSS so that when the locale is "Arabic" we use that font-family stack

A couple of things we might do to follow this up:

- Figure out how to use the Amiri font for metadata fields (or show page item titles) we know are displaying Arabic, even when in the English locale
- Change the default font stack (for English locale) to use a font that might be more complementary to Amiri

**Comment by camillevilla** [comment]
I took a quick look into this and noticed that implementing this will require some upstream work in Blacklight and Spotlight. Tickets incoming 📝

**Comment by mejackreed** [comment]
The analysis to why this original proposal was not used is in #709
