### ISSUE TITLE
Display search results as RTL

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#676]
Part of #544. UI text in mockup below is shown as English but would be Arabic when we have integrated all necessary translations.

Although shown in the mockup for context, breadcrumbs are covered in #673 and facets are covered in #674.

### A: Search result labels, constraints, and controls
- [x] Elements that are normally left-aligned in content area are right-aligned ("You searched for" label and prev|next navigation block)
- [x] The colon for the "You searched for" label should be on the left-side of the label
- [x] prev|next navigation block: components are flipped, including the "x - y of z" label
- [x] Constraint controls are flipped so that the delete button is to the left of the label portion
- [x] The "Start over" button is left-aligned
- [x] The grouping of search result view icons and per-page and sort by menus is left-aligned and reversed from normal order
- [x] The icon for the pulldown control on the "sort-by" and "per page" buttons is on the left of the label
- [x] The order of the search result view icons is flipped from normal order
- [x] The "List" icon (the currently selected icon in the mockup below) is flipped horizontally, so the bullets part of the icon is on the right instead of the left. `transform: scaleX(-1);` does this on Chrome, and likely(?) all other browsers we care about. According to [Caniuse](https://caniuse.com/#search=transform) some IE versions don't support `transform` for SVGs, but a transform attribute can be used. Might require a bit of investigation, although it isn't the end of the world if the icon is not always flipped.

The other result view icons do not need to be flipped (they're either more or less symmetrical or a special case (slideshow icon)).

### B: Result items
- [x] Arrangement of result item elements is flipped: thumbnail is right-aligned in main content area, metadata field labels are left-aligned, metadata values are right-aligned
- [x] Result item numbers: The number is right-aligned and the period goes to the left of the number, regardless of whether we stick with Western Arabic numbers or convert to Eastern Arabic numbers, as discussed in #639. (I don't know if we're going to include the default Blacklight item numbering in DLME, but I'm including it in the mockup in case we are doing this work upstream and want to make sure that it's handled for any future adopters that do want to include item numbering.) 
- [x] Result item title: Follows the number and is right-aligned, so if the title wraps it starts the second line at the right-side of the content area

### C: Pagination
- [x] Pagination elements are flipped so that the group is right-aligned and starts (from a RTL perspective) with Previous, etc.

### Mockup - List view

<img width="998" alt="Screen Shot 2019-11-11 at 5 15 23 PM" src="https://user-images.githubusercontent.com/101482/68631175-fdf51100-04a6-11ea-83bf-1942460c0ab4.png">

---

In each of the Gallery, Masonry, and Slideshow views we show item thumbnails in some form of a grid, where the result items start with the top-left corner. We need to reverse that arrange for RTL:

- [x] In the Gallery, Masonry, and Slideshow views, flip the thumbnail layout so the first item thumbnail is displayed in the top-right corner of the result content area

Each type of view has an additional adjustment necessary.

### Gallery view
It appears that in Gallery view we center the result item thumbnails, so the only thing we need to adjust here is:

- [x] Right-align item titles

<img width="979" alt="Screen Shot 2019-11-11 at 5 37 16 PM" src="https://user-images.githubusercontent.com/101482/68632083-98a31f00-04aa-11ea-9b62-e7e7e55678d4.png">

### ~Masonry view~ => #713 
In Masonry view we appear to center the (on hover) item titles, so the only thing we need to adjust is:

- [ ] Right-align the result item thumbnail area

<img width="979" alt="Screen Shot 2019-11-11 at 5 38 50 PM" src="https://user-images.githubusercontent.com/101482/68632659-82965e00-04ac-11ea-842f-6e3fc43fa454.png">

### Slideshow view
In Slideshow view we mostly center things so the only adjustment needed is:

- [x] Right-align the result item thumbnail area

<img width="979" alt="Screen Shot 2019-11-11 at 5 39 42 PM" src="https://user-images.githubusercontent.com/101482/68632512-ff750800-04ab-11ea-8d65-52051cc44e86.png">

**Comment by cbeer** [comment]
> The "Start over" button is left-aligned

Should that be right-aligned (currently left-aligned in LTR)?

**Comment by ggeisler** [comment]
> Should that be right-aligned (currently left-aligned in LTR)?

I guess we are using different LTR references. I see that the Blacklight demo aligns the "Start over" button to the far left of the content area, but I'm using the current DLME (and Vatican as a secondary reference, given it is our other significant Spotlight customization example) as my reference, and they have the "Start over" button right-aligned:

<img width="1201" alt="Screen Shot 2019-11-12 at 8 56 21 AM" src="https://user-images.githubusercontent.com/101482/68687947-30e0e880-052b-11ea-9acb-ee19515e59a3.png">

---

<img width="1201" alt="Screen Shot 2019-11-12 at 8 58 38 AM" src="https://user-images.githubusercontent.com/101482/68687969-3e966e00-052b-11ea-8a68-0c58c3146e99.png">

---

But I'm happy to defer to your judgement if it makes sense to start by sticking to the most vanilla Blacklight/Spotlight implementation. We might need to adjust some elements later, though.

**Comment by cbeer** [comment]
Masonry view may be tricky; we're using a 3rd party library to handle all the positioning. It looks like the library might support some form of RTL if we had a mechanism to send it configuration.

Before diving too deep, I want to confirm that masonry view is desired for DLME.

**Comment by cbeer** [comment]
Ah, I think that must be a change between Blacklight 6 + 7. Here's its position in 7:

<img width="501" alt="Screen Shot 2019-11-12 at 08 06 40" src="https://user-images.githubusercontent.com/111218/68688308-608bf280-0523-11ea-89da-1f7805abdbd1.png">

**Comment by ggeisler** [comment]
>Before diving too deep, I want to confirm that masonry view is desired for DLME.

Good question. We haven't received any requirements that detailed from our stakeholders. I personally don't think our current masonry view adds that much value over the other view options. If it comes down to offering masonry view but having it look odd in RTL versus not offering masonry view, I'd opt for not offering it.
