### ISSUE TITLE
Curation > Translations menu not available

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#679]
After you add a language via Configuration > General > Languages, you should see a new sidebar menu entry of Curation > Translations. I don't see this in DLME even though Arabic is added as a language (this is on -dev):

<img width="939" alt="Screen Shot 2019-11-12 at 5 52 39 PM" src="https://user-images.githubusercontent.com/101482/68723475-e2a50700-0575-11ea-9b16-f171005f3e04.png">

We'll need access to Curation > Translations so Jacob can enter the exhibit-specific translations.

**Comment by cbeer** [comment]
Fixed by https://github.com/sul-dlss/dlme/pull/678.
