### ISSUE TITLE
Add a Users section to the Statistics dashboard

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dlme#689]
Split out from #531

### G - Users table
* This is derived from Google Analytics data (depends on #522)

![Screenshot](https://user-images.githubusercontent.com/101482/68168823-5e280800-ff27-11e9-88f0-20bac4649ab8.png)

**Comment by cbeer** [comment]
We've deprioritized this until we know whether we want to display this data.

**Comment by ggeisler** [comment]
If and when work on this, I think we might consider a couple of minor wording changes:

B - For the users jumbotron card, use the label "888,666 visitors" (`visitors` in place of `users`)
G - For the heading, use "Site visitors" instead of "Users"
