### ISSUE TITLE
Add a field to indicate that content was indexed from a "collection"

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dlme#702]
A provider can provide several "collections" to the DLME site.

The Contributors section of the statistics dashboard indicates how many "collections" are included from each provider (see #688).  We do not currently have a field that differentiates which documents are part of which collection w/i the content indexed for a given provider.

Note: Our current UI requirements don't indicate the need for a user facing string for the name of the collection, just that we can count how many collections a given provider has contributed (presumably via faceting).

**Comment by aaron-collier** [comment]
Complete.
