### ISSUE TITLE
Update layout of show page to handle different types of items

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#715]
My understanding is that we will have three types of items in DLME:

- A: IIIF items
- B: Items are not IIIF but have a thumbnail image
- C: Items that are not IIIF and don't have a thumbnail image 

- [x] #716 - For Case A, we want to display in the Mirador Viewer, with the item metadata below the viewer.

- [x] #728 - I think cases B and C can be handled in the same way, since items without a thumbnail can use the placeholder thumbnail. For these cases we want to display the thumbnail image left-aligned (or right-aligned in RTL) with the item metadata adjacent, rather than beneath, the image.

FWIW, we don't handle Cases B/C well at the moment, even in Exhibits. For example, an uploaded image is shown left-aligned on the show page and the metadata is shown beneath, even though there can be plenty of space to show the metadata adjacent to the image. So I'm not sure whether some of this work might be done in Spotlight.

#### Example of uploaded item show page in Exhibits:

<img width="1182" alt="Screen Shot 2019-11-20 at 1 43 45 PM" src="https://user-images.githubusercontent.com/101482/69276522-e3542380-0b9b-11ea-894c-ec3cd464724e.png">

**Comment by cbeer** [comment]
In exhibits, I believe we explicitly chose to put the metadata underneath an uploaded image (for parity with other viewers, I guess)?: https://github.com/sul-dlss/exhibits/issues/1336

**Comment by ggeisler** [comment]
Hmm, yeah, although that ticket indicates the viewer should be full-width like Mirador, which might make it feel a bit better. Although it still seems awkward with smaller images like my example above.

Also there is some weirdness at different viewport widths:

<img width="1019" alt="Screen Shot 2019-11-20 at 2 09 46 PM" src="https://user-images.githubusercontent.com/101482/69278454-9c682d00-0b9f-11ea-99fe-fb3dfd2771a8.png">

Maybe we can do better after the BS4 upgrade and using `flex` for laying out things more flexibly based on the size of the image?

Anyway, from what I've seen of the DLME items with thumbnails, it seems to me they would work well with metadata to the side rather than underneath, so I still think this is worth discussing.

**Comment by cbeer** [comment]
👍 ; I'm just saying that exhibits may not be a good example of what spotlight does.
