### ISSUE TITLE
Update layout of show page for IIIF (Mirador 3 viewer) items

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#716]
Related to #715 and #728.

For IIIF items I think we can just use our current Exhibits approach to displaying an item in a M3 viewer with the metadata below it as the goal for DLME. There might be some thought needed to figure out how to get roughly the same layout of the metadata, since the Exhibits example is not using the upgraded BS4 code, but:

- [x] Mirador 3 viewer should be full-width of the content area, for all responsive sizes
- [x] Viewer should be `550px` in height, at least as a first pass
- [x] Metadata should be displayed below the viewer
- [x] Since long metadata values can extend quite far in a wide viewport, set a max-width on the metadata values to `50em;`

<img width="1019" alt="Screen Shot 2019-11-20 at 1 50 31 PM" src="https://user-images.githubusercontent.com/101482/69277247-2cf13e00-0b9d-11ea-8bb9-86081d929038.png">

**Comment by cbeer** [comment]
@jacobthill : are there examples of these "IIIF items"? That's probably a prerequisite for tackling this.
