### ISSUE TITLE
Record titles are not displaying in dev

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#719]
The newly transformed collections (Cambridge, Sakip Sabanci, etc.) don't have titles though the titles should be present in the IR.

**Comment by cbeer** [comment]
I took a look at https://spotlight.dev.dlmenetwork.org/library/catalog/cambridge_genizah-11814. The IR we're getting seems to be missing a title, suggesting to me an issue with the transform.

<img width="478" alt="Screen Shot 2019-11-20 at 14 08 31" src="https://user-images.githubusercontent.com/111218/69282542-6aef6180-0b9f-11ea-885c-5f0ac5fcb80e.png">

**Comment by jacobthill** [comment]
@cbeer is that the IR or the solr data? If you look at the output of both of the transforms: [Cambdrige](https://s3-us-west-2.amazonaws.com/dlme-metadata-dev/output-4c2913b0-f254-487d-b43b-fc866adb2e85.ndjson), [Sakip Sabanci](https://s3-us-west-2.amazonaws.com/dlme-metadata-dev/output-8326f038-39c7-4270-9f4f-5ceed5a9f9e6.ndjson) all of the records have titles. I'm not sure where you are pulling that data from but is seems like something its not a transform problem. Could it be an issue with how things are getting indexed into solr?

**Comment by cbeer** [comment]
I'll have to defer to the @sul-dlss/infrastructure-team; this is the data we're seeing in Solr, and my understanding is the IR is being indexed as it is provided. Here's what I see in the dump you linked:

> {"cho_title":{"en":[""]},"cho_creator":{"en":[""]},"cho_date":{"en":["13th century"]},"cho_date_range_norm":[1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299],"cho_date_range_hijri":[596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699],"cho_dc_rights":{"en":["This image may be used in accord with fair use and fair dealing provisions, including teaching and research. If you wish to reproduce it within publications or on the public web, please contact <a href='mailto:genizah@lib.cam.ac.uk'>genizah@lib.cam.ac.uk</a>.","This metadata is licensed under a Creative Commons Attribution-NonCommercial 3.0 Unported License."]},"cho_description":{"en":["Letter"]},"cho_edm_type":{"en":["Text"],"ar-Arab":["نص"]},"cho_extent":{"en":["1 leaf.\n                              14.3\n                              10.2"]},"cho_has_type":{"en":["Manuscript"],"ar-Arab":["مخطوط"]},"cho_language":{"en":["Judeo-Arabic","Hebrew"],"ar-Arab":["العربية اليهودية","العبرية"]},"cho_provenance":{"en":["Donated by Dr Solomon Schechter and his patron Dr Charles Taylor in 1898 as part of the Taylor-Schechter Genizah Collection"]},"cho_publisher":{"en":["Cambridge University Library"]},"agg_data_provider":{"en":["Cambridge University Library"],"ar-Arab":["مكتبة جامعة كامبريدج"]},"agg_data_provider_country":{"en":["United Kingdom"],"ar-Arab":["المملكة المتحدة"]},"agg_provider":{"en":["Cambridge University Library"],"ar-Arab":["مكتبة جامعة كامبريدج"]},"agg_provider_country":{"en":["United Kingdom"],"ar-Arab":["المملكة المتحدة"]},"cho_type_facet":{"en":["Text","Text:Manuscript"],"ar-Arab":["نص","نص:مخطوط"]},"id":"cambridge_genizah-11814","agg_is_shown_at":{"wr_id":"https://cudl.lib.cam.ac.uk/view/MS-TS-AS-00147-00188/1"},"agg_preview":{"wr_id":"https://image01.cudl.lib.cam.ac.uk/content/images/MS-TS-AS-00147-00188-000-00001_files/8/0_0.jpg"}}

**Comment by mjgiarlo** [comment]
> I'll have to defer to the @sul-dlss/infrastructure-team; this is the data we're seeing in Solr, and my understanding is the IR is being indexed as it is provided. Here's what I see in the dump you linked:
> 
> `{"cho_title":{"en":[""]},"cho_creator":{"en":[""]},"cho_date":{"en":["13th century"]},"cho_date_range_norm": ...`

That looks like an invalid transformation to me too.

**Comment by jacobthill** [comment]
I think this should be two tickets: I see 29 records in the Cambridge data that are missing titles but the overwhelming majority have titles. cho_title is a required field and an error should be raised in transform if there is no title (it used work that way and the contract seems to indicate that that is still the intended behavior) so those 29 Cambridge records should have caused an error. I have opened a [ticket](https://github.com/sul-dlss/dlme-transform/issues/413)

Most of Cambridge and all of Sakip Sabanci seem to have titles but none are showing up. It seems to me like something is going with the display.

Here are several records where the data is clearly present in the IR and SOLR:
 https://spotlight.dev.dlmenetwork.org/library/catalog/oai:cdm21044.contentdm.oclc.org:abidindino%2F2379
https://spotlight.dev.dlmenetwork.org/library/catalog/oai:cdm21044.contentdm.oclc.org:abidindino%2F2424
https://spotlight.dev.dlmenetwork.org/library/catalog/cambridge_islamic-36

I think almost all of them are like these while a handful of them might actually be missing the title.

**Comment by cbeer** [comment]
Ah -- these Turkish records are using a BCP39 code we weren't expecting. It looks like that was a recent change in the transform code? (https://github.com/sul-dlss/dlme-transform/pull/395)
