### ISSUE TITLE
CORS issue with uploading masthead image?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#722]
Following up discussion today about the absence of a masthead image, I tried to upload a masthead image as a test and it fails to load in the image cropper. I get this console error, doing this from https://spotlight.dev.dlmenetwork.org/library/appearance/edit:

> Access to XMLHttpRequest at 'https://spotlight.dlme.clir.org/images/5/info.json' from origin 'https://spotlight.dev.dlmenetwork.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by cbeer** [comment]
I removed the masthead image (presumably it was imported from the -prod site?), but it also seems like the server is missing some critical dependencies (#723)
