### ISSUE TITLE
Use IIIF manifest urls provided by the IR

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#734]
This should replace the case statement for `SolrDocument#iiif_manifest_url` with some mapping institutions to IIIF manifest URL patterns upstream to indexing (#734). There seems to be an established pattern for IIIF Image API identification (based on https://pro.europeana.eu/files/Europeana_Professional/Share_your_data/Technical_requirements/EDM_profiles/IIIFtoEDM_profile_042016.pdf), ~but not for IIIF manifests~ and a small note about the pattern for manifests in §1.5.

Is there any intent to record this information in the IR (or was the expectation that all DLME resources are single images and will never have a IIIF manifest?)

**Comment by anarchivist** [comment]
> Is there any intent to record this information in the IR (or was the expectation that all DLME resources are single images and will never have a IIIF manifest?)

The intent was to record this information in the IR when we have it - either directly from the source metadata, or in cases where it's fairly predictable and can be mapped(e.g., we know how to get to a manifest from a Stanford PURL). TMK this has not yet been implemented in the mappings.

**Comment by cbeer** [comment]
Fixed by #747
