### ISSUE TITLE
Handling multi-record XML loading

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss/dlme#74]
We need to support parsing XML files with multiple records. See below for details and examples.

Original issue: 

> I'm curious how this would break things given our current set up. Not pressing for this work right now, but will come up.

**Comment by cbeer** [comment]
Because of our reliance on file names as identifiers, probably among other things?

**Comment by jcoyne** [comment]
What does a multi-record XML look like?

**Comment by cbeer** [comment]
MODS collection? EADs where we want to target subresources? I'm not sure if @cmh2166 had a particular use-case in mind or just flagging it as a choice we've made.

**Comment by cmh2166** [comment]
Yes, exactly, @cbeer . I was wondering, given not just the filename reliance for IDs but the way the XPath look up is set up, how it would break if we passed a mods:collection XML document that had multiple records in that same document.

That said, again, it was more of this doesn't effect us now, but should be captured as a data expectation for any loading / ingest docs.

**Comment by cmh2166** [comment]
Documented in #290 - doesn't close, just records our decision.

**Comment by jacobthill** [comment]
Here are a few files that have multiple records for testing:
- https://github.com/sul-dlss-labs/dlme-metadata/blob/master/bnf/bo/data/bo.xml
- https://github.com/sul-dlss-labs/dlme-metadata/blob/master/bnf/cealex/data/cealex.xml
- https://github.com/sul-dlss-labs/dlme-metadata/blob/master/bnf/ebaf/data/ebaf.xml
- https://github.com/sul-dlss-labs/dlme-metadata/blob/master/bnf/ideo/data/ideo.xml

**Comment by justinlittman** [comment]
@jacobthill The links to sample files above no longer work. Can you update?

**Comment by jacobthill** [comment]
- https://github.com/sul-dlss/dlme-metadata/tree/master/bnf/ebaf/data
- https://github.com/sul-dlss/dlme-metadata/tree/master/bnf/salt
- https://github.com/sul-dlss/dlme-metadata/tree/master/bnf/ideo/data

**Comment by justinlittman** [comment]
So these are all separate files. Do we have examples where they are a single file?

**Comment by jacobthill** [comment]
No, not currently. I can get some data in that format.

**Comment by justinlittman** [comment]
Since this is a rather old ticket, let me ask the question: Is this something that we need to do?

**Comment by jacobthill** [comment]
yes, I think we do. Here is some test data.

https://github.com/sul-dlss/dlme-metadata/tree/add-test-data/test-multi-record-xml

**Comment by justinlittman** [comment]
Try a configuration like:
```
settings do
  provide 'writer_class_name', 'DlmeJsonResourceWriter'
  provide 'reader_class_name', 'Traject::NokogiriReader'
  provide 'nokogiri.namespaces', LOC_NS.clone(freeze: false)
  provide 'nokogiri.each_record_xpath', '//srw:records/srw:record'
end
```

**Comment by jacobthill** [comment]
I think this covers what we need.
