### ISSUE TITLE
Bug experienced with attempted desktop upload of image for Browse category thumbnail

### ISSUE THREAD

**Issue by caaster** [sul-dlss/dlme#748]
Behavior I experienced:

1. Using Google Chrome Version 78.0.3904.97 (Official Build) (64-bit), I navigated to the following browse category: https://spotlight.dev.dlmenetwork.org/library/browse/year-1400-to-1200
and selected "Edit"

2. I selected the "Thumbnail" tab, selected the radio button to "Upload an image" and chose a 229 KB PNG file on my desktop (a screenshot of an image in this browse category from the contributing institution's website)

3. As soon as I selected the file to upload, I saw the following dialog:

![Screen Shot 2019-11-25 at 1 47 15 PM](https://user-images.githubusercontent.com/3210225/69583150-0a8d6500-0f8f-11ea-9f96-c6041967d90f.png)

4. Next, I clicked "OK" in the dialog box I was presented with in the screenshot above, and then I saw this error message:

![Screen Shot 2019-11-25 at 1 47 43 PM](https://user-images.githubusercontent.com/3210225/69583299-6b1ca200-0f8f-11ea-88c0-6a3cc586e18a.png)

Expected behavior:

I expect to be able to successfully upload a PNG image of less than 10 MB from my desktop and have it display as a Browse category thumbnail.

**Comment by cbeer** [comment]
Which browser? And, are you able to reproduce this reliably?

**Comment by caaster** [comment]
@cbeer Chrome version as noted in step #1 on the ticket. Yes, I have been able to reproduce this reliably in Chrome. Will test other browsers and report back.
