### ISSUE TITLE
Create a mechanism for uploading data records for transformation and indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/dlme#75]
In Spotlight's "Add New Item" UI, create a way for curators (and Wayne) to select or upload files (using browse-everything?), select one of our existing transformations, and kick off an import job to transform them to DLME JSON IR resources.

<img width="930" alt="screen shot 2017-08-15 at 2 00 39 pm" src="https://user-images.githubusercontent.com/111218/29336301-318a7920-81c2-11e7-8296-553b2d5fdac9.png">

**Comment by jcoyne** [comment]
@cmh2166 can you paste the relevant comments in here?

**Comment by jcoyne** [comment]
The refactoring done in #113 should make this pretty easy.

**Comment by cbeer** [comment]
Also, we could add a button for `fetch_and_import` and `reprocess` into the existing UI.

**Comment by jcoyne** [comment]
There is a button in #172
