### ISSUE TITLE
Document individual collection names per provider

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#750]
@jacobthill - can you please create a list of providers and their individual collections? When possible, map to existing traject configs, when in a shared config, map to the individual dlme-metadata path.

**Comment by jacobthill** [comment]
@aaron-collier some of this information is already available in the metadata_mappings file. The only purpose of this is to capture the collection count. The two ways I can think of doing this are to manually input the count for each institution or to count the number of direct child folders that are transformed (e.g. if a transform path is `harvard` and there are two sub directories `islamic-heritage-project` and `maps` then there are two collections for the harvard data provider'). I'm happy to make the list if needed,  just don't want to duplicate information if there is another way.

**Comment by aaron-collier** [comment]
@jacobthill I believe they want individual collection names for dashboard stats. Let's confirm at stand up.

**Comment by jacobthill** [comment]
@aaron-collier the collection names don't exist anywhere currently. There is not a one-to-one mapping of config to collection and putting that info in the metadata mapping file could be complicated to maintain. Is there a way to grab the collection from the transform path? That seems to be the best approach I can think of. Then if we want to expose it to the user at some point we could use a translation map. Does that make sense?

**Comment by jacobthill** [comment]
The metadata paths were designed to be provider/collection/data/records consistently

**Comment by aaron-collier** [comment]
Right. I'll start a doc with relatively generic information based on the paths and then we can iterate on it.

**Comment by aaron-collier** [comment]
https://docs.google.com/spreadsheets/d/1dikUvrIML3Z_u3mDeHlHvmm2iTqaPOjLibz2-gkIqwg/edit#gid=0

**Comment by aaron-collier** [comment]
Closed via: https://github.com/sul-dlss/dlme-transform/pull/428
