### ISSUE TITLE
Result view icons should be larger

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#761]
![Screen Shot 2019-12-03 at 9 52 38 AM](https://user-images.githubusercontent.com/101482/70076048-d92a2000-15b2-11ea-8a12-87f72512b7f1.png)

It looks like they all are rendered as 16x16 even though the width and height attributes of their `<svg>` elements are larger. If they were rendered at the size specified in their width and height attribute values they might be the size we want (not 100% sure without seeing them in the larger rendered size).

If we implement #763, which reduces the height of the buttons, I think it is only the second and third icons (gallery and slideshow) that need enlarging.

**Comment by mejackreed** [comment]
For implementer, should likely happen in Blacklight-Gallery

**Comment by ggeisler** [comment]
FWIW, I noticed in base Spotlight (running latest master locally) the icons look bigger than in DLME and are the size we want, more or less:

![Screen Shot 2019-12-04 at 10 35 08 AM](https://user-images.githubusercontent.com/101482/70170892-7b650900-1682-11ea-8c27-704099600d49.png)

**Comment by mejackreed** [comment]
@ggeisler we updated the icons in Blacklight-Gallery to use the Material icons and remove Glyphicon dependency. https://github.com/projectblacklight/blacklight-gallery/pull/65

We can update the icons if there is something more specific to use, but the previous ones had some problems with the way that things we/are styled. See: https://github.com/projectblacklight/blacklight-gallery/pull/65/files#diff-8bc72bafc1baa26ba1291fa5f870efc1

This was done to be more inline with what Blacklight is holistically doing with icons, but we can adjust as needed.

**Comment by ggeisler** [comment]
@mejackreed Sure, I remember the switch to Material icons, that's all fine. I'm not really opinionated about **how** we do any of this, I just want to make sure the blacklight-gallery derived icons are larger in DLME and are roughly similar in size to what you see in base Spotlight. I included the screenshot above just as a visual example of what the icon size roughly be for a better visual look in DLME.
