### ISSUE TITLE
Reduce size of search result buttons

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#763]
Use the `btn-sm` class on the search result buttons to make them more likely to stay on a single row with the result navigation elements and reduce their visual dominance.

### Current
![Screen Shot 2019-12-03 at 11 13 56 AM](https://user-images.githubusercontent.com/101482/70082054-78084980-15be-11ea-9a31-27627ef18d41.png)

### With `btn-sm` class added
![Screen Shot 2019-12-03 at 11 17 56 AM](https://user-images.githubusercontent.com/101482/70082124-98380880-15be-11ea-94f5-f8a31a7936b1.png)

**Comment by mejackreed** [comment]
For implementer, should likely happen in Blacklight-Gallery

**Comment by ggeisler** [comment]
@mejackreed Can you say more? The first three of these buttons have nothing to do with blacklight-gallery, correct? We're just making a styling decision specific to DLME.

Or did you mean for this comment to go to #761?

**Comment by mejackreed** [comment]
Yes.. totally my bad .. good catch @ggeisler

**Comment by camillevilla** [comment]
I don't think we necessarily have to do this upstream! We can do this with ✨the magic of Sass✨.
