### ISSUE TITLE
Update date range slider styling

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#765]
- Hide the chart range handles
- Reduce font size of chart x-axis labels to `14px`

![Screen Shot 2019-12-03 at 12 38 06 PM](https://user-images.githubusercontent.com/101482/70087903-033b0c80-15ca-11ea-9572-f7871e7aaf65.png)

- Reduce the `margin-top` on `.limit_content .subsection` to `0.5em;` from `1em`

![Screen Shot 2019-12-03 at 12 40 15 PM](https://user-images.githubusercontent.com/101482/70087958-22399e80-15ca-11ea-896b-db37e26e8a20.png)

- ~~Widen the chart **and** slider bar horizontally so that it uses the full-width of the `card-body`. In the screenshot below notice how the "Unknown 31,593" label goes to the right and left edges of the card body but the date range chart and slider do not. The extra width would be useful when using the sidebar version of the slider.~~ This has been fixed.

![Screen Shot 2019-12-03 at 11 36 27 AM](https://user-images.githubusercontent.com/101482/70083596-8d32a780-15c1-11ea-8ac5-e4d9ef9ec83a.png)

**Comment by jkeck** [comment]
Submitted projectblacklight/blacklight_range_limit#123 for most of the tasks here.
Submitted a PR upstream to flot to deal w/ the last flot/flot#1726 (removing the handles)

**Comment by jkeck** [comment]
PRs that will unblock the config change that will address the final pieces
- [ ] https://github.com/projectblacklight/blacklight_range_limit/pull/144
- [ ] https://github.com/projectblacklight/blacklight_range_limit/pull/145

**Comment by jkeck** [comment]
I believe this can be closed now.  Feel free to re-open / file new issues for additional work.
