### ISSUE TITLE
Are there contacts that should be visible on site?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#772]
Most exhibits use the Contacts section of the About pages to include one or more named contacts with contact info (which shows up on the sidebar of all About page). Do we know if CLIR wants to expose one or more named contacts for the DLME project? Or someone from SUL?

There's currently some generic contact info for CLIR in the footer, but I think this might be better suited for the Contacts section. But ideally that info would be associated with a specific person (though we probably could just name the person "CLIR" if necessary).

@caaster @jacobthill @anarchivist There's no urgency to figuring this out (it's not a blocker and is easy and quick to add) but perhaps something to discuss at the next meeting with Wayne, etc.

**Comment by jacobthill** [comment]
Wayne suggested we keep the generic CLIR contact for now. I think it can be moved to the Contacts section if at your discretion @ggeisler

**Comment by ggeisler** [comment]
Great, thanks @jacobthill. I'll set that up.

**Comment by ggeisler** [comment]
Closing this since I've added a contact for CLIR to the About page sidebar. (I actually added two versions and we can decide on which one to keep after I make some related styling updates.)
