### ISSUE TITLE
Should we enable the Feedback feature?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#773]
Related to #772, do we want to enable DLME site visitors to have access to the Feedback form?

If so, we need at least one email address that would receive the form submissions.

This isn't required, of course (we don't have to expose the Feedback link), but I want to make sure we've made a conscious decision on whether to enable it.

**Comment by jacobthill** [comment]
I will discuss this with Mark and Elizabeth and get back to you.

**Comment by jacobthill** [comment]
I think we do want to enable the feedback feature unless @waynegraham has any reason not to do so.

**Comment by waynegraham** [comment]
I can't think of any reason not to do this right now. If we run in to issues, we can re-evaluate.

**Comment by ggeisler** [comment]
Okay thanks @waynegraham and @jacobthill. I'll use `dlme@clir.org` as the email address that receives the feedback submission unless you have other suggestions.

Note that we can add any number of email addresses to be recipients of the feedback submissions, if that would make sense for DLME.
