### ISSUE TITLE
Fix alignment of subtypes in hierarchical facets

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#774]
<img width="308" alt="Screen Shot 2019-12-04 at 4 19 49 PM" src="https://user-images.githubusercontent.com/37662787/70182510-f265c600-16b1-11ea-8fde-7877c988901a.png">
Subtypes are pushed to the left and it appears that there are five subtypes instead of three.

**Comment by cbeer** [comment]
Could someone with context expand the ticket to describe the desired behavior? Is it just the unnecessarily right indentation or something else?

**Comment by jacobthill** [comment]
The indentation could be smaller and perhaps the font as well. The bullet could also be centered between the two lines when text doesn't fit into a single line so it is clear what text the bullet is associated with. Currently it looks confusing. Not sure how much this can be cleaned up. I think @ggeisler might have had a few ideas.

**Comment by cbeer** [comment]
Ok. So maybe this ticket isn't ready and should be design needed?

**Comment by jacobthill** [comment]
Possibly, I'll defer to @ggeisler
