### ISSUE TITLE
IIIF display issue

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#779]
This is probably a data transformation issue but Aaron is out today and I would like to get a working example. Can someone take a look at [this record](https://spotlight.dev.dlmenetwork.org/library/catalog/f5961709-ef2b-4252-ad3a-b836355f6c85) and confirm if anything is missing (or incorrect) from any field. Is the `agg_is_shown_at`/`wr_id` field correct? I'm not sure why the resource is not viewable.

**Comment by aaron-collier** [comment]
```
agg_is_shown_at:
  wr_is_referenced_by:
  - https://iiif.bodleian.ox.ac.uk/iiif/manifest/https:.json
  - https://iiif.bodleian.ox.ac.uk/iiif/manifest/.json
  - https://iiif.bodleian.ox.ac.uk/iiif/manifest/digital.bodleian.ox.ac.uk.json
  - https://iiif.bodleian.ox.ac.uk/iiif/manifest/inquire.json
  - https://iiif.bodleian.ox.ac.uk/iiif/manifest/p.json
  - https://iiif.bodleian.ox.ac.uk/iiif/manifest/e13a514c-27fa-4320-938b-101658220272.json
```

the manifest extraction is pulling too many values.

**Comment by jacobthill** [comment]
Ok, I'm moving this to dlme-transform.

**Comment by jacobthill** [comment]
Issue moved to [sul-dlss/dlme-transform #442](https://github.com/sul-dlss/dlme-transform/issues/442) via [**ZenHub**](https://www.zenhub.com/)
