### ISSUE TITLE
Develop Mapping for Numismatics CSV

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#79]
The collections from the Numismatics Society provide a CSV of their data under the [Open Data Commons Open Database License](https://opendatacommons.org/licenses/odbl/) at http://numismatics.org/search/query.csv?q=department_facet:%22Islamic%22. There is a cache of this as of Aug 15, 2017 at https://github.com/waynegraham/dlme-metadata/blob/master/coins/numismatic_islam_departmtment.csv.

**Comment by jcoyne** [comment]
@waynegraham there's a typo in the file name. Would you like to fix it?

**Comment by waynegraham** [comment]
@jcoyne Thanks for catching that. I've renamed the file (https://github.com/waynegraham/dlme-metadata/blob/master/coins/numismatic_islam_department.csv)

**Comment by cmh2166** [comment]
Mapping for the fields for numismatic is here: https://docs.google.com/spreadsheets/d/1Sp7uMHizVX7xN7xN9mm-vgEuESQBovXO-qenAo_TV-w/edit#gid=1099940533

**Comment by aaron-collier** [comment]
Closing per PR 166
