### ISSUE TITLE
Arabic Font Display Issue in Subtitle

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#792]
The final period is getting moved to the front of the word and the last letter is in the medial form. When this letter is at the end of a word it should have a different shape. This may be an issue with the font. I'm not sure how to resolve these issues but I'm happy to consult with whoever to come up with a solution.
<img width="363" alt="Screen Shot 2019-12-10 at 11 31 59 AM" src="https://user-images.githubusercontent.com/37662787/70548588-d1cdbe00-1b40-11ea-8af4-09a22f325c2b.png">

**Comment by cbeer** [comment]
Off-hand, I'd guess the font is fine and it's a data entry issue, probably caused by text rendering engines being too clever about automatically handling RTL + LTR.

I tried using `۔` arabic full stop (U+06D4) instead of `.`, and at least it was placed on the correct side?

**Comment by jacobthill** [comment]
@cbeer This addresses part of the problem. The period is in the right place but the other part is that one letter should be in a different form (e.g. it should have a different shape because its the last letter in a word). I don't know how significant this is but it is likely a font issue. Maybe this is a common modern stylistic thing that I haven't seen before. Readers can certainly understand the text. I think we should keep this open for now and ask for the reviewers from QNL to determine if its a problem or not.

**Comment by ggeisler** [comment]
Note that with the proposed site masthead design in #884, we no longer display a site subtitle.

**Comment by jacobthill** [comment]
@cbeer the Arabic full stop seems to solve the misplacement issue. The font issue will likely be solved when we pick a new font. Although this won't be needed in the new masthead it might show up in other places. I will leave this open for now but I think it will be resolved through these other changes.

**Comment by jacobthill** [comment]
Closing this since the sub title has been removed.
