### ISSUE TITLE
ANS IIIF manifests are not usable

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#795]
The ANS IIIF manifests are only available via HTTP.

> @cvilla or @mejackreed can likely consult with recs of how to best work with the contributor to resolve this issue

**Comment by mejackreed** [comment]
Asked on twitter: https://twitter.com/mejackreed/status/1204483379111985152 12/10/2019

**Comment by mejackreed** [comment]
Per Slack discussion and answer on twitter, we have two options:
 - Remove the manifests from the data
 - Proxy the manifests

**Comment by jacobthill** [comment]
@mejackreed what would it take to proxy the manifests? Is this a relatively easy option? If not we can remove the manifests from the IR.

**Comment by mejackreed** [comment]
Unfortunately proxying the manifests feels really suboptimal. We could do it, but it will be kind of a strange thing to do. I'd defer to @cbeer on the approach here but I would like to avoid it if possible.

**Comment by cbeer** [comment]
I agree, @mejackreed; I think the question for @jacobthill is really how important are these AMS manifests compared to our other priorities, knowing that nearly all other providers won't have this issue and there's no drop-in option to support that behavior.

**Comment by jacobthill** [comment]
I will remove the iiif manifests. I don't think we need to create custom solutions for iiif display.
