### ISSUE TITLE
"Contacts" sidebar header is showing as Arabic in English locale

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#809]
When in English, the "Contacts" sidebar heading is showing the Arabic version, rather than "Contact":

<img width="484" alt="Screen Shot 2019-12-11 at 2 36 06 PM" src="https://user-images.githubusercontent.com/101482/70662584-ca331580-1c23-11ea-90e7-46edfb1d52c3.png">

**Comment by cbeer** [comment]
Perhaps this is a caching issue?
