### ISSUE TITLE
Improve date slider design

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#829]
- It is not completely clear what negative numbers mean in either calendar slider. We need some way of visually clarifying that they refer to BCE and before Hijra. Could we use a drop down that switched between (CE and BCE) for the Gregorian calendar and (H and BH) in the Hijri calendar? This would allow the users to not have to think about negative numbers which is causing confusion. Just a thought. We should discuss more. 
- There is no year 0; can we change this to year 1

**Comment by jacobthill** [comment]
<img width="642" alt="Hijri Date" src="https://user-images.githubusercontent.com/37662787/71283932-8af57a80-232f-11ea-8ab9-72f0cd0ef27e.png">
I drew this up to communicate a possible change to the curatorial advisors. I don't know if putting H or BH in the search field will work but it would make things much clearer.

**Comment by ggeisler** [comment]
See the [comment](https://github.com/sul-dlss/dlme/issues/845#issuecomment-568075174) in #845 before implementing this, since it refers to the same thing.

**Comment by ggeisler** [comment]
@jacobthill It's somewhat confusing to have both this and #845 as open tickets, since they overlap significantly. Can we close this ticket and use #845 to finalize what needs to be done in terms of improving the date slider date display?

**Comment by jacobthill** [comment]
@ggeisler yes closing this one.
