### ISSUE TITLE
"Object type" metadata field not displaying in Arabic locale

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#844]
Possibly related to #843.

When in the Arabic locale, on both the search results and item show page, the "Object type" field does not display:

### Results page

<img width="1474" alt="Screen Shot 2019-12-20 at 10 29 38 AM" src="https://user-images.githubusercontent.com/101482/71278486-fda52c80-2314-11ea-9a71-1631894e0024.png">

### Show page

<img width="1339" alt="Screen Shot 2019-12-20 at 10 37 41 AM" src="https://user-images.githubusercontent.com/101482/71278493-01d14a00-2315-11ea-9e62-bbbef311992e.png">

**Comment by jacobthill** [comment]
The same problem occurs with 'date range'.
