### ISSUE TITLE
Some records load in stage but not dev

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#866]
There are many records that, for various reasons, will not load in the application. Confirmed reasons a record might fail to load include:
- it has the same id as another record already existing in the database: a test to check for duplicate ids was written that fixed this
- bad urls in the agg_preview (possibly other fields): this is ultimately a mapping problem but some kind of error code from the application would help diagnose these issues.

Here is an example record that will not load in dev though it will load locally (https://s3-us-west-2.amazonaws.com/dlme-metadata-dev/output-6dadf373-a64a-4c01-8c12-dfddf10b1406.ndjson). I have checked that the json is valid, that the urls in the object are valid and resolvable, that it is not a duplicate record, that no other transformation errors are reported. 

This is currently preventing ~12k records in the harvard/scw collection from loading, and possibly others.

**Comment by jacobthill** [comment]
Update some records will load in stage, the others may have a data error but the records that load in stage won't load in dev.

**Comment by aaron-collier** [comment]
Closing this as we've been able to load these records into both stage and dev. If we need a related issue created around similar problems, we should open new issues.
