### ISSUE TITLE
Implement method to document service availability level

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#878]
Need a way to track service availability and service interruptions for quarterly reports to QNL.

**Comment by cbeer** [comment]
I think we'll need more information from you to make this actionable, most importantly:

- who is the audience for this? Is it only for internal use?
- what do we mean by service availability (and, interruptions)?

**Comment by jacobthill** [comment]
QNL requires this information in a report each quarter. @julianmorley is aware of the need and we are discussing in an email thread how to provide it. I assume by service availability (though I'm guessing because no other clarification was provided) we mean a percentage of time the application was running/working as expected. I assume by service interruptions we need to know when an interruption occurred, why, impact (e.g. how long the service was interrupted), and what we did to resolve it. @waynegraham does that sound accurate?

**Comment by waynegraham** [comment]
The audience is internal (for QNL executive leadership), so something quite simple should work (though we may need to tune). These were the metrics from the agreement:

- Overall Uptime for the period on the production environment (contract stated 98% availability)
- Overall Uptime for the staging environment (contract stated 12x5 availability)
- A list of service interruptions/unscheduled downtime (e.g. None, deployed tag, AWS outage, etc) for each environment

**Comment by jacobthill** [comment]
Learned that this information is available through honeybadger.
