### ISSUE TITLE
Add documentation about how to add records and mappings for testing

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#88]
Identified as a goal in the 8/15/17 sprint planning meeting. Presumably related to #75 too.

**Comment by jcoyne** [comment]
What does "for testing" mean in this context?

**Comment by anarchivist** [comment]
Meaning, how does one test a mapping locally before pushing it up and deploying it?

**Comment by cmh2166** [comment]
Closed by #290.
