### ISSUE TITLE
Change order of record view display fields

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#882]
creator, extent, alternative titles and Is part of (series) are currently at the bottom of the record, we think it should be near the top (or at least above the notes fields)

**Comment by ggeisler** [comment]
@jacobthill Can you include a link to a record that exhibits the situation you describe?

I can't find any records with a "notes" field on -dev or -prod, and on both "creator" appears fairly close to the top of the list of fields.

In any case, you can reorder metadata fields on the Configuration > Metadata page in the admin UI.

I believe I spent a fair amount of time last workcycle ordering and renaming metadata fields on -prod. But -dev (and probably -stage) got out-of-sync when that server was updated earlier this year.
