### ISSUE TITLE
Agg providers with multiple countries only display one

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#883]
American Institute for Maghrib Studies has three countries in the `agg_data_provider_country` field but only one shows up in the statistics dashboard. We need all three to display.
<img width="381" alt="Screen Shot 2020-03-30 at 2 07 03 PM" src="https://user-images.githubusercontent.com/37662787/77946083-c5a47280-728f-11ea-9095-978085dc98b1.png">
<img width="919" alt="Screen Shot 2020-03-30 at 1 56 26 PM" src="https://user-images.githubusercontent.com/37662787/77946091-cb01bd00-728f-11ea-9261-45442f10dc4f.png">

**Comment by cbeer** [comment]
It looks like allowing multiple countries is a recent change to the IR.

@ggeisler -- are there any design changes that need to be made to accommodate this? Presumably Country => Countries,  but  presumably we now need to be concerned  about text wrapping or truncation too?

**Comment by jacobthill** [comment]
Yes, we updated AIMS a few weeks back and that was our first case of a data provider with multiple country values. I think the IR always allowed it but we never implemented it.

**Comment by ggeisler** [comment]
@jacobthill Do these adjustments seem appropriate for handling the multiple country case?

<img width="990" alt="Screen Shot 2020-03-31 at 9 06 38 AM" src="https://user-images.githubusercontent.com/101482/78050405-07392a00-7331-11ea-9019-5bcaf8cb1c80.png">

- Change column header to "Countries" (assuming we are certain the table will include at least one row with multiple countries)
- Comma-separate an institution's countries when it has more than one

@cbeer Good point about the text wrapping issue. I'd suggest we don't worry about it for now, and see how things look with the updates. If the native table column adjustments end up looking awkward (e.g., giving too much width to the Countries column), we could add something simple like an explicit width on the Countries column to keep things more balanced:

<img width="990" alt="Screen Shot 2020-03-31 at 9 11 54 AM" src="https://user-images.githubusercontent.com/101482/78050739-89c1e980-7331-11ea-975b-af5cdd2ff991.png">

**Comment by jacobthill** [comment]
@ggeisler that seems like a good solution to me. Unless AIMS decides they don't want to partner with us anymore we will have at least one institution with multiple countries.
