### ISSUE TITLE
Should DLME logo in site header link to something?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#886]
Issue #884 describes an updated site masthead/header that includes a DLME logo in the topbar.

@jacobthill Do we know if that logo should be linked to something, such as a main page at QNL?

If it's too early to know this, that's fine, it's not a problem to leave the logo without a link until it becomes clear where it should be linked to.

**Comment by jacobthill** [comment]
@ggeisler I don't think we want the main logo to link to anything at this point.

**Comment by ggeisler** [comment]
Okay, thanks, I'll close this. I'm sure it'll be clear if and when we do need to link it to something.
