### ISSUE TITLE
Add QNL logo to footer

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#889]
In recent feedback we received from QNL, one person included the question:

> Have you considered putting QNL logo in the footer? I think our role is both partner and (financial) supporter, so that may be tricky.

We certainly can add QNL to the footer if it's appropriate, which seems likely. To move forward we'd need:

- [ ] Confirmation that QNL should be represented in the site footer
- [ ] Should they have a distinct column in the footer like the existing institutions have, or, since they are both partner and supporter, should we add them to each of the existing sections that currently have the Stanford and Mellon logos?
- [ ] What logo image should we use, which will work on the current blue site footer background color (since that color seems to have been approved by multiple stakeholders)?

**Comment by jacobthill** [comment]
Marcin at QNL is consulting with key stakeholders at QNL and will report back.

**Comment by ggeisler** [comment]
Something like this (the stacked icon/QNL text):

![download](https://user-images.githubusercontent.com/101482/78921790-4dd20700-7a4a-11ea-85bc-a45f87dd6492.png)

should work fine. We'd need a version that has a transparent background.

**Comment by jacobthill** [comment]
From Marcin: "Regarding the logo, for now: can you please put this logo: https://www.qdl.qa/sites/all/themes/QDLTheme/logo.svg in the footer, next to CLIR Logo? I will let you know if I will get any other ideas for that."
