### ISSUE TITLE
Export/import doesn't update properties of existing pages/searches/etc

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#893]
If I understand the recent export/import @cbeer did, it seems like one thing that didn't fully work was the maintaining the visibility state of the facets. 

On DLME -prod we have about 1/3 of the facets unchecked (in Configuration > Search > Facets.

On DLME -dev, after the import, all facets in that configuration section are checked.

**Comment by cbeer** [comment]
This is a broader problem -- import/export works great for populating a new exhibit, but if you try to import on top of an existing exhibit, the old data wins.

**Comment by ggeisler** [comment]
Ah, interesting. I believe we did originally create the import/export feature to address the populate-a-new-exhibit use case ("I want to copy Exhibit A to jumpstart creating new Exhibit B"), so this is not that surprising, now that you mention it.
