### ISSUE TITLE
Update how date range slider displays Hijri dates

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#895]
I'm creating a new ticket for this to clearly separate this issue from:

- General styling/display issues with the date range slider (covered in #765)
- Display of Hijri dates in metadata (covered in #845)

As noted in #845, the concern is that (if I understand correctly) the Hijri calendar starts with year 1, so displaying a value like "-500" as a label on the x-axis of the date range graph and as a value in the date range inputs doesn't really make sense.

### Preferred solution
It's not clear to @jacobthill and I what is technically feasible but here is our preferred solution:

1. For negative year values displayed on the x-axis, drop the minus sign and append "BH" to the year
2. For positive year values displayed on the x-axis, append "H" to the year
3. Do the same as 1 and 2 above for years displayed in the input fields
4. Do the same as 1 and 2 above for years displayed in the active constraint label

<img width="642" alt="71283802-381bc300-232f-11ea-918a-59635810489e" src="https://user-images.githubusercontent.com/101482/78194102-0be50780-7431-11ea-90e7-867ebe9da3ef.png">

(Ignore the flash message shown next to the facet title; this would be very challenging to display nicely in the sidebar version of the facet, and I'm hoping it is not really necessary.)

 ### Potential lesser solution
This is not at all ideal, but I'm worried that the input fields (item 3 above) might be more challenging than the other items, because it needs to be strictly numeric. If that's true, we might be able to get away with just doing:

1. For negative year values displayed on the x-axis, drop the minus sign and append "BH" to the year
2. For positive year values displayed on the x-axis, append "H" to the year
3. Do the same as 1 and 2 above for years displayed in the active constraint label

and leaving the input fields displaying a minus sign, to keep the field numeric-only. It would be very awkward to use different formatting for the input fields versus the labels, but perhaps it will nonetheless be clear to the user (because the numeric values will still match) that "-500" in the input box is shown as "500 BH" on the x-axis. 

I really don't like this solution, but bring it up as possibly better than doing nothing at all, if we can't do all of the preferred solution.

**Comment by cbeer** [comment]
If we do the preferred solution, how should we handle user input? Will they be typing H + BH (and, what variants of that do we need to support?)?

**Comment by jacobthill** [comment]
I think we should opt for the "potential lesser solution". I think having users type letters will be just trading one UX problem for another. This is not perfect but it is an improvement. I think we should also do the same thing to the Gregorian calendar view for consistency.

**Comment by ggeisler** [comment]
@cbeer Good point, maybe that is reason enough to go with the lesser solution as @jacobthill suggests.

I'm on the fence about whether we should do the same thing for the Gregorian calendar (which is why I made this ticket specific to the Hijri version of the component). It would be consistent within DLME, which feels right, but on the other hand aren't people who use Gregorian calendars familiar with the meaning of negative dates in a component like this? But I suppose if we can technically do it for Hijri, it is worth doing for Gregorian and see how it feels.

**Comment by jacobthill** [comment]
Yeah my thought is that there really is no difference between Hijri and Gregorian in this respect except that people are more likely to understand negative to mean BC. There is a precedent with Hijri. Its just not as commonly used because the Gregorian calendar is still in use and people can convey the same idea by referring to the Gregorian year instead of (e.g. 300 years before the Hijra). I think we want the UI to educate people in this respect and having consistency between the calendars will, hopefully, contribute to this end without having to add flash messages or other things to convey the point.

**Comment by mejackreed** [comment]
@jacobthill @ggeisler I've implemented this in English. But I'm curious, how should this look in Arabic?

![Screen Shot 2020-04-03 at 3 10 26 PM](https://user-images.githubusercontent.com/1656824/78405232-4e3b4f80-75bd-11ea-901f-3782283dc447.png)
![Screen Shot 2020-04-03 at 3 09 57 PM](https://user-images.githubusercontent.com/1656824/78405236-50051300-75bd-11ea-8978-fda8e5104a21.png)
![Screen Shot 2020-04-03 at 3 09 53 PM](https://user-images.githubusercontent.com/1656824/78405239-51364000-75bd-11ea-8508-0f42a829fce1.png)
![Screen Shot 2020-04-03 at 3 08 23 PM](https://user-images.githubusercontent.com/1656824/78405241-53000380-75bd-11ea-8019-9e04aeb3d375.png)

**Comment by ggeisler** [comment]
@mejackreed You mean how should the "BH", "H", "BCE" part of the labels display in Arabic? 

If so, let's see if @jacobthill knows. I'm not really sure if there are Arabic translations commonly used for those, and if so, will they reasonably fit into the limited horizontal space we have to work with.

**Comment by mejackreed** [comment]
Yes exactly that question, thanks for clarifying Gary.

**Comment by jacobthill** [comment]
I have a message out to QNL.

**Comment by jacobthill** [comment]
This is what we should use:

CE: م
H: ه
BCE: قبل م
BH:  قبل ه

**Comment by cbeer** [comment]
To the left or right of the digits?

**Comment by mejackreed** [comment]
I've implemented it one way.. not sure if this is correct, but maybe something to react to?

![Screen Shot 2020-04-07 at 8 37 58 AM](https://user-images.githubusercontent.com/1656824/78682486-458f9580-78ab-11ea-80f1-4e061dcd6a6e.png)

**Comment by jacobthill** [comment]
@mejackreed the green font seems correct but the black font at the bottom of the histogram should have the number to the right of the Arabic text

**Comment by jacobthill** [comment]
Which font are we using here? I think this was one of the problems mentioned the م which indicates 'Milady' (Gregorian) is missing the tale that hangs down which makes it look very similar to the ه which indicated Hijri.

**Comment by mejackreed** [comment]
This is the current font deployed in our environments, Mada.
