### ISSUE TITLE
Metadata questions from 8/3/2017

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#9]
* Is the presumption that
    * we should only work from @waynegraham's repo?
    * Wayne will be the one to put records in the repo?
* Are we expecting to leverage the Stanford druid loader in Spotlight or should we work from exports? [@cbeer: NO; Stanford's druid loader is built into exhibits and depends on non-public Stanford infrastructure]
* Can we set the following requirements?
     * We need either a URI or records.
     * We would prefer records.
* Is deduping out of scope?
* Which metadata enhancements do we care about?
* Penn Museum: which collections do we want?
* Do we need notification of changes?

**Comment by anarchivist** [comment]
![image uploaded from ios](https://user-images.githubusercontent.com/73732/28949171-d352767e-786f-11e7-8842-275824e22c82.jpg)

**Comment by waynegraham** [comment]
I'm going to follow this as best I can in the same order:

- Presumptions:
  - I think the items in that repo provide a good place to start (with the caveat that this is really dirty ways of grabbing and cleaning the data and shouldn't be used in any kind real effort). It may be useful to have in place some kind of shared storage space to drop these records in for processing (e.g. S3). 
  - I made this repo out of expediency; it may be worth thinking a bit about where this repo is located, and a bit on who can commit to it.
- Druid loader (no, but that's in the comment)
- Can we set the following requirements:
  - We need either a URI or records: **this seems reasonable**
  - We prefer records: **again, reasonable**
- Is deduping out of scope?
  - At this point, I would say yes. This is, however, something we may need to provide some statistics on for the next phase for planning implementations.
- Which metadata enhancements do we care about?
  - I think this could be its own ticket for discussion, but off the top of my head, for this phase "easy" ones like geocoding, annotation (from IIIF), and maybe an NLP output. Maybe LOD (I know that's vague, but maybe DBpedia links if it's not too difficult)? I think this opens a lot of questions for future development, but if we had one or two that were easily implemented, we could show that this is possible in this phase of the project.
- Penn Museum: which collections do we want?
  - I'll put the pertinent collections in the `dlme-metadata` repo 
- Do we need notification of changes?
  - Right now I would put this out of scope, but on the list for the next phase for planning on implementation
