### ISSUE TITLE
JSON response issues

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#903]
See, for example: https://spotlight.dev.dlmenetwork.org/library/catalog/81055%2Fvdc_100000000831.0x000044_dlme?format=json - separate [link to gist](https://gist.github.com/anarchivist/e97458055fb6386cd86ecd51d8a5e926)

* HTML tag leakage: e.g. `<bdi>`, `<br>`, and `<p>` tags
* id attributes for `holding institution` and `source institution` have spaces: e.g. `https://spotlight.dev.dlmenetwork.org/catalog/81055%2Fvdc_100000000831.0x000044_dlme#source institution` (instead of, say, `https://spotlight.dev.dlmenetwork.org/catalog/81055%2Fvdc_100000000831.0x000044_dlme#source%20institution`

**Comment by cbeer** [comment]
Who is consuming the JSON API?

**Comment by mejackreed** [comment]
My understanding is this was the intent of the [JSON API feature in Blacklight 7](https://github.com/projectblacklight/blacklight/pull/588).  https://earthworks.stanford.edu/catalog/stanford-gd672hm7648.json. We just end up using the raw api approach for MD consumption as an alternative https://earthworks.stanford.edu/catalog/stanford-gd672hm7648/raw .

**Comment by anarchivist** [comment]
Thanks, @mejackreed - it looks like the `/raw` endpoints give me a 404 instead. I'm fine with that approach (I'm most concerned about exposing JSON, rather than JSON:API per se).

**Comment by anarchivist** [comment]
(Should I edit this ticket?)

**Comment by mejackreed** [comment]
We can do https://github.com/sul-dlss/dlme/pull/906 which will remove some of the HTML from the JSON API. Is that what is needed? The raw endpoint doesn't seem to be working for documents with a `.` in them. Something like this does work. https://spotlight.dev.dlmenetwork.org/library/catalog/met_324272/raw

**Comment by cbeer** [comment]
We (Blacklight) are pushing people to consume JSON API instead of our bespoke JSON, so unless there's a consumer for non-JSON-API data, I don't think we should be concerned about exposing the raw JSON documents.

**Comment by anarchivist** [comment]
OK, thanks both. It also seems like multi-valued fields are wrapped in whatever HTML we use to format them. I don't know if this fits the way the implied expectation on the [Blacklight wiki](https://github.com/projectblacklight/blacklight/wiki/JSON-API). 

If it's helpful, I could rework this ticket or pair with someone to do so.

**Comment by anarchivist** [comment]
After pairing with @cbeer, I opened two new tickets: #921 and #922. To be clear, the "raw" endpoint is for internal use; the other gets the API to work in a basic way that allows us to demonstrate it as such. (At this point, it's not something we're going to widely announce it.)
