### ISSUE TITLE
Fielded search does not work for  'author' or 'title'

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#914]
Everything: https://spotlight.dev.dlmenetwork.org/ar/library/catalog?utf8=%E2%9C%93&locale=ar&exhibit_id=library&search_field=all_fields&q=%D9%88%D9%84%D9%88+%D9%85%D8%B1%D8%A9+%D9%88%D8%A7%D8%AD%D8%AF%D8%A9
<img width="940" alt="Screen Shot 2020-04-06 at 3 16 56 PM" src="https://user-images.githubusercontent.com/37662787/78596535-f51c2780-7819-11ea-9676-87c528e00f44.png">

Author: https://spotlight.dev.dlmenetwork.org/ar/library/catalog?utf8=%E2%9C%93&locale=ar&exhibit_id=library&search_field=author&q=%D8%A7%D8%A8%D9%88+%D8%B9%D9%84%D8%A7%D8%A1+%D8%A7%D9%84%D9%85%D8%B9%D8%B1%D9%8A
<img width="929" alt="Screen Shot 2020-04-06 at 3 18 42 PM" src="https://user-images.githubusercontent.com/37662787/78596538-f64d5480-7819-11ea-84e2-fb789dbf4049.png">

Title: https://spotlight.dev.dlmenetwork.org/ar/library/catalog?utf8=%E2%9C%93&locale=ar&exhibit_id=library&search_field=title&q=%D9%88%D9%84%D9%88+%D9%85%D8%B1%D8%A9+%D9%88%D8%A7%D8%AD%D8%AF%D8%A9
<img width="934" alt="Screen Shot 2020-04-06 at 3 17 09 PM" src="https://user-images.githubusercontent.com/37662787/78596546-f77e8180-7819-11ea-8b34-aca152ecd546.png">
The title search above should return https://spotlight.dev.dlmenetwork.org/ar/library/catalog/b1770523x

I'm happy to pair with anyone to clarify as needed.

**Comment by mejackreed** [comment]
@jacobthill would you mind dropping those search links in this ticket please?

**Comment by cbeer** [comment]
It would also help if you could suggest a document that should match for that title search.
