### ISSUE TITLE
Make hierarchical relationship more clear in statistics page

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#917]
<img width="453" alt="Screen Shot 2020-04-06 at 3 30 45 PM" src="https://user-images.githubusercontent.com/37662787/78597505-a7a0ba00-781b-11ea-8726-5c6dc9aeaa44.png">

QNL would like us to make the hierarchical relationship more clear if possible

**Comment by ggeisler** [comment]
@jacobthill Do you have a sense of whether this update (shown in screenshot below) would be sufficient for QNL? It modifies two things:

- Adds a character before the label of children elements to better distinguish children elements from their parent
- Reduces the indent of child elements 

<img width="963" alt="Screen Shot 2020-04-06 at 5 26 20 PM" src="https://user-images.githubusercontent.com/101482/78617429-2998df00-782c-11ea-8f60-f26d900722ba.png">

---

- [ ] Change existing class on `td` elements from `pl-5` to `pl-4` (reduces left padding)
- [ ] Add HTML entity as `::before` content on the  `pl-4` `td`s

```CSS
td.pl-4::before {
  content: "\00BB";
}

**Comment by jacobthill** [comment]
I heard from Asmaa at QNL and she thinks these changes are sufficient but us to ensure that the Arabic looks just as clear. She mentioned that the Arabic was less clear to begin with. @ggeisler can you post an image of the Arabic view?

**Comment by cbeer** [comment]
<img width="769" alt="Screen Shot 2020-04-08 at 07 42 03" src="https://user-images.githubusercontent.com/111218/78797357-7257b180-796c-11ea-8e9a-e6e27be0b1e4.png">

**Comment by camillevilla** [comment]
Note: this PR has already been merged, waiting on confirmation from QNL.

**Comment by jacobthill** [comment]
QNL confirmed that the Arabic is acceptable.
