### ISSUE TITLE
review + repair 3D / Objects split among object types

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/dlme#92]
Europeana to DCMI to MODS to MARC types mappings for `cho_type` and `cho_edm_type` aren't clear on handling objects (3d objects) vs digital representation types (i.e. 3d files).

Depending on decision, need to update translationMapping currently waiting in #65 and fix some config mappings.

**Comment by anarchivist** [comment]
Can we talk about this on standup today? `cho_edm_type` will be a constrained list for faceting, and in my opinion, it should specify what the digital representation should be.

**Comment by cmh2166** [comment]
the list so far for types is here / mapped here: https://docs.google.com/spreadsheets/d/1Sp7uMHizVX7xN7xN9mm-vgEuESQBovXO-qenAo_TV-w/edit#gid=1989427572

**Comment by cmh2166** [comment]
Alright, I'm going to make a PR to update this based on the feedback from the types spreadsheet.
