### ISSUE TITLE
Improve the JSON API to provide a basic workable version

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#921]
This ticket should partially supersede #903. Here's the list of requirements following my conversation with @cbeer:

* [x] Present multi-valued fields as an array, rather than a formatted string 
* [x] Add the intermediate representation whose response is included as a JSON object in reponse (i.e. from the `__raw_resource_json_ss` field in Solr)
* ~If possible, allow `.json` extension to be attended to records (e.g., `https://spotlight.dev.dlmenetwork.org/library/catalog/met_322492.json` currently returns a 404, but `https://spotlight.dev.dlmenetwork.org/library/catalog/met_322492?format=json` works)~ (see [@cbeer's comment](https://github.com/sul-dlss/dlme/issues/921#issuecomment-610040322))

**Comment by cbeer** [comment]
Without control over the identifiers coming in, I don't think we can (reliably) support format suffixes.

**Comment by anarchivist** [comment]
OK, thanks @cbeer. I'll cross this out as a requirement for now (ditto on #922)
