### ISSUE TITLE
Wrong number of contributors in statistics page

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#928]
<img width="913" alt="Screen Shot 2020-04-07 at 1 08 59 PM" src="https://user-images.githubusercontent.com/37662787/78698924-10963980-78d1-11ea-8df8-5c15e684b7d6.png">

I'm not clear where the contributors are coming from but my understanding is that this should be dynamically updated when new data is loaded. There should be more contributors. `Providers (Indirect)` has 22 institutions and `Providers (Direct)` has 20.

**Comment by jkeck** [comment]
One thing that #923 may not account for is the distinction between Direct and Indirect contributors.  We're using the data that is driving the facet labeled "Direct" and would not get the (presumably 2) institutions that in "Indirect" that are not in "Direct".  If we should be driving the list of contributors from a different facet, perhaps we can file a new issue to address that.

**Comment by jacobthill** [comment]
@jkeck I'm not sure if this is possible but the ideal configuration would grab both "Direct" and "Indirect" and then count unique strings. This would always ensure that every institution is counted and paint the best picture. Is that manageable?

**Comment by cbeer** [comment]
Can you make a new ticket for that new request?

**Comment by jacobthill** [comment]
Here is the new ticket https://github.com/sul-dlss/dlme/issues/930
