### ISSUE TITLE
Adjust contributors source to pull from Provider "Direct" and "Indirect"

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#930]
The contributors value ideally should take all values from `Provider (Direct)` and `Provider (Indirect)` and return a count of all unique values.

**Comment by cbeer** [comment]
I just want to confirm, when you say "all unique values", we're talking string uniqueness, so e.g. "Harvard University's Libraries and Museums" and "Harvard University Library" will count as 2 separate contributors?

**Comment by jacobthill** [comment]
Yes, that is correct.

**Comment by ggeisler** [comment]
@jacobthill Just so I understand this (haven't paid too close attention to details about the providers), are "Harvard University's Libraries and Museums" and  "Harvard University Library" (to use @cbeer's example) actually two independent contributors? Or are the provider labels just stored differently in the Provider (Direct) and Provider (Indirect) objects?

**Comment by cbeer** [comment]
In my example,

"Harvard University Library" is the direct contributor of 11737 records
"Harvard University's Libraries and Museums" is the indirect contributor of 11707 records
and "Harvard University. Center for Geographic Analysis" is the indirect contributor of 30 records

Under this ticket, I believe we're saying we'd count that as 3 separate contributors?

**Comment by jacobthill** [comment]
That example is correct. I realize it kind of inflates the number a bit but this is the correct implementation of the EDM values our data model is based on and, if we don't do it like that, we don't represent some institutions (e.g. Openn which isn't in dev yet pulls from multiple institutions which wouldn't be counted, etc.) If I find that "Harvard University Library" and "Harvard University's Libraries and Museums" is not a useful distinction I can just change one of the values in the settings file and re transform.

**Comment by cbeer** [comment]
Also, is this just for the contributor counts, or will it affect the content of the contributors table too (in which case, I think we'd see at least a few contributors doubled up there?)

**Comment by jacobthill** [comment]
It should effect the table and there shouldn't be any duplication. I can't remember why we added  "Harvard University Library" and "Harvard University's Libraries and Museums" but "Harvard University. Center for Geographic Analysis" is definitely a separate organization. In cases where it seems like data is being duplicated I will double check that the information in the settings file is correct and make changes as needed. I think we just need to make sure we don't leave any contributors off the list.

**Comment by anarchivist** [comment]
Can we clarify why we're looking to combine the two types of providers? If I'm not mistaken, this is combining `agg_provider` and `agg_data_provider`, which have two different purposes:

* "Direct provider," or `agg_provider`, is where we got the metadata. These are the This is most often one of two cases: an institution, if we harvested them directly, or potentially some kind of aggregator or digital object host. For example, we have harvested a bunch of materials from the BnF's Gallica portal, which hosts/aggregates digital objects for not just BnF, but also a number of contributing institutions in the region. In other cases, we may have harvested materials from a single institution like American University in Beirut.
* "Indirect provider," or `agg_data_provider`, is the institution that provided the `agg_provider` with the metadata. It refers to the institution in charge of the cultural object and which has created the related metadata. In some cases, the `agg_data_provider` and the `agg_provider` are identical (e.g. for Cambridge University Library), and in other cases, it might be different (e.g. Qatar National Library hosts the British Library's India Office Records, which are presented on QDL). 

The role of these contributors are different from the standpoint of aggregation, and I'm not sure what we get by combining them into a single count. Merging them into a single contributors field removes this nuance.

We should probably retain counts for both of these values independently in the dashboard - I expect that this is the type of information we want to present e.g. into reports to stakeholders/funders. If we need a combined count, that should be displayed (and labeled) separately.

**Comment by jacobthill** [comment]
@anarchivist Maybe we need two counts and maybe there is some confusion about what 'contributor' means. Here is a diagram that shows some potential data loss with choosing one or the other:
<img width="934" alt="Screen Shot 2020-04-07 at 5 10 46 PM" src="https://user-images.githubusercontent.com/37662787/78720096-1270f480-78f3-11ea-8d3c-d5c95a83cb3c.png">

It seems like we don't want to lose any of that information but maybe we need to figure out a better way of representing it in the dashboard. I'm open to suggestions.

**Comment by ggeisler** [comment]
What about displaying two versions of the Contributors table, one for "Direct provider" and one for "Indirect provider"? We'd have to come up with a good label for each table to make more clear what the difference between the two is, and it will make the Statistics page longer, but maybe populating the two tables will be straightforward that way.

**Comment by anarchivist** [comment]
I think that's probably the best option, and we should probably tweak the labels for each provider for them to be a bit clearer.

**Comment by jacobthill** [comment]
"There are only two hard things in Computer Science: cache invalidation and naming things."
-- Phil Karlton

I find myself struggling to come up with reasonable names for these sources. I personally think Europeana chose vague names and now we are trying to make them more clear. There seems to be a desire to name these things something users will understand and find useful. We concluded last work cycle that maybe we don't need both as facets on the home page because of the overlap but that creates a problem: the average user probably cares more about which institution is stewarding the physical objects. Agg_Data_Provider is a better proxy for that but if we only include that, we leave off QNL and other significant contributors. From the perspective of the aims of DLME to build partnerships Agg_Provider is more important and those partners need to be represented. I think we need to include both options on the home page and in the dashboard. Below is an attempt to rename them. Let me know what you all think.

|                | EDM:Provider (Agg_Provider) “Direct”                                                                               | EDM:DataProvider (Agg_Data_Provider) “Indirect”                                                                    | Notes                                                                                                                                                                                                                                                                                                                   |
|----------------|--------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| EDM Definition | The name or identifier of the provider of the object (i.e. the organisation providing data directly to Europeana). | The name or identifier of the data provider of the object (i.e. the organisation providing data to an aggregator). |                                                                                                                                                                                                                                                                                                                         |
|        1       | Direct Provider                                                                                                    | Indirect Provider                                                                                                  | Still somewhat vague.                                                                                                                                                                                                                                                                                                   |
|        2       | Data Aggregator                                                                                                    | Data Provider                                                                                                      | One downside of this option is it gives the false impression that these institutions are aggregating metadata. In some case that is true but in most cases they are just sharing their own data.                                                                                                                        |
|        3       | Aggregator                                                                                                         | Data Provider                                                                                                      | Same issue as option 2.                                                                                                                                                                                                                                                                                                 |
|        4       | Data Aggregator                                                                                                    | Data Source                                                                                                        | May provide the false sense that we know more about the provenance of the metadata than we do. E.g. I think BnF collected data but then altered it so they are kind of more than a "data aggregator." This is true of QNL too; they outsourced the creation of the English metadata but created the Arabic themselves.  |
|        5       | Data Contributor                                                                                                   | Collection Steward                                                                                                 | I feel like this is what we want to capture in the dashboard but this may drift too far from the intentions of Europeana.                                                                                                                                                                                               |

**Comment by camillevilla** [comment]
Resolved via discussion at sprint planning:
- Item contributor
- Data contributor

**Comment by cbeer** [comment]
Replaced by #936.
