### ISSUE TITLE
Add 'Suggest a collection' form

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#934]
Until now we have been using a Google form to solicit suggestions for new collections that was linked to the CLIR site which will be discontinued. We now need a dedicated form linked from the about page.

This is the wording currently used on the Google form:

"Would you like to recommend a digital collection for inclusion in the DLME? Let us know here!"

Field 1: "Title of the collection"

Field 2: "Url of the collection"

Field 3: "Name and email address of contact at the institution responsible for stewarding the collection"

Field 4: "Description of collection"

Field 3 could be split into two if that is desirable. So far no one has indicated confusion with any of this wording but if something seems unclear I can try to clarify.

**Comment by cbeer** [comment]
Could we continue to use that google form and just link to it?

**Comment by ggeisler** [comment]
I suggested to @jacobthill I could mockup both approaches (integrated into an About page versus linking to a Google form) and we could evaluate the technical effort/UX benefit tradeoff of each.

But when I suggested that I was forgetting about our About pages not being static pages we could easily drop a form into. So maybe the approach should be improving the Google form page + figuring out the location and wording of the text linking to the form.

**Comment by cbeer** [comment]
Could you iframe a google form?

**Comment by ggeisler** [comment]
@jacobthill @cbeer Embedding the google form seems like a potentially good compromise. It looks like you can generate an embed URL we should, in theory, be able to add to the iframe widget in an about page.

@jacobthill I'm happy to work with you on:

- Do a test and make sure we can embed your current Google form in an About page
- Assuming we can, work on updating the Google form (wording if necessary, but layout and colors to make sure it matches the DLME theme decently
- Creating an appropriate about page context around the embedded form

**Comment by jacobthill** [comment]
@ggeisler I'm available whenever it makes sense to start on this but its probably a lower priority than some other design tickets you are working on. Let me know when you get through all of the higher priority work and we can touch base on this.

**Comment by ggeisler** [comment]
@jacobthill Here's a first pass at embedding the form: https://spotlight.dev.dlmenetwork.org/library/about/suggest-a-collection

I created a new form, which we'll probably want to redo or move since I get the responses from it. But you can review the questions there (or see below). It seems to work and fit into the site pretty well, other than duplicating the page title and the form title, which doesn't seem avoidable.

<img width="1154" alt="Screen Shot 2020-04-20 at 5 42 38 PM" src="https://user-images.githubusercontent.com/101482/79812741-a77ddf80-832e-11ea-9e50-f81e8943be12.png">

**Comment by jacobthill** [comment]
Thanks @ggeisler. It looks good overall. Question three should be changed to 'email address' instead of 'address'. Is there a way to remove the title from the google form and add it only in the html? If this is not possible then we can go ahead anyway.

**Comment by ggeisler** [comment]
@jacobthill As I said above, duplicating the page title and the form title doesn't seem avoidable. But this is not a high profile page, so while the duplication would ordinarily bother me a lot, in this case I'm okay with it. It's better than sending the user away from the site to fill out the form.

I've fixed Q.3.

I think the remaining issue is where the put the form. It's currently in my personal Google Drive space, but that's not a long-term solution. Let me know where you think we should store the form long-term and I can either try to move it there (I'd need the Drive directory shared with my gmail address, I believe) or you can recreate the form in that space (you'd need to change the theme color to `#0f2450` and everything else is pretty obvious from looking at my example of the form).

**Comment by jacobthill** [comment]
Ok, you can put the form here: https://drive.google.com/drive/u/1/folders/1-qxumLrirbAS0Vm6ZnNcAsKFmbkTFSLN

**Comment by ggeisler** [comment]
Done. 

@jacobthill I suggest you verify that you can edit the form and see the responses, and if so, close this ticket. (If you can edit the form and see the responses, so should Elizabeth and anyone else with access to that Drive folder.)
