### ISSUE TITLE
Review DevOps docs

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#935]
Someone from access team needs to review https://github.com/sul-dlss/DevOpsDocs/tree/master/projects/dlme and make corrections as needed.

**Comment by camillevilla** [comment]
Seeking review + confirmation from Ops and Infra re: the current level of documentation for this project, given that it's an AWS project. Open q's:
- are the deployment instructions *clear*?
- do we have a clear escalation path? 
- how does our SLA differ while working with external stakeholders?

Email re: meeting to discuss has been sent out.
