### ISSUE TITLE
Update Statistics page to show both Item Contributors and Data Contributors

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#936]
Based on our decision in #930, we need to update the Statistics page accordingly. Here are the changes that I think need to be made. I assume that whoever works on this knows how to populate the two displays "item contributors" and "data contributors" based on #930.

@jacobthill please review the suggestions below and correct me if necessary.

## Update the jumbotron summary boxes
- [x] Replace the third box with two boxes, one titled "N item contributors" and one titled "N data contributors". Ideally there is about `1rem` of margin between the boxes (no margin necessary on the left of the first box or the right of the last box). Here's a rough idea, though my quick attempt resulted in the boxes overflowing the left and right page content areas, which we don't want:

<img width="1074" alt="Screen Shot 2020-04-09 at 11 08 29 AM" src="https://user-images.githubusercontent.com/101482/78927324-8a563080-7a53-11ea-9bde-45d3414484be.png">

## Update the Contributors table
- [x] Replace the existing Contributors table with two similar tables, one titled "Item contributors" and one titled "Data contributors". 

I assume the existing table columns all still make sense for both tables.

<img width="969" alt="Screen Shot 2020-04-09 at 11 09 09 AM" src="https://user-images.githubusercontent.com/101482/78927493-dbfebb00-7a53-11ea-9f52-c9d9a1397b8c.png">

---

<img width="969" alt="Screen Shot 2020-04-09 at 11 09 42 AM" src="https://user-images.githubusercontent.com/101482/78927505-e15c0580-7a53-11ea-8526-be0f3c1e2d5a.png">

**Comment by jacobthill** [comment]
I think it looks good except maybe the numbers are mixed up. `Data contributors` should pull from `agg_provider` which has 20 unique values and `item contributors` should pull from `agg_data_provider` which currently has 23 values. @anarchivist can you confirm? I've been confused by this before. Just want to make sure we're all on the same page.

**Comment by ggeisler** [comment]
@jacobthill The numbers in my screenshot were totally random, not based on real data. I mean, I left the 20 that was there for Contributors, and just picked 23 at random to show the Data contributors would be different. That was just a Web inspector edit, not an attempt to reflect the actual count (I figure the developer who works on this will know how to get the correct counts).

**Comment by jacobthill** [comment]
I think it was clear, but just in case it wasn't, I agree with the proposed solution.

**Comment by cbeer** [comment]
@ggeisler what data goes in the contributors section of the first box (and, do we want to change the label?)

**Comment by ggeisler** [comment]
@cbeer I'm assuming you mean the first jumbotron box and the "20 contributors" label in my question below (if that's wrong, please correct me).

@jacobthill can we use the item contributors as the source for the  "20 contributors" label in the first, "63 collections" summary box?

To me, the items are the primary thing that make up the collection, so it makes sense to base the count on the item contributors, but you have a better understanding of what might make the most sense here.

If so, I guess we should update the label to "20 item contributors" to remove any ambiguity. Good catch @cbeer.

**Comment by jacobthill** [comment]
<img width="926" alt="Screen Shot 2020-04-21 at 9 28 26 AM" src="https://user-images.githubusercontent.com/37662787/79871544-7cd56a80-83b2-11ea-8e94-cee290190b70.png">

It is correct as is. Item contributors should be the second point in the first box as in the screenshot.
