### ISSUE TITLE
Customize site masthead structure and styling, Version 2

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#937]
Replaces #884. That ticket has a long description and it seems easier to start with a fresh one.

The main goal is to customize the site masthead structure; I'll provide some styling suggestions but after the structure is in place, I can refine colors and font-sizes as necessary in a follow-on PR.

As an overview, we're sticking with the current default Spotlight main menu and search box bar. The customizations we need are:

- Make the topbar taller to accommodate the DLME logo and site title
- Add the DLME logo to the topbar
- Move the site title `H1` into the topbar
- Enable the masthead background image to extend up so it is underneath the entire masthead section, including the topbar (so we can have it show through the semi-transparent topbar)

## LG and XL viewports
<img width="1095" alt="Screen Shot 2020-04-08 at 3 52 25 PM" src="https://user-images.githubusercontent.com/101482/78840968-09465d00-79b1-11ea-9d50-f52cc93735c5.png">

### Masthead height and background
- The total height (including topbar section) should be about `178px`, but it can be determined by the heights of the individual sections.

- The masthead background image: `background-light-blue-mosaic.png` 

### Masthead topbar
- Topbar height:  should end up about`66px`
- Topbar background color: `#0F2450`
- Topbar font color: `#ffffff`

- Logo image: `DLME-logo-transparent-white.png` at `50px` height. The logo is not linked.
- Logo image top and bottom margin: `8px`
- Logo right margin: to get the horizontal space between the logo and the site title, I did:

```CSS
.topbar .navbar-logo {
  flex: 0 0 80px; // was 0 0 150px
}
```

- Site title (`Digital Library of the Middle East`): `2rem`
- Site title vertical placement: centered with the logo; I gave it `margin-top: 1rem;` but there is a probably a better way to ensure vertical centering in the topbar
- Topbar utility links: `1rem` (same as current), `#ffffff` (changed)

### Masthead body (menu and searchbox section)
Everything is standard Spotlight, except in my mockup I'm showing the active menu item with a blue (`#0F2450`) background behind it to indicate that it's linked. This is how we did the main menu before the BL7/BS4 upgrade but we lost that because the `.navbar` element now has top and bottom padding, which prevents the highlight background from extended the full height of the menu bar, so it looks weird. We can try to stick with depending on the font color change of the active menu item to indicate it is active, but if we can figure out how to show the active item like in the mockup, that would be better.

### Body background color

`body` background color: Change to `#f7f7f7`.

## Responsive considerations
Below are responsive adjustments needed when the viewport is below the `LG` (`992px`) viewport width. These are general suggestions; feel free to do things differently when it makes sense. The goal is to approximate the screenshots and I can tweak later.

### MD viewport
<img width="800" alt="Screen Shot 2020-04-08 at 4 28 20 PM" src="https://user-images.githubusercontent.com/101482/78842828-fc783800-79b5-11ea-9f7e-b06d9c048f21.png">

- Site title: Reduce font-size to `1.75rem`
- Site title top-margin: Reduce to `0.5rem`

### SM viewport
<img width="619" alt="Screen Shot 2020-04-08 at 4 33 20 PM" src="https://user-images.githubusercontent.com/101482/78843091-af489600-79b6-11ea-8f5c-69e82b5e44ba.png">

- Site title: Reduce font-size to `1.5rem`
- Site title top-margin: Reduce to `0.5rem` (same as MD)
- Reduce logo size and right-margin:

```CSS
.topbar .navbar-logo {
  flex: 0 0 60px; 
}

.navbar-brand {
  margin-right: 0rem;
}
```

### XS viewport
<img width="440" alt="Screen Shot 2020-04-08 at 4 40 12 PM" src="https://user-images.githubusercontent.com/101482/78843432-a3a99f00-79b7-11ea-940e-41cf6b153291.png">

- Site title: Reduce font-size to `1.25rem`
- Site title top-margin: Reduce to `0.5rem` (same as MD and SM)
- Logo: `display: none`

## Logo image file
![DLME-logo-transparent-white](https://user-images.githubusercontent.com/101482/77951095-5b370680-727e-11ea-81c2-65581ea6dbd1.png)

## Masthead background image file
![background-light-blue-mosaic](https://user-images.githubusercontent.com/101482/77951103-60945100-727e-11ea-9ac6-b27c9e0e6556.png)

**Comment by cbeer** [comment]
Do we need to consider browse categories with a custom masthead (or maybe that feature won't be used for DLME)?

**Comment by ggeisler** [comment]
No, I think it's safe to assume we won't use that custom masthead option in DLME.
