### ISSUE TITLE
Search box options missing when on Statistics page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#944]
It looks like the custom Statistics page is not getting the search box options menu applied to it, unlike the other pages of the site:

### Statistics page

<img width="902" alt="Screen Shot 2020-04-14 at 11 37 09 AM" src="https://user-images.githubusercontent.com/101482/79261341-8b68d280-7e44-11ea-8f1b-127e6967371b.png">

### About page (and all other pages)

<img width="902" alt="Screen Shot 2020-04-14 at 11 37 15 AM" src="https://user-images.githubusercontent.com/101482/79261362-928fe080-7e44-11ea-9086-3a3efeee34dd.png">

**Comment by cbeer** [comment]
Fallout from https://github.com/sul-dlss/dlme/pull/929?
