### ISSUE TITLE
Update facets labels, visibility, and order

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#961]
Part of #960.

**Comment by jacobthill** [comment]
@ggeisler I took a stab at this. I couldn't figure out how to remove `Empty Fields`, `Shown At`, `Shown By`, `Thumbnail`, and `Indexed At` but these aren't very useful to the end user so should remove them if possible. Any idea how to do that?

**Comment by ggeisler** [comment]
@jacobthill A normal user (non-logged in user) shouldn't see those fields, but I just tested with an incognito window and do see them, so I'll create a ticket for it.

**Comment by jacobthill** [comment]
Thanks, that's what I thought but I logged out and they still showed for me as well.

**Comment by jacobthill** [comment]
@ggeisler we can close this if you don't have any other suggestions.

**Comment by ggeisler** [comment]
I like that we have the list of facets down to a pretty small group (now that regular users won't see the admin-only facets).

But I also wonder if exposing the Temporal (Time period) and Spatial (Geographic region) fields as facets would be helpful to users forming a search? They feel more useful -- at least for less sophisticated users such as high school students or undergraduates -- to find subsets of items than Item or Data contributor. Item or Data contributor seem useful to either very knowledgable users who already know which institutions hold collections of interest to them, or to project stakeholders and contributors.

So I'd lean toward exposing the Time period and Geographic region facets, and ordering them  before the contributor facets.

**Comment by jacobthill** [comment]
The problem I see with using Time period and Geographic region is that neither of them are normalized and both lists are quite long. A user would have to browse through hundreds of options and then there would be many concepts that are expressed in various ways (e.g. Iran, Persian Empire, etc.) I agree that the concepts would be useful but I think we need to normalize the values first and then reconsider based on how many options there are. I personally think if the values exceed 50 or 60 there are too many to browse.

**Comment by ggeisler** [comment]
Okay, sure, makes sense. That's why I wanted you to make the final call.

(Technically, as a general rule I wouldn't rule out a facet just because it has many values. We do show a "more" link at the bottom of facets with more than 10 values, and in my opinion it's pretty easy to navigate a few pages of values in the resulting modal. But your point about the values not being very well normalized in DLME is probably the deciding factor here.)
