### ISSUE TITLE
Update metadata field labels, visibility, and order

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#962]
Part of #960.

**Comment by jacobthill** [comment]
@ggeisler I tried to adjust these. Take a look and let me know if you think any other changes need to be made.

**Comment by ggeisler** [comment]
@jacobthill My main feedback is whether some of the current labels will make sense to the user, or if we can figure out a label that might be more immediately clear. I don't know the data thoroughly enough to be sure of anything, so these are just some fields to reconsider.

<img width="626" alt="Screen Shot 2020-04-21 at 3 40 15 PM" src="https://user-images.githubusercontent.com/101482/79921417-0010b380-83e7-11ea-9f96-bd92f6cbc52f.png">


**A:** I haven't seen a record with a value for Source yet, so not sure what sort of values it might have, but given we already have Creator, Contributor, Item Contributor, and Data Contributor, I wonder if Source should have a more specific label? It feels very generic.

**B:** Would  "Geographic region" be more user-friendly than Spatial?

**C:**  Would  "Time period" be more user-friendly than Temporal?  

**D:** I this is for an alternative title? If so, maybe "Alternative title"?

**E:** Not sure what sort of values Coverage has in DLME, so I don't have a suggestion for a better label, but it doesn't strike me as too user-friendly.

**F:** Would "Related to" be better than Relation?

**G:** I've forgotten what these all are, but we definitely should not be displaying "any of the Agg * *" fields with those labels to site visitors.

### Field order
Generally the order of the fields looks fine to me. I'd move Publisher way up, though, below Item Contributor maybe. And Coverage feels like it would fit better with the Spatial and Temporal fields.

**Comment by jacobthill** [comment]
A: Source is defined in our application profile as "A related resource from which the described resource is derived." It could be changed to "Source record" or something along those lines but I also think the value will likely be a url that a user can follow to understand by example what is meant. Not sure if we should change this or what we should change it to.

B: Changed to "Geographic region"

C: Changed to "Time period"

D: Changed to "Alternative title"

E: We could change this to "Geographic or temporal coverage" but that is a mouth full.

F: Changes to "Related to"

G: I took all the Agg fields off. Agg EDM rights and Agg Dc rights are never used and Agg is Shown at is redundant given the "View on contributors site link"

I changed the field order as suggested.

**Comment by ggeisler** [comment]
Okay, those sound good. I'm okay with leaving Coverage and Source as is. I do have a few more things to think about:

- If we're going to display the Data contributor field as a facet, I think it needs to be exposed as a metadata field as well. It doesn't make sense for a user to be able to select by a facet value and then not see the value on the item details page, I don't think.

- I think there are too many fields exposed for the search results view. In particular, exposing the Description field in search results can make the result items very long (Description can have very long values). We want the user to be able to scan the results list easily to quickly find items of potential relevance, so keeping the result item sections compact while exposing the fields that will best help determine potential relevance is the goal. 

- For the reason above, I'd also consider removing Source, Provenance, and Attribution from the search results view. They don't strike me as fields that would commonly help a user decide whether to select the item to see more details or not.

**Comment by jacobthill** [comment]
I implemented all of the suggested changes.
