### ISSUE TITLE
Reduce indent in hierarchical type facet

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#966]
<img width="216" alt="Screen Shot 2020-04-21 at 3 28 52 PM" src="https://user-images.githubusercontent.com/37662787/79905913-f5edb580-83e4-11ea-9edd-b857c30d730b.png">

**Comment by ggeisler** [comment]
It looks like we can just remove this padding:

```css
.facet-hierarchy .h-leaf {
    padding-left: 1.3em
}
```
and get a reasonable indent (except at `md` viewport):

<img width="290" alt="Screen Shot 2020-04-22 at 9 06 31 AM" src="https://user-images.githubusercontent.com/101482/80005680-c7b9b580-8478-11ea-9189-95b6ff5a3bc4.png">
