### ISSUE TITLE
Exclude search results info box on browse detail page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#976]
In DLME we added a flash message/info box on search results pages to inform the user that they might get better results by entering their query in another language. Our current implementation of this includes displaying the message for browse pages:

<img width="1046" alt="Screen Shot 2020-04-27 at 9 54 17 AM" src="https://user-images.githubusercontent.com/101482/80399083-7ab95300-886d-11ea-8541-a34729351ea7.png">

This is potentially confusing to the user, since the user did not form the query for the results they see on the browse detail page. So it would be better to omit the message on browse detail pages.

In DLME we're using the option to display the search box on browse detail pages (I removed it from my screenshot above to make the issue more clear), so a user could potentially enter a query _after_ arriving on a browse detail page, and the message would be relevant to that next iteration of the browse detail page, the one containing the subset of results from their query.

<img width="1046" alt="Screen Shot 2020-04-27 at 10 03 47 AM" src="https://user-images.githubusercontent.com/101482/80399662-704b8900-886e-11ea-81b7-0e7f3b4ef04a.png">

### Ideal solution
So the ideal solution would be to omit the flash message/info box from the initial display of a browse results page, but display it if the user conducts a search from a browse details page.

### Fallback solution
If it isn't feasible to do the ideal solution, I'd suggest we omit the flash message/info box from browse pages altogether.

**Comment by cbeer** [comment]
Would it be ok if we just omit the info box if there's no user query for all searches (browse or otherwise)?

**Comment by ggeisler** [comment]
Yep. I didn't think about the other scenarios (facet-only search) but you're right, the same solution would make sense there.
