### ISSUE TITLE
Error when sending contact email confirmation on localhost

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#979]
Not sure if this is DLME-specific or a bug that crept into Spotlight. It's probably only relevant when running locally but since I think it used to work (it definitely used to work in Spotlight, not sure about DLME) I thought it might be worth filing a ticket.

When I'm running DLME locally and use the "Resend confirmation?" action on the Configuration > General, Basic Settings page, I get the following error:

<img width="1039" alt="Screen Shot 2020-04-27 at 3 16 25 PM" src="https://user-images.githubusercontent.com/101482/80426471-9d159580-889a-11ea-9f8c-b8c96fe89ef0.png">

At least in Spotlight, this used to work: I'd get a flash message saying an email has been sent, and then I could go to the Rails log and copy the validation link that would appear in the email on a real server and use that to validate the contact email.

EDIT: This affects a couple of other features as well. I get the same error when trying to add a new user (Config > Users) and when trying to import an export.json to a new exhibit.

**Comment by mejackreed** [comment]
@ggeisler You should be able to configure a local setting here in your application to bypass this. 

Create file `config/settings.local.yml`

```diff
action_mailer:
  default_options:
-    from: ~
+    from: test@replytodlme.com
  default_url_options:
-    host: ~
+   host: www.test.dlme.example.com
-    locale: ~
+   locale: en
```

This has been kind of our standard approach with these types of configs for applications, but maybe there is merit to checking in some fake default values for development?

**Comment by ggeisler** [comment]
Thanks @mejackreed that works. I'll leave it up to the team to decide if it's worth adding a development default for people like me that forget to configure a local setting, but this solves my immediate problem for DLME so I'm not opposed to closing this if you all decide it's not worth adding a dev default.

**Comment by cbeer** [comment]
Yeah, I think it's fine to close because even if we set a default, there's no guarantee it's the right one for someone's environment.
