### ISSUE TITLE
Import to -stage produced an "Something went wrong" exception

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#980]
I first removed almost everything from -stage (deleted browse categories and pages, turned off all facets, etc.) to try to get it as close to a blank exhibit as possible.

I then exported from -dev, and tried to import that into -stage.

A lot of things appeared to work, though other things didn't work. It's hard for me to assess what worked and what didn't, though, since I assume the exception stopped the process in the middle somewhere.

I can clear off -stage so we can try it again, but for the time being I left in it the state it was in when I got the exception during import. Perhaps @cbeer can learn something from the logs?

**Comment by cbeer** [comment]
I'm pretty sure this is just temporary until we get our new import/export code out to -stage.

**Comment by ggeisler** [comment]
Ah okay, I forgot about that part (since I couldn't try locally because of #979, I thought, _I'll just do it on -stage_). I'll try again when the code is on -stage.

**Comment by jkeck** [comment]
And just as a heads up, I'm still working through getting my env setup for that deploy (in like the last 10 of 100 steps).  My hope is to have the final access setup by the morning and DLME updated in stage, but if not maybe somebody else can get the deploy out (since I'll be taking most of the day off).

**Comment by cbeer** [comment]
Confirmed it works. Note that, unless images are re-uploaded to -dev (or some other data remediation happens... which given the pain of getting into a Rails console in our AWS environment would not be my first choice), all image references still point over at the dev environment.
