### ISSUE TITLE
Import/export issues

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#982]
@cbeer did an export for -dev and import to -stage. Here are the things I notice that still don't work as I expected. It would be good to clarify whether my expectations are wrong, or if these are still things that need to be fixed in the import/export process.

- Configuration > Search, Options settings not imported (I deliberately turned off search box display on -stage prior to the import and it is still off, though it is configured on in -dev)

- Configuration > Search, Facets settings not imported (in -dev I selected a subset of facets to display, and renamed some facet labels; in -stage all facets are on with their default labels)

- Configuration > Search, Results settings _might_ not work; I base this on the fact that the other Search settings are not working, but I didn't change the Results settings from the default on -dev so it's not possible for me to be sure

- Configuration > Metadata - the selected fields and label overrides on -dev were not imported to -stage

- Configuration > Users - there are many more users on -dev than there are on -stage

- Curation > About pages, Contacts - the contact info that is set to be visible on -dev was not imported into -stage

**Comment by cbeer** [comment]
#2527 should fix the blacklight configuration issues (labels, settings, etc).

We're not importing or exporting users  or their privileges (and if we did, it'd lead to some weird results.. if nothing  else, any newly created users wouldn't be able to log in because we can't take  their passwords with us).

I'm not sure what to make of contacts -- importing them locally into a new exhibit worked just fine.

**Comment by jacobthill** [comment]
@cbeer @ggeisler does this need to stay open or has it been resolved?

**Comment by ggeisler** [comment]
@jacobthill I believe the last export/imports we did worked fine, though I think @cbeer might have been the one to do them. So this is closable from my point of view.
