### ISSUE TITLE
Feedback form not sending email or creating JIRA ticket

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#986]
The feedback form on prod does not send an email or create a JIRA ticket. It should be set to dlme-feedback@lists.stanford.edu.

**Comment by cbeer** [comment]
It looks like the email wasn't configured within the application. I've added it, and see every indication the confirmation email was sent correctly, so let me know if you don't get it.

![Screen Shot 2020-05-06 at 12 29 05](https://user-images.githubusercontent.com/111218/81219804-30368580-8f95-11ea-8cba-192d23eb36ca.png)

**Comment by jacobthill** [comment]
I didn't get a confirmation email. I tried submitting the form again and that didn't work either.

**Comment by kamchan** [comment]
it does look like something is blocking sent emails from a @lists.stanford.edu to another @lists.stanford.edu.

@jacobthill did the owner (maybe you're one of them) of the dlme-feedback@lists.stanford.edu get any held/bounced emails?  (ie requires approval etc.).  Trying to see if there are any stanford mailman configs that can get around the sender @lists address.  If not, will have to open a case with UIT.

**Comment by jacobthill** [comment]
I am the owner and I didn't get any held/bounced emails that were waiting for approval.

**Comment by kamchan** [comment]
can you please add me as one of the owners for now?  You can remove me after this issue has been resolved.  thanks

**Comment by jacobthill** [comment]
I added you as an owner but the issue seems to be resolved. Not sure who/what fixed it but I was able to submit the form and get an email. I'll assume that this is no longer an issue.
